package ProgramaColecionadores;

import Jogo.Cartas;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tábata Gianelli
 */
public class JIFrameJogo extends javax.swing.JInternalFrame {
    Jogo jogo;
    int idUserLogando=Principal.getIdUserLogando();
    Atividade atividade;
    private Atividade atividadeEditar;
    private boolean visitante;
    private Image img;
    /**
     * Creates new form JIFrameJogo
     */
    public JIFrameJogo() {
        
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas 
        this.jogo = new Jogo();
        this.Editar.setVisible(false);
        this.Salvar.setVisible(false);
        this.visitante = false;
        solicitarTroca.setEnabled(true);
        Trocar.setVisible(false);
    }
    public JIFrameJogo(Jogo jogo){
        this.idUserLogando=Principal.getIdUserLogando();
        if(idUserLogando!=jogo.getIdUsuario()){
        this.visitante=true;}else{this.visitante=false;
            this.Trocar.setVisible(false);
        }
        this.jogo=jogo;
        initComponents();
        this.CadastrarJo.setVisible(false);
        if(visitante){ this.Editar.setVisible(false);}

        //dentro da classe jogo
        this.jTextFieldNome.setText(jogo.getNome());
        this.jTextFieldProdutora.setText(jogo.o1.getProdutora());
        this.jTextFieldNJogadores.setText(jogo.getQntJogadores());
        this.jTextFieldCensura.setText(jogo.o1.getCensura());
        this.jTextFieldSinopse.setText(jogo.o1.getSinopse());
        this.jComboBoxPlataforma.setSelectedItem(jogo.getPlataforma().toString());
        this.jComboBoxGenero.setSelectedItem(jogo.o1.getGenero().toString());
        this.jComboBoxIdioma.setSelectedItem(jogo.o1.getIdioma().toString());
        //dentro da classe item
        if(jogo.getFoto()!=null){ 
        jLabelFoto.setSize(220,191);
        jLabelFoto.setIcon(new ImageIcon(jogo.getFoto().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT)));}
        this.jTextFieldEdicao.setText(jogo.getEdicao());
        this.jComboBoxEstado.setSelectedItem(jogo.getEstadoPreservacao());
        this.jTextFieldDescricao.setText(jogo.getDescricao());
        this.jTextFieldFabricacao.setText(jogo.getFabricacao());
        this.jTextFieldAquisicao.setText(jogo.getAquisicao());
        this.jTextFieldVFabricacao1.setText(jogo.getVFabricacao());        
        this.jTextFieldVAquisicao1.setText(jogo.getVAquisicao());    
         this.jComboBoxPrivacidade.setSelectedIndex(jogo.getPrivacidade());
        //desativa edicao
        //dentro da classe jogo
        this.jComboBoxPrivacidade.setEnabled(false);
        this.jTextFieldNome.setEditable(false);
        this.jTextFieldProdutora.setEditable(false);
        this.jTextFieldNJogadores.setEditable(false);
        this.jTextFieldCensura.setEditable(false);
        this.jTextFieldSinopse.setEditable(false);
        this.jComboBoxPlataforma.setEnabled(false);
        this.jComboBoxGenero.setEnabled(false);
        this.jComboBoxIdioma.setEnabled(false);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(false);
        this.jComboBoxEstado.setEnabled(false);
        this.jTextFieldDescricao.setEditable(false);
        this.jTextFieldFabricacao.setEditable(false);
        this.jTextFieldAquisicao.setEditable(false);
        this.jTextFieldVFabricacao1.setEditable(false);
        this.jTextFieldVAquisicao1.setEditable(false);
        this.Salvar.setVisible(false);//oculta o botão salvar
         if(idUserLogando==jogo.getIdUsuario()){ this.Trocar.setVisible(false); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTroca = new javax.swing.JPanel();
        solicitarTroca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbListarJogo = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProdutora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNJogadores = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxPlataforma = new javax.swing.JComboBox();
        jComboBoxIdioma = new javax.swing.JComboBox();
        jTextFieldCensura = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldEdicao = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldAquisicao = new javax.swing.JFormattedTextField();
        jTextFieldFabricacao = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldDescricao = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldVFabricacao1 = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldVAquisicao1 = new javax.swing.JFormattedTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldSinopse = new javax.swing.JTextArea();
        jComboBoxPrivacidade = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        Trocar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Salvar = new javax.swing.JLabel();
        CadastrarJo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanelTroca.setBackground(new java.awt.Color(255, 255, 255));

        solicitarTroca.setBackground(new java.awt.Color(21, 30, 51));
        solicitarTroca.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        solicitarTroca.setForeground(java.awt.SystemColor.control);
        solicitarTroca.setText("Solicitar Troca");
        solicitarTroca.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        solicitarTroca.setContentAreaFilled(false);
        solicitarTroca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitarTroca.setOpaque(true);
        solicitarTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseExited(evt);
            }
        });
        solicitarTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarTrocaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha um item seu para oferecer na troca");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 3));

        jtbListarJogo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtbListarJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Plataforma"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbListarJogo.setMaximumSize(new java.awt.Dimension(225, 0));
        jScrollPane3.setViewportView(jtbListarJogo);

        javax.swing.GroupLayout jPanelTrocaLayout = new javax.swing.GroupLayout(jPanelTroca);
        jPanelTroca.setLayout(jPanelTrocaLayout);
        jPanelTrocaLayout.setHorizontalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(solicitarTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(136, 136, 136))
        );
        jPanelTrocaLayout.setVerticalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solicitarTroca)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 5));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nome");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Plataforma");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Produtora");

        jTextFieldProdutora.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldProdutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoraActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Objetivo(s)");

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Idioma");

        jComboBoxGenero.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxGenero.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ação", "Aventura", "Estratégia", "RPG", "Tabuleiro Eletrônico", "MMO", "Simulação", "Corrida", "Esportes", "Quebra-Cabeça" }));
        jComboBoxGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Gênero");

        jTextFieldNome.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Nº de jogadores");

        jTextFieldNJogadores.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNJogadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNJogadoresActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Capa do jogo");

        jComboBoxPlataforma.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPlataforma.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPlataforma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Arcade", "Pc", "Xbox one", "Xbox 360", "Ps4", "Ps3", "Ps2", "Super nintendo", "Nintendo wii", "Nintendo 3DS", "Mega drive", "Atari", "Psp", "Game cube" }));
        jComboBoxPlataforma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jComboBoxIdioma.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxIdioma.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inglês", "Chinês Mandarim", "Espanhol", "Português", "Russo", "Francês", "Alemão", "Japonês", "Italiano", "Tailandês", "Polonês" }));
        jComboBoxIdioma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTextFieldCensura.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldCensura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCensuraActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Classificação indicativa");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Data de fabricação");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Data de aquisição");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Valor (Aquisição)");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Valor (Fabricação)");

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Edição");

        jTextFieldEdicao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdicaoActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Estado de preservação");

        jComboBoxEstado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Usado", "Precário" }));
        jComboBoxEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Descrição");

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enari - imagem(item).png"))); // NOI18N
        jLabelFoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51)));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
        });

        try {
            jTextFieldAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldAquisicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAquisicao.setSelectionColor(new java.awt.Color(21, 30, 51));

        try {
            jTextFieldFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFabricacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFabricacao.setSelectionColor(new java.awt.Color(21, 30, 51));

        jTextFieldDescricao.setColumns(20);
        jTextFieldDescricao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextFieldDescricao.setLineWrap(true);
        jTextFieldDescricao.setRows(3);
        jTextFieldDescricao.setWrapStyleWord(true);
        jTextFieldDescricao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jScrollPane1.setViewportView(jTextFieldDescricao);

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("R$");

        jTextFieldVFabricacao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVFabricacao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVFabricacao1.setSelectionColor(new java.awt.Color(21, 30, 51));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("R$");

        jTextFieldVAquisicao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVAquisicao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVAquisicao1.setSelectionColor(new java.awt.Color(21, 30, 51));

        jTextFieldSinopse.setColumns(20);
        jTextFieldSinopse.setLineWrap(true);
        jTextFieldSinopse.setRows(3);
        jTextFieldSinopse.setSelectionColor(new java.awt.Color(21, 30, 51));
        jScrollPane2.setViewportView(jTextFieldSinopse);

        jComboBoxPrivacidade.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPrivacidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPrivacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Amigos", "Privado" }));
        jComboBoxPrivacidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxPrivacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrivacidadeActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Privacidade");

        Voltar.setBackground(new java.awt.Color(21, 30, 51));
        Voltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voltar.setText("Cadastrados");
        Voltar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.setOpaque(true);
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });

        Trocar.setBackground(new java.awt.Color(21, 30, 51));
        Trocar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Trocar.setForeground(new java.awt.Color(255, 255, 255));
        Trocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trocar.setText("Trocar");
        Trocar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Trocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trocar.setOpaque(true);
        Trocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrocarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrocarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrocarMouseExited(evt);
            }
        });

        Editar.setBackground(new java.awt.Color(21, 30, 51));
        Editar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("Editar");
        Editar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.setOpaque(true);
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });

        Salvar.setBackground(new java.awt.Color(21, 30, 51));
        Salvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salvar.setText("Salvar");
        Salvar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salvar.setOpaque(true);
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalvarMouseExited(evt);
            }
        });

        CadastrarJo.setBackground(new java.awt.Color(21, 30, 51));
        CadastrarJo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CadastrarJo.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarJo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastrarJo.setText("Cadastrar jogo");
        CadastrarJo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        CadastrarJo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarJo.setOpaque(true);
        CadastrarJo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarJoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarJoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarJoMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 30, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Jogo");

        jSeparator1.setBackground(new java.awt.Color(21, 30, 51));
        jSeparator1.setForeground(new java.awt.Color(21, 30, 51));
        jSeparator1.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Trocar, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CadastrarJo, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                        .addGap(277, 277, 277)
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jTextFieldProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(4, 4, 4)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel8Layout.createSequentialGroup()
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldNJogadores))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jTextFieldCensura))))
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jComboBoxPrivacidade, javax.swing.GroupLayout.Alignment.LEADING, 0, 211, Short.MAX_VALUE)
                                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jTextFieldEdicao)
                                    .addComponent(jComboBoxPlataforma, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jComboBoxEstado, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jTextFieldFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(7, 7, 7)
                                        .addComponent(jTextFieldAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel19))
                                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel8Layout.createSequentialGroup()
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                    .addComponent(jLabel26)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldVFabricacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGroup(jPanel8Layout.createSequentialGroup()
                                                    .addComponent(jLabel25)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(jTextFieldVAquisicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))))))))))
                .addGap(22, 22, 22))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxPrivacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldProdutora, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVFabricacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVAquisicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jTextFieldNJogadores, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCensura, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jTextFieldEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(2, 2, 2)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxGenero, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarJo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Trocar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8, "card2");

        getContentPane().add(jPanel7, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProdutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoraActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldNJogadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNJogadoresActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jTextFieldNJogadoresActionPerformed

    private void jTextFieldCensuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCensuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCensuraActionPerformed

    private void jTextFieldEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdicaoActionPerformed

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        String caminho;
        JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
        File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
        arquivo.setCurrentDirectory(diretorio);
        arquivo.showOpenDialog(null);
         jLabelFoto.setSize(220,191);
        caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
        img = new ImageIcon(caminho).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT);//NOVO COD PARA DEFINIR TAMANHO UNICO DE IMAGENS
        jLabelFoto.setIcon(new ImageIcon(img)); //LBIMAGEM RECEBERA A IMAGEM        // TODO add your handling code here:
        if(visitante==true){} else {
            jogo.setFoto(img.getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT));
        }
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void jComboBoxPrivacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrivacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPrivacidadeActionPerformed

    private void solicitarTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarTrocaActionPerformed
        if (jtbListarJogo.getSelectedRow() == -1) {JOptionPane.showMessageDialog(this, "Nenhuma camiseta selecionada.");}
        Integer idJogo = (Integer) jtbListarJogo.getValueAt(jtbListarJogo.getSelectedRow(), 0);
        Troca troca=new Troca(idUserLogando,jogo.getIdUsuario(),3,(Item)Dados.getJogosBD().get(idJogo),(Item)jogo);
        solicitarTroca.setText("Troca solicitada !");
        solicitarTroca.setEnabled(false);
        solicitarTroca.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_solicitarTrocaActionPerformed

    private void CadastrarJoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarJoMouseClicked
        addJogo();
    }//GEN-LAST:event_CadastrarJoMouseClicked

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
        Jogo novoJogo=jogo;
        //dentro da classe jogo
        novoJogo.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        novoJogo.setNome(this.jTextFieldNome.getText());
        novoJogo.o1.setProdutora(this.jTextFieldProdutora.getText());
        novoJogo.setQntJogadores(this.jTextFieldNJogadores.getText());
        novoJogo.o1.setCensura(this.jTextFieldCensura.getText());
        novoJogo.o1.setSinopse(this.jTextFieldSinopse.getText());
        novoJogo.setPlataforma(this.jComboBoxPlataforma.getSelectedItem().toString());
        novoJogo.o1.setGenero(this.jComboBoxGenero.getSelectedItem().toString());
        novoJogo.o1.setIdioma(this.jComboBoxIdioma.getSelectedItem().toString());
        //dentro da classe item
        novoJogo.setEdicao(this.jTextFieldEdicao.getText());
        novoJogo.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        novoJogo.setDescricao(this.jTextFieldDescricao.getText());
        novoJogo.setFabricacao(this.jTextFieldFabricacao.getText());
        novoJogo.setAquisicao(this.jTextFieldAquisicao.getText());
        novoJogo.setVFabricacao(jTextFieldVFabricacao1.getText());
        novoJogo.setVAquisicao(jTextFieldVAquisicao1.getText());
        novoJogo.setFoto(img);
       
        Dados.getJogosBD().get(atividadeEditar.getIdItem()).equals(novoJogo);
        atividadeEditar.lstItem.add(novoJogo);
        atividadeEditar.bloquearAtividades(idUserLogando);
        JIFrameListarJogo jIFrameListarJogo = new JIFrameListarJogo(idUserLogando);
        jIFrameListarJogo.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarJogo);
        jIFrameListarJogo.setVisible(true);
        try {jIFrameListarJogo.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_SalvarMouseClicked

    private void TrocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseClicked
        listarJogo();
        JOptionPane.showMessageDialog(null,jPanelTroca);
    }//GEN-LAST:event_TrocarMouseClicked

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        atividadeEditar=new Atividade(jogo.getIdItem(),3, idUserLogando, 3, "Editou","JOGO");
        atividadeEditar.add((Item) Dados.getJogosBD().get(atividadeEditar.getIdItem()).clone());
        atividadeEditar.salvar();
        this.Salvar.setVisible(true);//oculta o botão salvar
        //habilita a edicao dos campos
        this.jTextFieldNome.setEditable(true);
        this.jTextFieldProdutora.setEditable(true);
        this.jTextFieldNJogadores.setEditable(true);
        this.jTextFieldCensura.setEditable(true);
        this.jTextFieldSinopse.setEditable(true);
        this.jComboBoxPlataforma.setEnabled(true);
        this.jComboBoxGenero.setEnabled(true);
        this.jComboBoxIdioma.setEnabled(true);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(true);
        this.jComboBoxEstado.setEnabled(true);
        this.jTextFieldDescricao.setEditable(true);
        this.jTextFieldFabricacao.setEditable(true);
        this.jTextFieldAquisicao.setEditable(true);
        this.jTextFieldVFabricacao1.setEditable(true);
        this.jTextFieldVAquisicao1.setEditable(true);
        this.jComboBoxPrivacidade.setEnabled(true);
    }//GEN-LAST:event_EditarMouseClicked

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
       JIFrameListarJogo jIFrameListarJogo = new JIFrameListarJogo(idUserLogando);
        jIFrameListarJogo.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarJogo);
        jIFrameListarJogo.setVisible(true);
        try {jIFrameListarJogo.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_VoltarMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        Voltar.setOpaque(true);
        Voltar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        Color padrao=new Color(21,30,51);
        Voltar.setBackground(padrao);
    }//GEN-LAST:event_VoltarMouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setOpaque(true);
        Editar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Color padrao=new Color(21,30,51);
        Editar.setBackground(padrao);
    }//GEN-LAST:event_EditarMouseExited

    private void TrocarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseEntered
        Trocar.setOpaque(true);
        Trocar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_TrocarMouseEntered

    private void TrocarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseExited
        Color padrao=new Color(21,30,51);
        Trocar.setBackground(padrao);
    }//GEN-LAST:event_TrocarMouseExited

    private void SalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseEntered
        Salvar.setOpaque(true);
        Salvar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_SalvarMouseEntered

    private void SalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseExited
        Color padrao=new Color(21,30,51);
        Salvar.setBackground(padrao);
    }//GEN-LAST:event_SalvarMouseExited

    private void CadastrarJoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarJoMouseEntered
        CadastrarJo.setOpaque(true);
        CadastrarJo.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_CadastrarJoMouseEntered

    private void CadastrarJoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarJoMouseExited
        Color padrao=new Color(21,30,51);
        CadastrarJo.setBackground(padrao);
    }//GEN-LAST:event_CadastrarJoMouseExited

    private void solicitarTrocaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseEntered
        if(solicitarTroca.isEnabled()==true){
        solicitarTroca.setOpaque(true);
        solicitarTroca.setBackground(Color.DARK_GRAY); 
        }
    }//GEN-LAST:event_solicitarTrocaMouseEntered

    private void solicitarTrocaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseExited
        Color padrao=new Color(21,30,51);
        solicitarTroca.setBackground(padrao);
    }//GEN-LAST:event_solicitarTrocaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarJo;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Salvar;
    private javax.swing.JLabel Trocar;
    private javax.swing.JLabel Voltar;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JComboBox jComboBoxIdioma;
    private javax.swing.JComboBox jComboBoxPlataforma;
    private javax.swing.JComboBox jComboBoxPrivacidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelTroca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jTextFieldAquisicao;
    private javax.swing.JTextField jTextFieldCensura;
    private javax.swing.JTextArea jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JFormattedTextField jTextFieldFabricacao;
    private javax.swing.JTextField jTextFieldNJogadores;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldProdutora;
    private javax.swing.JTextArea jTextFieldSinopse;
    private javax.swing.JFormattedTextField jTextFieldVAquisicao1;
    private javax.swing.JFormattedTextField jTextFieldVFabricacao1;
    private javax.swing.JTable jtbListarJogo;
    private javax.swing.JButton solicitarTroca;
    // End of variables declaration//GEN-END:variables
public void addJogo(){
        String NOME = jTextFieldNome.getText();
        Jogo JOGO = new Jogo();
        boolean existeJogo=false;
        for (int i = 0; i < Dados.getJogosBD().size(); i++) {//percorre a lista de usuarios "lst"
                JOGO = Dados.getJogosBD().get(i);//paga o objeto da posição "i" e armazena no objeto "usuario" do tipo "Usuario"
            if (NOME.equals(JOGO.getNome())){jLabel8.setText("Jogo já cadastrado");
            existeJogo=true;
            break;}
        }
            if(!existeJogo){
        jogo.setIdUsuario(idUserLogando);
        //dentro da classe jogo
        jogo.setNome(this.jTextFieldNome.getText());
        jogo.o1.setGenero(this.jComboBoxGenero.getSelectedItem().toString());
        jogo.setQntJogadores(this.jTextFieldNJogadores.getText());
        jogo.setPlataforma(this.jComboBoxPlataforma.getSelectedItem().toString());
        jogo.o1.setCensura(this.jTextFieldCensura.getText());
        jogo.o1.setProdutora(this.jTextFieldProdutora.getText());
        jogo.o1.setSinopse(this.jTextFieldSinopse.getText());
        jogo.o1.setIdioma(this.jComboBoxIdioma.getSelectedItem().toString());        
        //dentro da classe item
        jogo.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        jogo.setFabricacao(this.jTextFieldFabricacao.getText());
        jogo.setAquisicao(this.jTextFieldAquisicao.getText());
        jogo.setEdicao(this.jTextFieldEdicao.getText());
        jogo.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        jogo.setDescricao(this.jTextFieldDescricao.getText());
        jogo.setVFabricacao(jTextFieldVFabricacao1.getText());        
        jogo.setVAquisicao(jTextFieldVAquisicao1.getText());
        jogo.salvar();
        //Atividade de adição do jogo
        
        int idCarta=(int) (Math.random() * Cartas.getJogos().size()-1);
        if(idCarta<0){idCarta=0;}
        Dados.getUsuariosBD().get(idUserLogando).setCartaJogo(idCarta);
        
        
        
        atividade=new Atividade(jogo.getIdItem(),3, idUserLogando, 1, "Adicionou","JOGO");
        atividade.salvar();
        atividade.bloquearAtividades(idUserLogando);
        JIFrameListarJogo jIFrameListarJogo = new JIFrameListarJogo(idUserLogando);
        jIFrameListarJogo.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarJogo);
        jIFrameListarJogo.setVisible(true);
        try {jIFrameListarJogo.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
        this.doDefaultCloseAction();//fim atual
        Principal.atualizaInicial();
        }
        }
 private void listarJogo() {
        DefaultTableModel dtm = (DefaultTableModel) jtbListarJogo.getModel();
        dtm.setNumRows(0);
        
        for (Jogo jogoDaLista: Dados.getUsuariosBD().get(idUserLogando).getColecaoJogo()) {
            dtm.addRow(new Object[]{jogoDaLista.getIdItem(),jogoDaLista.getNome(),
                jogoDaLista.getPlataforma()});
        }
    }
    }
