/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaColecionadores;

import static ProgramaColecionadores.Principal.idUserLog;
import java.awt.Color;
import java.awt.Font;
import java.beans.PropertyVetoException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.BorderFactory;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.border.BevelBorder.RAISED;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Casa
 */
public class JIFrameUsuariosRede extends javax.swing.JInternalFrame {
       private final int idUserLogando;
       private List<Atividade> lstMinhasAtividades;
       private int idAtividade;
       int p;
       int posicaoAtividadeRede;
       Integer idUsuario;
       private Usuario usuario;
    /**
     * Creates new form JIFrameUsuariosRede
     * @param idUserLogando
     */
    public JIFrameUsuariosRede(int idUserLogando) {
        this.isMaximum=true;
        this.idUserLogando=idUserLogando;
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas 
        this.jButtonSolicitacao.setText("["+Integer.toString(Dados.getSolicitacaoAmizade(idUserLogando).size())+"]");
        if(Dados.getSolicitacaoAmizade(idUserLogando).size()>0){
        jButtonSolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolicitacao.setOpaque(true);
        Color padrao=new Color(153,0,0);
        jButtonSolicitacao.setBackground(padrao);
            }else{
            jButtonSolicitacao.setOpaque(false);
            jButtonSolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        this.jButtonMensagem.setText("["+Integer.toString(Dados.getMensagensBD().size())+"]");
        this.lstMinhasAtividades=new ArrayList();
        
        for (Atividade atividade : Dados.getAtividadesBD()) {//percorre lista de atividades
               if(atividade.getIdUsuario()==idUserLogando){//verifica se a atividade possui o id do usuário logado
               lstMinhasAtividades.add(atividade);//adiciona a atividade na lista de atividades especificas do usuario
               }
        }
        JIFramePerfil jIFramePefil = new JIFramePerfil(idUserLogando);
        jIFramePefil.idUserLogando=Principal.getIdUserLogando();
        jDesktopPane.add(jIFramePefil);
        jIFramePefil.setVisible(true);
        try {jIFramePefil.setMaximum(true);} 
        catch (PropertyVetoException ex) {  }
        
    }
    
    public JIFrameUsuariosRede() {
        this.isMaximum=true;
        this.idUserLogando=Principal.getIdUserLogando();
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas 
        this.jButtonSolicitacao.setText("["+Integer.toString(Dados.getSolicitacaoAmizade(idUserLogando).size())+"]");
        if(Dados.getSolicitacaoAmizade(idUserLogando).size()>0){
        jButtonSolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolicitacao.setOpaque(true);
        Color padrao=new Color(153,0,0);
        jButtonSolicitacao.setBackground(padrao);
            }else{
            jButtonSolicitacao.setOpaque(false);
            jButtonSolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            }
        this.jButtonMensagem.setText("["+Integer.toString(Dados.getMensagensBD().size())+"]");
        this.lstMinhasAtividades=new ArrayList();
        
        for (Atividade atividade : Dados.getAtividadesBD()) {//percorre lista de atividades
               if(atividade.getIdUsuario()==idUserLogando){//verifica se a atividade possui o id do usuário logado
               lstMinhasAtividades.add(atividade);//adiciona a atividade na lista de atividades especificas do usuario
               }
        }
        JIFrameHome jIFramePefil = new JIFrameHome(idUserLogando);
        jDesktopPane.add(jIFramePefil);
        jIFramePefil.setVisible(true);
        try {jIFramePefil.setMaximum(true);} 
        catch (PropertyVetoException ex) {  }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMensagem = new javax.swing.JPanel();
        jScrollPaneRecado = new javax.swing.JScrollPane();
        jTextAreaRecado = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        MenuInferior = new javax.swing.JPanel();
        jButtonUndo = new javax.swing.JButton();
        jButtonUndo1 = new javax.swing.JButton();
        jButtonaAmigos = new javax.swing.JButton();
        jButtonMeuPerfil = new javax.swing.JButton();
        jButtonaRede = new javax.swing.JButton();
        jButtonSolicitacao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonMensagem = new javax.swing.JButton();
        jButtonInicio = new javax.swing.JButton();
        jDesktopPane = new javax.swing.JDesktopPane();

        jPanelMensagem.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPaneRecado.setBorder(null);

        jTextAreaRecado.setColumns(20);
        jTextAreaRecado.setLineWrap(true);
        jTextAreaRecado.setRows(3);
        jTextAreaRecado.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jTextAreaRecado.setSelectionColor(new java.awt.Color(21, 30, 51));
        jScrollPaneRecado.setViewportView(jTextAreaRecado);

        jButton1.setBackground(new java.awt.Color(21, 30, 51));
        jButton1.setFont(new java.awt.Font("Verdana", 1, 10)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Enviar Recado");
        jButton1.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setOpaque(true);
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton1MouseExited(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelMensagemLayout = new javax.swing.GroupLayout(jPanelMensagem);
        jPanelMensagem.setLayout(jPanelMensagemLayout);
        jPanelMensagemLayout.setHorizontalGroup(
            jPanelMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensagemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPaneRecado, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelMensagemLayout.setVerticalGroup(
            jPanelMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMensagemLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMensagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneRecado, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(245, 245, 245));

        MenuInferior.setBackground(new java.awt.Color(21, 30, 51));
        MenuInferior.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(255, 255, 0)));
        MenuInferior.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        MenuInferior.setMaximumSize(new java.awt.Dimension(0, 30));
        MenuInferior.setMinimumSize(new java.awt.Dimension(0, 30));

        jButtonUndo.setBackground(new java.awt.Color(21, 30, 51));
        jButtonUndo.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jButtonUndo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/undo.png"))); // NOI18N
        jButtonUndo.setToolTipText("Desfazer");
        jButtonUndo.setBorder(null);
        jButtonUndo.setBorderPainted(false);
        jButtonUndo.setContentAreaFilled(false);
        jButtonUndo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUndo.setFocusPainted(false);
        jButtonUndo.setMaximumSize(new java.awt.Dimension(85, 50));
        jButtonUndo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUndoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUndoMouseExited(evt);
            }
        });
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });
        jButtonUndo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonUndoFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonUndoFocusLost(evt);
            }
        });

        jButtonUndo1.setBackground(new java.awt.Color(21, 30, 51));
        jButtonUndo1.setFont(new java.awt.Font("Vrinda", 0, 18)); // NOI18N
        jButtonUndo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Redo.png"))); // NOI18N
        jButtonUndo1.setToolTipText("Refazer");
        jButtonUndo1.setBorder(null);
        jButtonUndo1.setBorderPainted(false);
        jButtonUndo1.setContentAreaFilled(false);
        jButtonUndo1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonUndo1.setFocusPainted(false);
        jButtonUndo1.setMaximumSize(new java.awt.Dimension(85, 50));
        jButtonUndo1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonUndo1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonUndo1MouseExited(evt);
            }
        });
        jButtonUndo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndo1ActionPerformed(evt);
            }
        });
        jButtonUndo1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jButtonUndo1FocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jButtonUndo1FocusLost(evt);
            }
        });

        jButtonaAmigos.setBackground(new java.awt.Color(21, 30, 51));
        jButtonaAmigos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonaAmigos.setForeground(new java.awt.Color(255, 255, 255));
        jButtonaAmigos.setText("AMIGOS");
        jButtonaAmigos.setToolTipText("Atualizações de amigos");
        jButtonaAmigos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonaAmigos.setContentAreaFilled(false);
        jButtonaAmigos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonaAmigos.setFocusPainted(false);
        jButtonaAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonaAmigosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonaAmigosMouseExited(evt);
            }
        });
        jButtonaAmigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaAmigosActionPerformed(evt);
            }
        });

        jButtonMeuPerfil.setBackground(new java.awt.Color(21, 30, 51));
        jButtonMeuPerfil.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonMeuPerfil.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMeuPerfil.setText("MEU PERFIL");
        jButtonMeuPerfil.setToolTipText("Atualizações do usuário");
        jButtonMeuPerfil.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonMeuPerfil.setContentAreaFilled(false);
        jButtonMeuPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMeuPerfil.setFocusPainted(false);
        jButtonMeuPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMeuPerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMeuPerfilMouseExited(evt);
            }
        });
        jButtonMeuPerfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMeuPerfilActionPerformed(evt);
            }
        });

        jButtonaRede.setBackground(new java.awt.Color(21, 30, 51));
        jButtonaRede.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonaRede.setForeground(new java.awt.Color(255, 255, 255));
        jButtonaRede.setText("REDE");
        jButtonaRede.setToolTipText("Atualizações da rede");
        jButtonaRede.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonaRede.setContentAreaFilled(false);
        jButtonaRede.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonaRede.setFocusPainted(false);
        jButtonaRede.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonaRedeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonaRedeMouseExited(evt);
            }
        });
        jButtonaRede.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaRedeActionPerformed(evt);
            }
        });

        jButtonSolicitacao.setBackground(new java.awt.Color(21, 30, 51));
        jButtonSolicitacao.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonSolicitacao.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSolicitacao.setBorder(null);
        jButtonSolicitacao.setContentAreaFilled(false);
        jButtonSolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolicitacao.setFocusPainted(false);
        jButtonSolicitacao.setPreferredSize(new java.awt.Dimension(125, 31));
        jButtonSolicitacao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonSolicitacaoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonSolicitacaoMouseExited(evt);
            }
        });
        jButtonSolicitacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSolicitacaoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" Solicitações:");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText(" Mensagens:");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jButtonMensagem.setBackground(new java.awt.Color(153, 0, 0));
        jButtonMensagem.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonMensagem.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMensagem.setBorder(null);
        jButtonMensagem.setContentAreaFilled(false);
        jButtonMensagem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonMensagem.setFocusPainted(false);
        jButtonMensagem.setPreferredSize(new java.awt.Dimension(125, 31));
        jButtonMensagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonMensagemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonMensagemMouseExited(evt);
            }
        });
        jButtonMensagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMensagemActionPerformed(evt);
            }
        });

        jButtonInicio.setBackground(new java.awt.Color(21, 30, 51));
        jButtonInicio.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonInicio.setForeground(new java.awt.Color(255, 255, 255));
        jButtonInicio.setText("INÍCIO");
        jButtonInicio.setToolTipText("Atualizações do usuário");
        jButtonInicio.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonInicio.setContentAreaFilled(false);
        jButtonInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonInicio.setFocusPainted(false);
        jButtonInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonInicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonInicioMouseExited(evt);
            }
        });
        jButtonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuInferiorLayout = new javax.swing.GroupLayout(MenuInferior);
        MenuInferior.setLayout(MenuInferiorLayout);
        MenuInferiorLayout.setHorizontalGroup(
            MenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuInferiorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jButtonaAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonaRede, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonSolicitacao, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonUndo1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MenuInferiorLayout.setVerticalGroup(
            MenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuInferiorLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(MenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButtonMensagem, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(MenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonMeuPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuInferiorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonaAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonaRede, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButtonInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonSolicitacao, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(jButtonUndo, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
            .addComponent(jButtonUndo1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.getAccessibleContext().setAccessibleParent(jButtonSolicitacao);

        jDesktopPane.setBackground(new java.awt.Color(245, 245, 245));

        javax.swing.GroupLayout jDesktopPaneLayout = new javax.swing.GroupLayout(jDesktopPane);
        jDesktopPane.setLayout(jDesktopPaneLayout);
        jDesktopPaneLayout.setHorizontalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jDesktopPaneLayout.setVerticalGroup(
            jDesktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 192, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuInferior, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jDesktopPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuInferior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jDesktopPane))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonUndoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonUndoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndoFocusGained

    private void jButtonUndoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonUndoFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndoFocusLost

    private void jButtonUndoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUndoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndoMouseEntered

    private void jButtonUndoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUndoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndoMouseExited

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
        for (Atividade atividade : Dados.getAtividadesBD()) {//percorre lista de atividades
            if(atividade.getIdUsuario()==idUserLogando){//verifica se a atividade possui o id do usuário logado
                lstMinhasAtividades.add(atividade);//adiciona a atividade na lista de atividades especificas do usuario
            }
        }
        for (int i=lstMinhasAtividades.size()-1; i >= 0 ; i--) {//percorre lista de atividades
            Atividade atividade=lstMinhasAtividades.get(i);//carrega objeto atividade
            if(
                (atividade.getIdTipoAtividade()!=0
                    ||atividade.getIdTipoAtividade()==51
                    ||atividade.getIdTipoAtividade()==52
                    ||atividade.getIdTipoAtividade()==53)
                && atividade.getIdStatus()==0)
            {//verifica se é de tipo que pode ser desfeito
                idAtividade=atividade.getIdAtividade();//define o id da atividade que será desfeita
                break;
            }

        }
        Atividade atividade=Dados.getAtividadesBD().get(idAtividade);//carraga objeto da atividade
        if((atividade.getIdTipoAtividade()!=0 && atividade.getIdStatus()==0) ||
            (atividade.getIdTipoAtividade()==51 && atividade.getIdStatus()==0)||
            (atividade.getIdTipoAtividade()==52 && atividade.getIdStatus()==0)||
            (atividade.getIdTipoAtividade()==53 && atividade.getIdStatus()==0)){//verifica se a atividade é de tipo que pode ser desfeita
            if(atividade.getIdTipoAtividade()==1 || atividade.getIdTipoAtividade()==51 ){//verifica se a atividade é uma adicao de item
                atividade.undoAdicaoItem();
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdTipoAtividade(6);  ///atividade bloqueada
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdStatus(1);//atividade refeita

            }
            if(atividade.getIdTipoAtividade()==3 || atividade.getIdTipoAtividade()==53 ){//verifica se atividade é uma exclusao
                atividade.undoAlteracaoItem();
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdTipoAtividade(6);  ///atividade desfeita
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdStatus(1);//atividade refeita

            }
            if(atividade.getIdTipoAtividade()==2 || atividade.getIdTipoAtividade()==52){//verifica se a atividade é uma edicao de item
                atividade.undoExclusaoItem();
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdTipoAtividade(6);  ///atividade desfeita
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdStatus(1);//atividade refeita

            }
        }else{
            JOptionPane.showMessageDialog(null, "Não há atividade para ser desfeita");
        }
         Principal.getjDPPrincipal().removeAll();
        //Repaint - faz a atualização do conteúdo(componentes) de dentro do DesktopFrame
        Principal.getjDPPrincipal().repaint();
           //JIFramePerfil recebendo o ID de usuario logando
           JIFrameUsuariosRede jIFramePefil = new JIFrameUsuariosRede();
        //Add adicionando JIFramePerfil que foi criado ao JDesktioFrame(jDPPrincipal)          
        Principal.getjDPPrincipal().add(jIFramePefil);       
        //tornando frame Perfil visivel ao usuario
        jIFramePefil.setVisible(true);
        //setMaximum para adaptar internalFrame/componentes do frame atividades ao DesktopFrame em dimensões(tamanho).
        try {jIFramePefil.setMaximum(true);} 
        catch (PropertyVetoException ex) {  }
       
    }//GEN-LAST:event_jButtonUndoActionPerformed

    private void jButtonUndo1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonUndo1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndo1FocusGained

    private void jButtonUndo1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jButtonUndo1FocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndo1FocusLost

    private void jButtonUndo1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUndo1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndo1MouseEntered

    private void jButtonUndo1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonUndo1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonUndo1MouseExited

    private void jButtonUndo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndo1ActionPerformed
        for (Atividade atividade : Dados.getAtividadesBD()) {//percorre lista de atividades
            if(atividade.getIdUsuario()==idUserLogando){//verifica se a atividade possui o id do usuário logado
                lstMinhasAtividades.add(atividade);//adiciona a atividade na lista de atividades especificas do usuario
            }
        }
        for (int i=0; i<lstMinhasAtividades.size();i++) {//percorre lista de atividades
            Atividade atividade=lstMinhasAtividades.get(i);//carrega objeto atividade
            if((atividade.getIdTipoAtividade()==41 ||
                atividade.getIdTipoAtividade()==42 ||
                atividade.getIdTipoAtividade()==43)&& atividade.getIdStatus()==1){//verifica se é de tipo que pode ser desfeito
            idAtividade=atividade.getIdAtividade();//define o id da atividade que será desfeita
            break;
        }
        }
        Atividade atividade=Dados.getAtividadesBD().get(idAtividade);//carraga objeto da atividade
        if(
            (atividade.getIdTipoAtividade()==41 ||
                atividade.getIdTipoAtividade()==42 ||
                atividade.getIdTipoAtividade()==43)
            && atividade.getIdStatus()==1)
        {//verifica se a atividade é de tipo que pode ser desfeita
            if(atividade.getIdTipoAtividade()==41){//verifica se a atividade é uma adicao de item
                atividade.redoAdicaoItem();
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdTipoAtividade(6);  ///atividade refeita
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdStatus(0);//atividade refeita

            }
            if(atividade.getIdTipoAtividade()==43){//verifica se atividade é uma a
                atividade.redoAlteracaoItem();
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdTipoAtividade(6);//atividade refeita
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdStatus(0);//atividade refeita

            }
            if(atividade.getIdTipoAtividade()==42){//verifica se a atividade é uma exclusao de item
                atividade.redoExclusaoItem();
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdStatus(0);//atividade refeita
                Dados.getAtividadesBD().get(atividade.getIdAtividade()).setIdStatus(0);//atividade refeita

            }
             Principal.getjDPPrincipal().removeAll();
        //Repaint - faz a atualização do conteúdo(componentes) de dentro do DesktopFrame
        Principal.getjDPPrincipal().repaint();
           //JIFramePerfil recebendo o ID de usuario logando
           JIFrameUsuariosRede jIFramePefil = new JIFrameUsuariosRede();
        //Add adicionando JIFramePerfil que foi criado ao JDesktioFrame(jDPPrincipal)          
        Principal.getjDPPrincipal().add(jIFramePefil);       
        //tornando frame Perfil visivel ao usuario
        jIFramePefil.setVisible(true);
        //setMaximum para adaptar internalFrame/componentes do frame atividades ao DesktopFrame em dimensões(tamanho).
        try {jIFramePefil.setMaximum(true);} 
        catch (PropertyVetoException ex) {  }
       
        }else{
            JOptionPane.showMessageDialog(null, "Não há atividade para ser refeita");
        }
        
    }//GEN-LAST:event_jButtonUndo1ActionPerformed

    private void jButtonaAmigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaAmigosActionPerformed
        for(Usuario e:Dados.getAmigos(Principal.getIdUserLogando())){
               System.out.println(e.getIdUsuario()+e.getNome());
        }
        jDesktopPane.removeAll();
        jDesktopPane.repaint();
        JIFrameListarUsuarios jIFrameListarUsuarios = new JIFrameListarUsuarios(idUserLogando);
        jDesktopPane.add(jIFrameListarUsuarios);
        jIFrameListarUsuarios.setVisible(true);
        try {jIFrameListarUsuarios.setMaximum(true);}
        catch (PropertyVetoException ex) {  }
    }//GEN-LAST:event_jButtonaAmigosActionPerformed

    private void jButtonMeuPerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMeuPerfilActionPerformed
        jDesktopPane.removeAll();
        jDesktopPane.repaint(); 
        JIFramePerfil jIFramePefil = new JIFramePerfil(Principal.getIdUserLogando());
        jIFramePefil.idUserLogando=Principal.getIdUserLogando();
        jDesktopPane.add(jIFramePefil);
        jIFramePefil.setVisible(true);
        try {jIFramePefil.setMaximum(true);} 
        catch (PropertyVetoException ex) {  }
    }//GEN-LAST:event_jButtonMeuPerfilActionPerformed

    private void jButtonaRedeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaRedeActionPerformed
        jDesktopPane.removeAll();
        jDesktopPane.repaint();
        JIFrameListarUsuarios jIFrameListarUsuarios = new JIFrameListarUsuarios();
        jDesktopPane.add(jIFrameListarUsuarios);
        jIFrameListarUsuarios.setVisible(true);
        try {jIFrameListarUsuarios.setMaximum(true);}
        catch (PropertyVetoException ex) {  }
    }//GEN-LAST:event_jButtonaRedeActionPerformed

    private void jButtonSolicitacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSolicitacaoActionPerformed
        Notificacao e=new Notificacao();
    }//GEN-LAST:event_jButtonSolicitacaoActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        Notificacao e=new Notificacao();    
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jButtonMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMensagemActionPerformed
        JFrame janela = new JFrame("Minhas conversas");
        janela.setSize(673, 330);
	janela.setVisible(true);
              janela.setResizable(false);
              janela.setLocationRelativeTo(null);
        JIFrameRecado recados=new JIFrameRecado(Principal.getIdUserLogando());
        recados.setVisible(true);
        janela.add(recados);
        
    }//GEN-LAST:event_jButtonMensagemActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonMeuPerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMeuPerfilMouseEntered
        jButtonMeuPerfil.setOpaque(true);
        jButtonMeuPerfil.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_jButtonMeuPerfilMouseEntered

    private void jButtonMeuPerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMeuPerfilMouseExited
        Color padrao=new Color(21,30,51);
        jButtonMeuPerfil.setBackground(padrao);
    }//GEN-LAST:event_jButtonMeuPerfilMouseExited

    private void jButtonaAmigosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonaAmigosMouseEntered
        jButtonaAmigos.setOpaque(true);
        jButtonaAmigos.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_jButtonaAmigosMouseEntered

    private void jButtonaAmigosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonaAmigosMouseExited
        Color padrao=new Color(21,30,51);
        jButtonaAmigos.setBackground(padrao);
    }//GEN-LAST:event_jButtonaAmigosMouseExited

    private void jButtonaRedeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonaRedeMouseEntered
        jButtonaRede.setOpaque(true);
        jButtonaRede.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_jButtonaRedeMouseEntered

    private void jButtonaRedeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonaRedeMouseExited
        Color padrao=new Color(21,30,51);
        jButtonaRede.setBackground(padrao);
    }//GEN-LAST:event_jButtonaRedeMouseExited

    private void jButtonMensagemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMensagemMouseEntered
        // TODO add your handling code here:
        jLabel2.setFont(new Font("Verdana",Font.BOLD,12));
    }//GEN-LAST:event_jButtonMensagemMouseEntered

    private void jButtonMensagemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonMensagemMouseExited
        // TODO add your handling code here:
        jLabel2.setFont(new Font("Verdana",Font.PLAIN,12));
    }//GEN-LAST:event_jButtonMensagemMouseExited

    private void jButtonSolicitacaoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSolicitacaoMouseEntered
        jLabel1.setFont(new Font("Verdana",Font.BOLD,12));
        if(Dados.getSolicitacaoAmizade(idUserLogando).size()>0){
        Color padrao=new Color(255,0,0);
        jButtonSolicitacao.setBackground(padrao);
        }
    }//GEN-LAST:event_jButtonSolicitacaoMouseEntered

    private void jButtonSolicitacaoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonSolicitacaoMouseExited
        // TODO add your handling code here:
        jLabel1.setFont(new Font("Verdana",Font.PLAIN,12));
        Color padrao=new Color(153,0,0);
        jButtonSolicitacao.setBackground(padrao);        
        jButtonSolicitacao.setBorder(null);
    }//GEN-LAST:event_jButtonSolicitacaoMouseExited

    private void jButtonInicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInicioMouseExited
        Color padrao=new Color(21,30,51);
        jButtonInicio.setBackground(padrao);
    }//GEN-LAST:event_jButtonInicioMouseExited

    private void jButtonInicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonInicioMouseEntered
        jButtonInicio.setOpaque(true);
        jButtonInicio.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_jButtonInicioMouseEntered

    private void jButtonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInicioActionPerformed
     Principal.getjDPPrincipal().removeAll();
        //Repaint - faz a atualização do conteúdo(componentes) de dentro do DesktopFrame
        Principal.getjDPPrincipal().repaint();
           //JIFramePerfil recebendo o ID de usuario logando
           JIFrameUsuariosRede jIFramePefil = new JIFrameUsuariosRede();
        //Add adicionando JIFramePerfil que foi criado ao JDesktioFrame(jDPPrincipal)          
        Principal.getjDPPrincipal().add(jIFramePefil);       
        //tornando frame Perfil visivel ao usuario
        jIFramePefil.setVisible(true);
        //setMaximum para adaptar internalFrame/componentes do frame atividades ao DesktopFrame em dimensões(tamanho).
        try {jIFramePefil.setMaximum(true);} 
        catch (PropertyVetoException ex) {  }
       
    }//GEN-LAST:event_jButtonInicioActionPerformed

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        jButton1.setOpaque(true);
        jButton1.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseExited
        Color padrao=new Color(21,30,51);
        jButton1.setBackground(padrao);
    }//GEN-LAST:event_jButton1MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JPanel MenuInferior;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonInicio;
    private javax.swing.JButton jButtonMensagem;
    private javax.swing.JButton jButtonMeuPerfil;
    private static javax.swing.JButton jButtonSolicitacao;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JButton jButtonUndo1;
    private javax.swing.JButton jButtonaAmigos;
    private javax.swing.JButton jButtonaRede;
    private javax.swing.JDesktopPane jDesktopPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelMensagem;
    private javax.swing.JScrollPane jScrollPaneRecado;
    private javax.swing.JTextArea jTextAreaRecado;
    // End of variables declaration//GEN-END:variables
    public static void Refresh(){        
        jButtonSolicitacao.setText("["+Integer.toString(Dados.getSolicitacaoAmizade(Principal.getIdUserLogando()).size())+"]");
        if(Dados.getSolicitacaoAmizade(Principal.getIdUserLogando()).size()>0){
        jButtonSolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonSolicitacao.setOpaque(true);
        }else{
            jButtonSolicitacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
            jButtonSolicitacao.setOpaque(false);
        }        
    }
    public static void removeMenu(){
        MenuInferior.show(false);
    }
}
