/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ProgramaColecionadores;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.image.BufferedImage;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.Iterator;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Casa
 */
public class JIFrameEditarPerfil extends javax.swing.JInternalFrame {
    Usuario usuario;
    int idUserLogando;
    private Atividade atividadeEditar;
    private Image img;
    private int privacidade;
    /**
     * Creates new form JIFrameEditarPerfil
     * @param idUserLogando
     */
    public JIFrameEditarPerfil(int idUserLogando) {
        
        this.usuario=Dados.getUsuariosBD().get(Principal.getIdUserLogando());
        this.idUserLogando=idUserLogando;
        initComponents();
        this.setBorder(null);
        Iterator<String> pais = Dados.getPais().iterator();
            while(pais.hasNext()){
                String nomesitens = pais.next();
                
                this.jComboBoxPais.addItem(nomesitens);
        }
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas  
        usuario=Dados.getUsuariosBD().get(idUserLogando);
        this.jTextFieldNome.setText(usuario.getNome());
        this.jTextFieldSobrenome.setText(usuario.getSobrenome());
        this.jComboBoxSexo.setSelectedItem(usuario.getSexo());
        this.jTextFieldEmail.setText(usuario.getEmail());
        this.jTextFieldNomeUsuario.setText(usuario.getNomeUsuario());
        this.jComboBoxIdioma.setSelectedItem(usuario.getIdioma());
        this.jTextFieldCpf.setText(usuario.getCpf());
        this.jTextFieldCNPJ.setText(usuario.getCNPJ());
        this.jTextFieldNumero.setText(usuario.getNumero());
        this.jComboBoxInteresse.setSelectedItem(usuario.getAreasInteresse());
        this.jFormattedTextFieldTelefone.setText(usuario.getTelefone());
        this.jFormattedTextFieldCelular.setText(usuario.getCelular());
        this.jTextAreaSobre.setText(usuario.getSobre());
        this.jComboBoxPrivacidade.setSelectedIndex(usuario.getPrivacidade());
        if(usuario.getFoto()!=null){ 
        jLabelFoto.setIcon(new ImageIcon(usuario.getFoto()));
        img=usuario.getFoto();}
        jTextAreaSobre.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jComboBoxIdioma.setEnabled(false);
        jComboBoxInteresse.setEnabled(false);
        this.jTextFieldCNPJ.setEnabled(false);
        this.jTextFieldCpf.setEnabled(false);
        this.jTextFieldEmail.setEnabled(false);
        this.jComboBoxPais.setEnabled(false);
        this.jTextFieldNome.setEnabled(false);
        this.jTextFieldNomeUsuario.setEnabled(false);
        this.jTextFieldNumero.setEnabled(false);
        this.jTextFieldSobrenome.setEnabled(false);
        this.jFormattedTextFieldCelular.setEnabled(false);
        this.jPasswordFieldSenha01.setEnabled(false);
        this.jPasswordFieldSenha02.setEnabled(false);
        this.jComboBoxPrivacidade.setEnabled(false);
        this.SALVAR.setVisible(false);//oculta o botão salvar
        jPasswordFieldSenha01.setText(usuario.getSenha());
        jPasswordFieldSenha02.setText(usuario.getSenha());
        jPasswordFieldSenha01.addMouseListener(new MouseAdapter() {///apaga o texto da caixa de de senha 01  
       public void mouseClicked(MouseEvent arg0) {jPasswordFieldSenha01.setText("");}
       });
       
       jPasswordFieldSenha02.addMouseListener(new MouseAdapter() {///apaga o texto da caixa de de senha 01  
       public void mouseClicked(MouseEvent arg0) {jPasswordFieldSenha02.setText("");}
       });   
       jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldEmail = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jPasswordFieldSenha01 = new javax.swing.JPasswordField();
        jLabel12 = new javax.swing.JLabel();
        jPasswordFieldSenha02 = new javax.swing.JPasswordField();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldSobrenome = new javax.swing.JTextField();
        jComboBoxSexo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldNumero = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxIdioma = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldCpf = new javax.swing.JTextField();
        jTextFieldCNPJ = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaSobre = new javax.swing.JTextArea();
        jComboBoxInteresse = new javax.swing.JComboBox();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jFormattedTextFieldCelular = new javax.swing.JFormattedTextField();
        privacidadelabel = new javax.swing.JLabel();
        jComboBoxPrivacidade = new javax.swing.JComboBox();
        jComboBoxPais = new javax.swing.JComboBox();
        EDITAR = new javax.swing.JLabel();
        SALVAR = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 5));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nome");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("E-mail");

        jTextFieldEmail.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextFieldEmail.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEmailActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Senha");

        jPasswordFieldSenha01.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jPasswordFieldSenha01.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPasswordFieldSenha01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordFieldSenha01ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Confirmar senha");

        jPasswordFieldSenha02.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jPasswordFieldSenha02.setSelectionColor(new java.awt.Color(21, 30, 51));

        jTextFieldNome.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextFieldNome.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Nome usuário");

        jTextFieldNomeUsuario.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextFieldNomeUsuario.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeUsuarioActionPerformed(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator1.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setOpaque(true);

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Sobrenome");

        jTextFieldSobrenome.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextFieldSobrenome.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldSobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldSobrenomeActionPerformed(evt);
            }
        });

        jComboBoxSexo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxSexo.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        jComboBoxSexo.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jComboBoxSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Sexo");

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Foto de perfil");

        jLabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default-user.png"))); // NOI18N
        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 2));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.setMaximumSize(new java.awt.Dimension(234, 202));
        jLabelFoto.setMinimumSize(new java.awt.Dimension(234, 202));
        jLabelFoto.setPreferredSize(new java.awt.Dimension(234, 202));
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseExited(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Telefone");

        jSeparator2.setBackground(new java.awt.Color(102, 102, 102));
        jSeparator2.setForeground(new java.awt.Color(102, 102, 102));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator2.setOpaque(true);

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Celular");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("País");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("DDI");

        jTextFieldNumero.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextFieldNumero.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNumeroActionPerformed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Idioma");

        jComboBoxIdioma.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxIdioma.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inglês", "Chinês Mandarim", "Espanhol", "Português", "Russo", "Francês", "Alemão", "Japonês", "Italiano", "Tailandês", "Polonês" }));
        jComboBoxIdioma.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jComboBoxIdioma.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("CPF");

        jTextFieldCpf.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextFieldCpf.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldCpf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCpfActionPerformed(evt);
            }
        });

        jTextFieldCNPJ.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextFieldCNPJ.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldCNPJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCNPJActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("CNPJ");

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Area de interesse");

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("Sobre");

        jTextAreaSobre.setColumns(20);
        jTextAreaSobre.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextAreaSobre.setLineWrap(true);
        jTextAreaSobre.setRows(5);
        jTextAreaSobre.setWrapStyleWord(true);
        jTextAreaSobre.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jTextAreaSobre.setSelectionColor(new java.awt.Color(21, 30, 51));
        jScrollPane1.setViewportView(jTextAreaSobre);

        jComboBoxInteresse.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Camisetas", "Moedas", "Cartões", "Quadrinhos", "Jogos", "Hotwheels" }));
        jComboBoxInteresse.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jComboBoxInteresse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jFormattedTextFieldTelefone.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jFormattedTextFieldTelefone.setSelectionColor(new java.awt.Color(21, 30, 51));

        jFormattedTextFieldCelular.setDisabledTextColor(new java.awt.Color(21, 30, 51));
        jFormattedTextFieldCelular.setSelectionColor(new java.awt.Color(21, 30, 51));

        privacidadelabel.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        privacidadelabel.setForeground(new java.awt.Color(102, 102, 102));
        privacidadelabel.setText("Privacidade");

        jComboBoxPrivacidade.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPrivacidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPrivacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Amigos", "Privado" }));
        jComboBoxPrivacidade.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jComboBoxPrivacidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxPrivacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrivacidadeActionPerformed(evt);
            }
        });

        jComboBoxPais.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPais.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPais.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jComboBoxPais.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxPais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPaisActionPerformed(evt);
            }
        });

        EDITAR.setBackground(new java.awt.Color(21, 30, 51));
        EDITAR.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        EDITAR.setForeground(new java.awt.Color(255, 255, 255));
        EDITAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EDITAR.setText("EDITAR");
        EDITAR.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        EDITAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EDITAR.setOpaque(true);
        EDITAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EDITARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EDITARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EDITARMouseExited(evt);
            }
        });

        SALVAR.setBackground(new java.awt.Color(21, 30, 51));
        SALVAR.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        SALVAR.setForeground(new java.awt.Color(255, 255, 255));
        SALVAR.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        SALVAR.setText("SALVAR");
        SALVAR.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        SALVAR.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SALVAR.setOpaque(true);
        SALVAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SALVARMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SALVARMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SALVARMouseExited(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Meu Perfil");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel12)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel10)
                            .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldSenha01, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordFieldSenha02, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
                                    .addComponent(jComboBoxInteresse, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(privacidadelabel)
                                            .addComponent(jComboBoxPrivacidade, 0, 111, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel21)
                                            .addComponent(jComboBoxIdioma, 0, 1, Short.MAX_VALUE)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxPais, 0, 122, Short.MAX_VALUE))))
                                .addGap(47, 47, 47)))
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCNPJ)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(35, 35, 35)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel8Layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(20, 20, 20)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(privacidadelabel)
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                            .addComponent(jComboBoxPrivacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxPais, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jComboBoxInteresse, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                                                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jFormattedTextFieldCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                        .addComponent(jLabel15)
                                                        .addGap(4, 4, 4))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                        .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(7, 7, 7)
                                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(jTextFieldCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jTextFieldCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel8Layout.createSequentialGroup()
                                                .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(26, 26, 26)
                                                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jTextFieldNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPasswordFieldSenha01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jPasswordFieldSenha02, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(9, 9, 9))))))
                            .addComponent(jSeparator2)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jSeparator1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EDITAR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SALVAR, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEmailActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldNomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeUsuarioActionPerformed

    private void jTextFieldSobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldSobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldSobrenomeActionPerformed

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        if(EDITAR.isVisible()==true && EDITAR.isShowing()==true){
        String caminho;
        JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
        File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
        arquivo.setCurrentDirectory(diretorio);
        arquivo.showOpenDialog(null);
        caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
        img=new ImageIcon(caminho).getImage().getScaledInstance(240, 202, Image.SCALE_DEFAULT);                    
        jLabelFoto.setIcon(new ImageIcon(img));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        }
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void jTextFieldNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNumeroActionPerformed

    private void jTextFieldCpfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCpfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCpfActionPerformed

    private void jTextFieldCNPJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCNPJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCNPJActionPerformed

    private void jComboBoxPrivacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrivacidadeActionPerformed
    
    }//GEN-LAST:event_jComboBoxPrivacidadeActionPerformed

    private void jPasswordFieldSenha01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordFieldSenha01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordFieldSenha01ActionPerformed

    private void jComboBoxPaisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPaisActionPerformed
             if(this.jComboBoxPais.getSelectedIndex()==1){
           String novoPais=JOptionPane.showInputDialog("Qual é o País?").toUpperCase();
           Dados.getPais().add(novoPais);
           jComboBoxPais.removeAllItems();
           Iterator<String> pais = Dados.getPais().iterator();
            while(pais.hasNext()){
                String nomesitens = pais.next();
                
                this.jComboBoxPais.addItem(nomesitens);
            }
       }
     
    }//GEN-LAST:event_jComboBoxPaisActionPerformed

    private void EDITARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITARMouseClicked
        // TODO add your handling code here:
        atividadeEditar=new Atividade();
        atividadeEditar.usuarios.add((Usuario) usuario.clone());
        //atividade.lstItemAlterado.add(camiseta);
        atividadeEditar.salvar();
        this.SALVAR.setVisible(true);//oculta o botão salvar
        //////habilita a edicao dos campos
        jTextAreaSobre.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jComboBoxSexo.setEnabled(true);
        jComboBoxIdioma.setEnabled(true);
        jComboBoxInteresse.setEnabled(true);
        this.jTextFieldCNPJ.setEnabled(true);
        this.jTextFieldCpf.setEnabled(true);
        this.jTextFieldEmail.setEnabled(true);
        this.jComboBoxPais.setEnabled(true);
        this.jTextFieldNome.setEnabled(true);
        this.jTextFieldNomeUsuario.setEnabled(true);
        this.jTextFieldNumero.setEnabled(true);
        this.jTextFieldSobrenome.setEnabled(true);
        this.jComboBoxPrivacidade.setEnabled(true);
        this.jFormattedTextFieldCelular.setEnabled(true);
        this.jPasswordFieldSenha01.setEnabled(true);
        this.jPasswordFieldSenha02.setEnabled(true);
        this.jComboBoxPrivacidade.setEnabled(true);
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    }//GEN-LAST:event_EDITARMouseClicked

    private void SALVARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALVARMouseClicked
        // TODO add your handling code here:
        String senha = new String(jPasswordFieldSenha01.getPassword());
        Usuario novoUsuario=Dados.getUsuariosBD().get(idUserLogando);
        novoUsuario.setSenha(this.jPasswordFieldSenha01.getText());
        novoUsuario.setEmail(this.jTextFieldEmail.getText());
        novoUsuario.setNomeUsuario(this.jTextFieldNomeUsuario.getText());
        novoUsuario.setNome(this.jTextFieldNome.getText());
        novoUsuario.setTelefone(this.jFormattedTextFieldTelefone.getText());
        novoUsuario.setCelular(this.jFormattedTextFieldCelular.getText());
        novoUsuario.setSobrenome(this.jTextFieldSobrenome.getText());
        novoUsuario.setSexo(this.jComboBoxSexo.getSelectedItem().toString());
        novoUsuario.setIdioma(this.jComboBoxIdioma.getSelectedItem().toString());
        novoUsuario.setIdPais(this.jComboBoxPais.getSelectedIndex());
        novoUsuario.setAreasInteresse(this.jComboBoxInteresse.getSelectedItem().toString());
        novoUsuario.setNumero(this.jTextFieldNumero.getText());
        novoUsuario.setSobre(this.jTextAreaSobre.getText());
        novoUsuario.setCpf(this.jTextFieldCpf.getText());
        novoUsuario.setCNPJ(this.jTextFieldCNPJ.getText());
        String txtprivacidade=this.jComboBoxPrivacidade.getSelectedItem().toString();
        switch (txtprivacidade) {
            case "Privado":
                privacidade=2;
                break;
            case "Amigos":
                privacidade=1;
                break;
            default:
                privacidade=0;
                break;
        }
        novoUsuario.setPrivacidade(privacidade);
        novoUsuario.setFoto(img);
        atividadeEditar.usuarios.add(novoUsuario);//adiciona nova versao de camiseta
        Dados.getUsuariosBD().get(novoUsuario.getIdUsuario()).equals(novoUsuario);
        this.SALVAR.setVisible(false);//oculta o botão salvar
        //////habilita a edicao dos campos
        jTextAreaSobre.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jComboBoxSexo.setEnabled(false);
        jComboBoxIdioma.setEnabled(false);
        jComboBoxInteresse.setEnabled(false);
        this.jTextFieldCNPJ.setEnabled(false);
        this.jTextFieldCpf.setEnabled(false);
        this.jTextFieldEmail.setEnabled(false);
        this.jComboBoxPais.setEditable(false);
        this.jTextFieldNome.setEnabled(false);
        this.jTextFieldNomeUsuario.setEnabled(false);
        this.jTextFieldNumero.setEnabled(false);
        this.jTextFieldSobrenome.setEnabled(false);
        this.jComboBoxPrivacidade.setEnabled(false);
        this.jFormattedTextFieldCelular.setEnabled(false);
        this.jPasswordFieldSenha01.setEnabled(false);
        this.jPasswordFieldSenha02.setEnabled(false);
        this.jComboBoxPrivacidade.setEnabled(false);
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_SALVARMouseClicked

    private void SALVARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALVARMouseEntered
        SALVAR.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_SALVARMouseEntered

    private void SALVARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SALVARMouseExited
        Color padrao=new Color(21,30,51);
        SALVAR.setBackground(padrao);
    }//GEN-LAST:event_SALVARMouseExited

    private void EDITARMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITARMouseEntered
        EDITAR.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_EDITARMouseEntered

    private void EDITARMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EDITARMouseExited
        Color padrao=new Color(21,30,51);
        EDITAR.setBackground(padrao);
    }//GEN-LAST:event_EDITARMouseExited

    private void jLabelFotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseEntered
        // TODO add your handling code here:
        if(SALVAR.isVisible()==true){
        if(Dados.getUsuariosBD().get(Principal.getIdUserLogando()).getFoto()==null){
            ImageIcon img=new ImageIcon(Principal.class.getResource("/Images/default_user_Editar.png"));
            jLabelFoto.setIcon(new ImageIcon(img.getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH)));
        }
        }
    }//GEN-LAST:event_jLabelFotoMouseEntered

    private void jLabelFotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseExited
        // TODO add your handling code here:
        if(Dados.getUsuariosBD().get(Principal.getIdUserLogando()).getFoto()==null){
            ImageIcon img=new ImageIcon(Principal.class.getResource("/Images/default-user.png"));
            jLabelFoto.setIcon(new ImageIcon(img.getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH)));
        }
    }//GEN-LAST:event_jLabelFotoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private static javax.swing.JLabel EDITAR;
    private javax.swing.JLabel SALVAR;
    private javax.swing.JComboBox jComboBoxIdioma;
    private javax.swing.JComboBox jComboBoxInteresse;
    private javax.swing.JComboBox jComboBoxPais;
    private javax.swing.JComboBox jComboBoxPrivacidade;
    private javax.swing.JComboBox jComboBoxSexo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCelular;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordFieldSenha01;
    private javax.swing.JPasswordField jPasswordFieldSenha02;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextAreaSobre;
    private javax.swing.JTextField jTextFieldCNPJ;
    private javax.swing.JTextField jTextFieldCpf;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    private javax.swing.JTextField jTextFieldNumero;
    private javax.swing.JTextField jTextFieldSobrenome;
    private javax.swing.JLabel privacidadelabel;
    // End of variables declaration//GEN-END:variables
    public static void NoEdit(){
        
        EDITAR.setVisible(false);
        //jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        }
}
