package ProgramaColecionadores;

import Jogo.Jogador;
import Jogo.TelaJogo;
import Jogo.Trunfo;
import static ProgramaColecionadores.Principal.idUserLog;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ScrollPaneConstants;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;
import view.Colecoes;

/**
 *
 * @author Casa
 */
public class JIFramePerfil extends javax.swing.JInternalFrame {
    static Integer idUsuario;
    private Usuario usuario=Dados.getUsuariosBD().get(idUsuario);
    int idUserLogando;
    private ExibeItemColecao e;
    private JInternalFrame container;    
   
    /**
     * Creates new form JIFramePerfil
     * @param idUsuario
     */
    public JIFramePerfil(int idUsuario) {
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas  
        this.idUsuario=idUsuario;
        usuario=Dados.getUsuariosBD().get(idUsuario);
        this.isMaximum=true;
        initComponents();
        //JPanelAtividadeRede jIFrameMinhasAtividades = new JPanelAtividadeRede();
        jPanelAtividadeRede2.ativadadesUsuario(idUsuario);
        //fazer verificação caso houver propaganda...
        if(usuario.getPubli1()!=null){
            this.jLabelPublicidade.setIcon(new ImageIcon(usuario.getPubli1().getScaledInstance(250,600, Image.SCALE_SMOOTH)));
       jPanel2.updateUI();
        }else{
          jPanel2.setVisible(false); 
       }
        jPanel8.setVisible(false);
        //jDesktopConteudoPerfil.add(jIFrameMinhasAtividades);
        //jIFrameMinhasAtividades.setVisible(true);
        usuario=Dados.getUsuariosBD().get(idUsuario);
        if(Principal.getIdUserLogando()==idUsuario){
            jButtonAdicionarAmigo.setText("EDITAR");
        }else{jPanel8.setVisible(false);}
        
        jLabelFoto.setSize(240,185);
        if(usuario.getFoto()==null){   
            jLabelFoto.setIcon(new ImageIcon(new ImageIcon(Principal.class.getResource("/Images/default-user.png")).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH)));       
               }
        else{            
        ImageIcon foto=new ImageIcon(usuario.getFoto().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH));
        jLabelFoto.setIcon((foto));
        }
        
        jButtonNome.setText(usuario.getNome()+" "+usuario.getSobrenome());
        if(usuario.getAreasInteresse()!=null){jLabelInteresseC.setText(usuario.getAreasInteresse());}
        else{jLabelInteresseC.setText("Nenhum");}
        this.jLabelRank.setText(Integer.toString(usuario.getRank()+1));
        pais.setText(Dados.getPais().get(usuario.getIdPais()));
        this.jLabelNumeroColecoes.setText(Integer.toString(usuario.getQuantidadeColecoes()));
        this.jLabelItens.setText(Integer.toString(usuario.getQuantidadeItensColecoes()));
//       verificaColecoes(); 
       for(Integer idComunidade:Dados.getComunidadesUsuario(idUsuario)){
       view.IconComunidade icone=new view.IconComunidade(idComunidade);
       
       PainelExibicao.add(icone);icone.setVisible(true);
       }
       this.jComboBoxItem.setEnabled(false);
        if(Principal.getIdUserLogando()!=idUsuario){
           jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
           ADDItem.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
           Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
           jComboBoxColecao.setEnabled(false);
           JIFrameUsuariosRede.removeMenu();
           jComboBoxColecao.setVisible(false);
           ADDItem.setVisible(false);
           Excluir.setVisible(false);
           jComboBoxItem.setVisible(false);
           ADDAmigo.setVisible(true);
       }else{this.ADDAmigo.setVisible(false);}
       
 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelJogo = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbListarCliente = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbListarJogos = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButtonConvidarJogo = new javax.swing.JButton();
        jButtonJogar = new javax.swing.JButton();
        jComboBoxColecaoJogo = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelFoto = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jButtonRecado = new javax.swing.JButton();
        jButtonAdicionarAmigo = new javax.swing.JButton();
        jButtonJogoTrunfo = new javax.swing.JButton();
        colecoes = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jComboBoxColecao = new javax.swing.JComboBox();
        jComboBoxItem = new javax.swing.JComboBox();
        ADDItem = new javax.swing.JLabel();
        Excluir = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelNumeroColecoes = new javax.swing.JLabel();
        jLabelItens = new javax.swing.JLabel();
        jLabelRank = new javax.swing.JLabel();
        jButtonNome = new javax.swing.JButton();
        jLabelInteresse1 = new javax.swing.JLabel();
        jLabelInteresseC = new javax.swing.JLabel();
        jLabelInteresse2 = new javax.swing.JLabel();
        pais = new javax.swing.JLabel();
        ADDAmigo = new javax.swing.JLabel();
        jPanelDetalhes = new javax.swing.JPanel();
        exibeAmigos = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PainelExibicao = new javax.swing.JPanel();
        exibeComunidades = new javax.swing.JLabel();
        jDesktopConteudoPerfil = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanelAtividadeRede2 = new ProgramaColecionadores.JPanelAtividadeRede();
        jPanel2 = new javax.swing.JPanel();
        jLabelPublicidade = new javax.swing.JLabel();

        jPanelJogo.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jtbListarCliente.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtbListarCliente.setForeground(new java.awt.Color(21, 30, 51));
        jtbListarCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbListarCliente.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtbListarCliente.setGridColor(new java.awt.Color(21, 30, 51));
        jtbListarCliente.setSelectionBackground(new java.awt.Color(21, 30, 51));
        jtbListarCliente.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jtbListarCliente);

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane3.setOpaque(false);

        jtbListarJogos.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtbListarJogos.setForeground(new java.awt.Color(21, 30, 51));
        jtbListarJogos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Jogador 1", "Pontos", "Jogador 2", "Pontos", "Tipo Colecao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbListarJogos.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jtbListarJogos.setGridColor(new java.awt.Color(21, 30, 51));
        jtbListarJogos.setOpaque(false);
        jtbListarJogos.setSelectionBackground(new java.awt.Color(21, 30, 51));
        jtbListarJogos.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(jtbListarJogos);

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(21, 30, 51));
        jLabel5.setText("Convidar para jogar");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(21, 30, 51));
        jLabel6.setText("Jogo Anteriores");

        jButtonConvidarJogo.setBackground(new java.awt.Color(21, 30, 51));
        jButtonConvidarJogo.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonConvidarJogo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonConvidarJogo.setText("Convidar Para Jogar");
        jButtonConvidarJogo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonConvidarJogo.setContentAreaFilled(false);
        jButtonConvidarJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConvidarJogo.setOpaque(true);
        jButtonConvidarJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonConvidarJogoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonConvidarJogoMouseExited(evt);
            }
        });
        jButtonConvidarJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConvidarJogoActionPerformed(evt);
            }
        });

        jButtonJogar.setBackground(new java.awt.Color(21, 30, 51));
        jButtonJogar.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jButtonJogar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJogar.setText("Jogar");
        jButtonJogar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonJogar.setContentAreaFilled(false);
        jButtonJogar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJogar.setOpaque(true);
        jButtonJogar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonJogarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonJogarMouseExited(evt);
            }
        });
        jButtonJogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogarActionPerformed(evt);
            }
        });

        jComboBoxColecaoJogo.setForeground(new java.awt.Color(21, 30, 51));
        jComboBoxColecaoJogo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Camiseta", "Cartao", "Jogo", "Moeda", "Quadrinho", "HotWheels" }));
        jComboBoxColecaoJogo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxColecaoJogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxColecaoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColecaoJogoActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(21, 30, 51));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("TRUNFO COLECIONADORES");

        javax.swing.GroupLayout jPanelJogoLayout = new javax.swing.GroupLayout(jPanelJogo);
        jPanelJogo.setLayout(jPanelJogoLayout);
        jPanelJogoLayout.setHorizontalGroup(
            jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelJogoLayout.createSequentialGroup()
                        .addGroup(jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelJogoLayout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(72, 72, 72))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelJogoLayout.createSequentialGroup()
                                .addGroup(jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButtonJogar, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(jPanelJogoLayout.createSequentialGroup()
                                .addComponent(jComboBoxColecaoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonConvidarJogo, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanelJogoLayout.setVerticalGroup(
            jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelJogoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(38, 38, 38)
                .addGroup(jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 233, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelJogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonConvidarJogo)
                    .addComponent(jButtonJogar)
                    .addComponent(jComboBoxColecaoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);
        setIconifiable(true);
        setTitle("Rede de Colecionadores");
        setMaximumSize(new java.awt.Dimension(934, 844));
        setMinimumSize(new java.awt.Dimension(934, 844));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setAutoscrolls(true);
        jPanel7.setMaximumSize(new java.awt.Dimension(934, 844));
        jPanel7.setMinimumSize(new java.awt.Dimension(500, 844));

        jPanel1.setBackground(new java.awt.Color(21, 30, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 0, 0, new java.awt.Color(21, 30, 51)));
        jPanel1.setMaximumSize(new java.awt.Dimension(256, 32767));
        jPanel1.setMinimumSize(new java.awt.Dimension(256, 0));

        jLabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(255, 255, 255)));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setMaximumSize(new java.awt.Dimension(234, 202));
        jLabelFoto.setMinimumSize(new java.awt.Dimension(234, 202));
        jLabelFoto.setName(""); // NOI18N
        jLabelFoto.setPreferredSize(new java.awt.Dimension(234, 202));
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseExited(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(21, 30, 51));
        jPanel5.setMaximumSize(new java.awt.Dimension(32767, 542));
        jPanel5.setMinimumSize(new java.awt.Dimension(500, 542));
        jPanel5.setPreferredSize(new java.awt.Dimension(500, 542));

        jButtonRecado.setBackground(new java.awt.Color(21, 30, 51));
        jButtonRecado.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonRecado.setForeground(new java.awt.Color(255, 255, 255));
        jButtonRecado.setText("CONVERSAS");
        jButtonRecado.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonRecado.setContentAreaFilled(false);
        jButtonRecado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonRecado.setFocusPainted(false);
        jButtonRecado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonRecado.setOpaque(true);
        jButtonRecado.setPreferredSize(new java.awt.Dimension(115, 21));
        jButtonRecado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonRecadoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonRecadoMouseExited(evt);
            }
        });
        jButtonRecado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRecadoActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonRecado);

        jButtonAdicionarAmigo.setBackground(new java.awt.Color(21, 30, 51));
        jButtonAdicionarAmigo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonAdicionarAmigo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAdicionarAmigo.setText("Perfil");
        jButtonAdicionarAmigo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonAdicionarAmigo.setContentAreaFilled(false);
        jButtonAdicionarAmigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAdicionarAmigo.setFocusPainted(false);
        jButtonAdicionarAmigo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonAdicionarAmigo.setOpaque(true);
        jButtonAdicionarAmigo.setPreferredSize(new java.awt.Dimension(115, 21));
        jButtonAdicionarAmigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonAdicionarAmigoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonAdicionarAmigoMouseExited(evt);
            }
        });
        jButtonAdicionarAmigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAdicionarAmigoActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonAdicionarAmigo);

        jButtonJogoTrunfo.setBackground(new java.awt.Color(21, 30, 51));
        jButtonJogoTrunfo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jButtonJogoTrunfo.setForeground(new java.awt.Color(255, 255, 255));
        jButtonJogoTrunfo.setText("Super Trunfo");
        jButtonJogoTrunfo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        jButtonJogoTrunfo.setContentAreaFilled(false);
        jButtonJogoTrunfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonJogoTrunfo.setFocusPainted(false);
        jButtonJogoTrunfo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonJogoTrunfo.setOpaque(true);
        jButtonJogoTrunfo.setPreferredSize(new java.awt.Dimension(115, 21));
        jButtonJogoTrunfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButtonJogoTrunfoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButtonJogoTrunfoMouseExited(evt);
            }
        });
        jButtonJogoTrunfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonJogoTrunfoActionPerformed(evt);
            }
        });
        jPanel5.add(jButtonJogoTrunfo);

        colecoes.setBackground(new java.awt.Color(21, 30, 51));
        colecoes.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        colecoes.setForeground(new java.awt.Color(255, 255, 255));
        colecoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        colecoes.setText("Coleções");
        colecoes.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        colecoes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        colecoes.setOpaque(true);
        colecoes.setPreferredSize(new java.awt.Dimension(115, 21));
        colecoes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                colecoesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                colecoesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                colecoesMouseExited(evt);
            }
        });
        jPanel5.add(colecoes);

        jPanel8.setBackground(new java.awt.Color(21, 30, 51));
        jPanel8.setPreferredSize(new java.awt.Dimension(455, 85));

        jComboBoxColecao.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jComboBoxColecao.setForeground(new java.awt.Color(21, 30, 51));
        jComboBoxColecao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Camiseta", "Cartão", "HotWheels", "Jogo", "Moeda", "Quadrinho" }));
        jComboBoxColecao.setBorder(null);
        jComboBoxColecao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxColecao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxColecaoActionPerformed(evt);
            }
        });

        jComboBoxItem.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jComboBoxItem.setForeground(new java.awt.Color(21, 30, 51));
        jComboBoxItem.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um item" }));
        jComboBoxItem.setBorder(null);

        ADDItem.setBackground(new java.awt.Color(0, 102, 0));
        ADDItem.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ADDItem.setForeground(java.awt.SystemColor.control);
        ADDItem.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADDItem.setText("Adicionar Item");
        ADDItem.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        ADDItem.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADDItem.setOpaque(true);
        ADDItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDItemMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDItemMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDItemMouseExited(evt);
            }
        });

        Excluir.setBackground(new java.awt.Color(153, 0, 0));
        Excluir.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Excluir.setForeground(java.awt.SystemColor.control);
        Excluir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Excluir.setText("Remover Item");
        Excluir.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Excluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Excluir.setOpaque(true);
        Excluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExcluirMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExcluirMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jComboBoxColecao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(ADDItem, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jComboBoxItem, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jComboBoxColecao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ADDItem, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBoxItem, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel8);

        jPanel6.setBackground(new java.awt.Color(21, 30, 51));
        jPanel6.setPreferredSize(new java.awt.Dimension(292, 120));

        jLabel1.setBackground(new java.awt.Color(21, 30, 51));
        jLabel1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Coleções");
        jLabel1.setMinimumSize(new java.awt.Dimension(265, 20));
        jLabel1.setPreferredSize(new java.awt.Dimension(130, 20));

        jLabel2.setBackground(new java.awt.Color(21, 30, 51));
        jLabel2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Itens");
        jLabel2.setMinimumSize(new java.awt.Dimension(265, 20));
        jLabel2.setPreferredSize(new java.awt.Dimension(130, 20));

        jLabel3.setBackground(new java.awt.Color(21, 30, 51));
        jLabel3.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Ranking");
        jLabel3.setMinimumSize(new java.awt.Dimension(265, 20));
        jLabel3.setPreferredSize(new java.awt.Dimension(130, 20));

        jLabelNumeroColecoes.setBackground(new java.awt.Color(21, 30, 51));
        jLabelNumeroColecoes.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabelNumeroColecoes.setForeground(new java.awt.Color(255, 255, 255));
        jLabelNumeroColecoes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelNumeroColecoes.setText(" ");
        jLabelNumeroColecoes.setMinimumSize(new java.awt.Dimension(265, 20));
        jLabelNumeroColecoes.setPreferredSize(new java.awt.Dimension(130, 20));

        jLabelItens.setBackground(new java.awt.Color(21, 30, 51));
        jLabelItens.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabelItens.setForeground(new java.awt.Color(255, 255, 255));
        jLabelItens.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelItens.setText(" ");
        jLabelItens.setMinimumSize(new java.awt.Dimension(265, 20));
        jLabelItens.setPreferredSize(new java.awt.Dimension(130, 20));
        jLabelItens.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jLabelItensMouseReleased(evt);
            }
        });

        jLabelRank.setBackground(new java.awt.Color(21, 30, 51));
        jLabelRank.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabelRank.setForeground(new java.awt.Color(255, 255, 255));
        jLabelRank.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelRank.setText(" ");
        jLabelRank.setMinimumSize(new java.awt.Dimension(265, 20));
        jLabelRank.setPreferredSize(new java.awt.Dimension(130, 20));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelNumeroColecoes, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelItens, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRank, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelNumeroColecoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelItens, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        jPanel5.add(jPanel6);

        jButtonNome.setBackground(new java.awt.Color(255, 255, 255));
        jButtonNome.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jButtonNome.setForeground(new java.awt.Color(255, 255, 255));
        jButtonNome.setText("Nome:");
        jButtonNome.setContentAreaFilled(false);
        jButtonNome.setEnabled(false);
        jButtonNome.setFocusPainted(false);
        jButtonNome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jButtonNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNomeActionPerformed(evt);
            }
        });

        jLabelInteresse1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelInteresse1.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInteresse1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInteresse1.setText("Area de interesse");

        jLabelInteresseC.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        jLabelInteresseC.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInteresseC.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabelInteresse2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelInteresse2.setForeground(new java.awt.Color(255, 255, 255));
        jLabelInteresse2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInteresse2.setText("País");

        pais.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        pais.setForeground(new java.awt.Color(255, 255, 255));
        pais.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        ADDAmigo.setBackground(new java.awt.Color(0, 102, 0));
        ADDAmigo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        ADDAmigo.setForeground(java.awt.SystemColor.control);
        ADDAmigo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ADDAmigo.setText("Adicionar Amigo");
        ADDAmigo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        ADDAmigo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ADDAmigo.setOpaque(true);
        ADDAmigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ADDAmigoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ADDAmigoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ADDAmigoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ADDAmigo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelInteresseC, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jLabelInteresse1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(pais, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                    .addComponent(jLabelInteresse2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jLabelFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(7, 7, 7)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jButtonNome, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabelInteresse2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelInteresse1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(pais, javax.swing.GroupLayout.DEFAULT_SIZE, 15, Short.MAX_VALUE)
                    .addComponent(jLabelInteresseC, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ADDAmigo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanelDetalhes.setBackground(new java.awt.Color(255, 255, 255));
        jPanelDetalhes.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 10, 0, new java.awt.Color(21, 30, 51)));

        exibeAmigos.setBackground(new java.awt.Color(21, 30, 51));
        exibeAmigos.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        exibeAmigos.setForeground(new java.awt.Color(255, 255, 255));
        exibeAmigos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exibeAmigos.setText("Exibir Amigos");
        exibeAmigos.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        exibeAmigos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exibeAmigos.setOpaque(true);
        exibeAmigos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exibeAmigosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exibeAmigosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exibeAmigosMouseExited(evt);
            }
        });

        jScrollPane1.setBorder(null);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(3276799, 32767));

        PainelExibicao.setBackground(new java.awt.Color(255, 255, 255));
        PainelExibicao.setLayout(new javax.swing.BoxLayout(PainelExibicao, javax.swing.BoxLayout.LINE_AXIS));
        jScrollPane1.setViewportView(PainelExibicao);

        exibeComunidades.setBackground(new java.awt.Color(21, 30, 51));
        exibeComunidades.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        exibeComunidades.setForeground(new java.awt.Color(255, 255, 255));
        exibeComunidades.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        exibeComunidades.setText("Exibir Comunidades");
        exibeComunidades.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        exibeComunidades.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        exibeComunidades.setOpaque(true);
        exibeComunidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exibeComunidadesMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exibeComunidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exibeComunidadesMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanelDetalhesLayout = new javax.swing.GroupLayout(jPanelDetalhes);
        jPanelDetalhes.setLayout(jPanelDetalhesLayout);
        jPanelDetalhesLayout.setHorizontalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addComponent(exibeComunidades)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(exibeAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 815, Short.MAX_VALUE))
        );
        jPanelDetalhesLayout.setVerticalGroup(
            jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDetalhesLayout.createSequentialGroup()
                .addGroup(jPanelDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(exibeComunidades, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(exibeAmigos, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE))
        );

        jDesktopConteudoPerfil.setBackground(new java.awt.Color(255, 255, 255));
        jDesktopConteudoPerfil.setMinimumSize(new java.awt.Dimension(960, 666));

        jPanelAtividadeRede2.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane4.setViewportView(jPanelAtividadeRede2);

        javax.swing.GroupLayout jDesktopConteudoPerfilLayout = new javax.swing.GroupLayout(jDesktopConteudoPerfil);
        jDesktopConteudoPerfil.setLayout(jDesktopConteudoPerfilLayout);
        jDesktopConteudoPerfilLayout.setHorizontalGroup(
            jDesktopConteudoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jDesktopConteudoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE))
        );
        jDesktopConteudoPerfilLayout.setVerticalGroup(
            jDesktopConteudoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jDesktopConteudoPerfilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jDesktopConteudoPerfilLayout.createSequentialGroup()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(250, 0));

        jLabelPublicidade.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabelPublicidade.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelPublicidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabelPublicidade)
                .addContainerGap(732, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelDetalhes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jDesktopConteudoPerfil, javax.swing.GroupLayout.PREFERRED_SIZE, 863, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 228, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanelDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesktopConteudoPerfil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConvidarJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConvidarJogoActionPerformed
        if (jtbListarCliente.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum usuário selecionado");}
        else{
            int idUsuario = (Integer) jtbListarCliente.getValueAt(jtbListarCliente.getSelectedRow(), 0);
            int tipoCarta=this.jComboBoxColecaoJogo.getSelectedIndex()+1;
            Trunfo jogo=new Trunfo(Principal.getIdUserLogando(),idUsuario,tipoCarta);
            if(jogo.verificaExistenciaBaralho()){
                TelaJogo tela=new TelaJogo(jogo.getIdJogo());
                tela.setIdUserLogando(idUserLogando);
                if(tela.getPossuiCartas()){

                    container.dispose();
                    container = new JInternalFrame("Super Trunfo");
                    ((BasicInternalFrameUI)container.getUI()).setNorthPane(null); //retirar o painel superior
                    container.setBorder(null);//retirar bordas
                    container.setPreferredSize(new Dimension(700,500));
                    container.setBounds(0,0,700,500);
                    container.add(tela);
                    tela.setVisible(true);
                    container.setVisible(true);
                    Principal.getjDPPrincipal().removeAll();
                    //Repaint - faz a atualização do conteúdo(componentes) de dentro do DesktopFrame
                    Principal.getjDPPrincipal().repaint();
                    Principal.getjDPPrincipal().add(container);
                    Principal.getjDPPrincipal().updateUI();
                }
            }
        }
    }//GEN-LAST:event_jButtonConvidarJogoActionPerformed

    private void jButtonJogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogarActionPerformed
        if (jtbListarJogos.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum Jogo selecionado");}
        else{
            int idJogo = (int) jtbListarJogos.getValueAt(jtbListarJogos.getSelectedRow(), 0);
            TelaJogo telaJogo=new TelaJogo(idJogo);
            if(telaJogo.getPossuiCartas()){
                telaJogo.setIdUserLogando(idUserLogando);
                Principal.getjDPPrincipal().removeAll();
                //Repaint - faz a atualização do conteúdo(componentes) de dentro do DesktopFrame
                Principal.getjDPPrincipal().repaint();
                container.dispose();
                container = new JInternalFrame("Super Trunfo");
                telaJogo.setVisible(true);
                container.setPreferredSize(new Dimension(800,600));
                container.setBounds(0,0,800,600);
                container.add(telaJogo);
                ((BasicInternalFrameUI)container.getUI()).setNorthPane(null); //retirar o painel superior
                container.setBorder(null);//retirar bordas
                telaJogo.setVisible(true);
                container.setVisible(true);
                Principal.getjDPPrincipal().add(container);
                Principal.getjDPPrincipal().updateUI();
            }
        }
    }//GEN-LAST:event_jButtonJogarActionPerformed

    private void jComboBoxColecaoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColecaoJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxColecaoJogoActionPerformed

    private void jButtonJogarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJogarMouseEntered
        jButtonJogar.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jButtonJogarMouseEntered

    private void jButtonJogarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJogarMouseExited
        Color padrao=new Color(21,30,51);
        jButtonJogar.setBackground(padrao);
    }//GEN-LAST:event_jButtonJogarMouseExited

    private void jButtonConvidarJogoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConvidarJogoMouseEntered
        jButtonConvidarJogo.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jButtonConvidarJogoMouseEntered

    private void jButtonConvidarJogoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonConvidarJogoMouseExited
        Color padrao=new Color(21,30,51);
        jButtonConvidarJogo.setBackground(padrao);
    }//GEN-LAST:event_jButtonConvidarJogoMouseExited

    private void exibeComunidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exibeComunidadesMouseExited
        // TODO add your handling code here:
        Color padrao=new Color(21,30,51);
        exibeComunidades.setBackground(padrao);
    }//GEN-LAST:event_exibeComunidadesMouseExited

    private void exibeComunidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exibeComunidadesMouseEntered
        exibeComunidades.setOpaque(true);
        exibeComunidades.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_exibeComunidadesMouseEntered

    private void exibeComunidadesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exibeComunidadesMouseClicked
        PainelExibicao.removeAll();
        for(Integer idComunidade:Dados.getComunidadesUsuario(idUsuario)){
            view.IconComunidade icone=new view.IconComunidade(idComunidade);
            PainelExibicao.add(icone);icone.show(true);
        }
        PainelExibicao.updateUI();PainelExibicao.revalidate();
    }//GEN-LAST:event_exibeComunidadesMouseClicked

    private void exibeAmigosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exibeAmigosMouseExited
        // TODO add your handling code here:
        Color padrao=new Color(21,30,51);
        exibeAmigos.setBackground(padrao);
    }//GEN-LAST:event_exibeAmigosMouseExited

    private void exibeAmigosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exibeAmigosMouseEntered
        exibeAmigos.setOpaque(true);
        exibeAmigos.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_exibeAmigosMouseEntered

    private void exibeAmigosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exibeAmigosMouseClicked
        // TODO add your handling code here:
        List<Integer> amiguinhos=new ArrayList<Integer>();
        for(Usuario ID:Dados.getAmigos(idUsuario)){
            amiguinhos.add(ID.getIdUsuario());
        }
        PainelExibicao.removeAll();
        for(Integer idUSER:amiguinhos){
            view.IconUser icone=new view.IconUser(idUSER);
            PainelExibicao.add(icone);icone.show(true);
        }
        PainelExibicao.updateUI();PainelExibicao.revalidate();
    }//GEN-LAST:event_exibeAmigosMouseClicked

    private void jButtonNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNomeActionPerformed

    private void jLabelItensMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelItensMouseReleased
        this.jLabelItens.setText(Integer.toString(usuario.getQuantidadeItensColecoes()));
    }//GEN-LAST:event_jLabelItensMouseReleased

    private void colecoesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colecoesMouseExited
        Color padrao=new Color(21,30,51);
        colecoes.setBackground(padrao);
    }//GEN-LAST:event_colecoesMouseExited

    private void colecoesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colecoesMouseEntered
        colecoes.setOpaque(true);
        colecoes.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_colecoesMouseEntered

    private void colecoesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_colecoesMouseClicked
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        Colecoes collection=new Colecoes();
        this.jDesktopConteudoPerfil.add(collection);
        collection.setVisible(true);
        try {collection.setMaximum(true);
        } catch (PropertyVetoException ex) {  }        
    }//GEN-LAST:event_colecoesMouseClicked

    private void jButtonJogoTrunfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonJogoTrunfoActionPerformed
        listarJogos();
        listarUsuarios();
        if(idUserLog!=null){//RemoveAll - remove todos os componentes de dentro do DesktopFrame
            jDesktopConteudoPerfil.removeAll();
            //Repaint - faz a atualização do conteúdo(componentes) de dentro do DesktopFrame
            jDesktopConteudoPerfil.repaint();
            container = new JInternalFrame("Super Trunfo");
            ((BasicInternalFrameUI)container.getUI()).setNorthPane(null);
            container.setPreferredSize(new Dimension(800,500));
            container.setBounds(0,0,800,500);
            container.add(this.jPanelJogo);
            container.setBorder(null);//retirar bordas
            this.jPanelJogo.setVisible(true);
            container.setVisible(true);
            jDesktopConteudoPerfil.add(container);
            jDesktopConteudoPerfil.updateUI();
        }

    }//GEN-LAST:event_jButtonJogoTrunfoActionPerformed

    private void jButtonJogoTrunfoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJogoTrunfoMouseExited
        Color padrao=new Color(21,30,51);
        jButtonJogoTrunfo.setBackground(padrao);
    }//GEN-LAST:event_jButtonJogoTrunfoMouseExited

    private void jButtonJogoTrunfoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonJogoTrunfoMouseEntered
        jButtonJogoTrunfo.setOpaque(true);
        jButtonJogoTrunfo.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jButtonJogoTrunfoMouseEntered

    private void jButtonAdicionarAmigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmigoActionPerformed
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameEditarPerfil jIFrameEditarPerfil=new JIFrameEditarPerfil(Principal.getIdUserLogando());
        jIFrameEditarPerfil.idUserLogando=Principal.getIdUserLogando();
        if(Principal.getIdUserLogando()!=idUsuario){
            jIFrameEditarPerfil.NoEdit();
        }
        jDesktopConteudoPerfil.add(jIFrameEditarPerfil);
        jIFrameEditarPerfil.setVisible(true);
        try {jIFrameEditarPerfil.setMaximum(true);
        } catch (PropertyVetoException ex) {  }
    }//GEN-LAST:event_jButtonAdicionarAmigoActionPerformed

    private void jButtonAdicionarAmigoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmigoMouseExited
        // TODO add your handling code here:
        Color padrao=new Color(21,30,51);
        jButtonAdicionarAmigo.setBackground(padrao);
    }//GEN-LAST:event_jButtonAdicionarAmigoMouseExited

    private void jButtonAdicionarAmigoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonAdicionarAmigoMouseEntered
        jButtonAdicionarAmigo.setOpaque(true);
        jButtonAdicionarAmigo.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jButtonAdicionarAmigoMouseEntered

    private void jButtonRecadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRecadoActionPerformed
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameRecado jIFrameRecado = new JIFrameRecado(idUsuario);
        jIFrameRecado.idUserLogando=Principal.getIdUserLogando();
        jDesktopConteudoPerfil.add(jIFrameRecado);
        jIFrameRecado.setVisible(true);
        try {jIFrameRecado.setMaximum(true);
        } catch (PropertyVetoException ex) {  }

    }//GEN-LAST:event_jButtonRecadoActionPerformed

    private void jButtonRecadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRecadoMouseExited
        // TODO add your handling code here:
        Color padrao=new Color(21,30,51);
        jButtonRecado.setBackground(padrao);
    }//GEN-LAST:event_jButtonRecadoMouseExited

    private void jButtonRecadoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonRecadoMouseEntered
        jButtonRecado.setOpaque(true);
        jButtonRecado.setBackground(Color.DARK_GRAY);
    }//GEN-LAST:event_jButtonRecadoMouseEntered

    private void jLabelFotoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseExited
        if(Dados.getUsuariosBD().get(idUsuario).getFoto()==null){           
            ImageIcon img=new ImageIcon(Principal.class.getResource("/Images/default-user.png"));
            jLabelFoto.setIcon(new ImageIcon(img.getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH)));
        }
    }//GEN-LAST:event_jLabelFotoMouseExited

    private void jLabelFotoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseEntered
        if(Dados.getUsuariosBD().get(idUsuario).getFoto()==null){
            ImageIcon img=new ImageIcon(Principal.class.getResource("/Images/default_user_Editar.png"));
            jLabelFoto.setIcon(new ImageIcon(img.getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH)));
        }
    }//GEN-LAST:event_jLabelFotoMouseEntered

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        if(Principal.getIdUserLogando()==idUsuario){
            String caminho;
            JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
            File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
            arquivo.setCurrentDirectory(diretorio);
            arquivo.showOpenDialog(null);
            //        jLabelFoto.setSize(234,202);
            caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
            Image img=new ImageIcon(caminho).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH);
            jLabelFoto.setIcon(new ImageIcon(img));
            if(Principal.getIdUserLogando()==idUsuario){
                Dados.getUsuariosBD().get(Principal.getIdUserLogando()).setFoto(img);
            }
        }
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void ExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseExited
        // TODO add your handling code here:
        if(Principal.getIdUserLogando()==idUsuario){
            Color padrao=new Color(153,0,0);
            Excluir.setBackground(padrao);
        }
    }//GEN-LAST:event_ExcluirMouseExited

    private void ExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseEntered
        // TODO add your handling code here:
        if(Principal.getIdUserLogando()==idUsuario){
            Color padrao=new Color(204,0,0);
            Excluir.setBackground(padrao);
        }
    }//GEN-LAST:event_ExcluirMouseEntered

    private void ExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExcluirMouseClicked
        // TODO add your handling code here:
        String op;
        op = this.jComboBoxColecao.getSelectedItem().toString();
        String opItem;
        opItem = this.jComboBoxItem.getSelectedItem().toString();
        System.out.println(""+opItem);
        if(null != op)switch (op) {
            case "Moeda":
            for (Moeda moeda : Dados.getColecaoMoeda(idUserLogando)) {
                if(opItem.equals(moeda.getNomeM())){
                    Atividade atividade=new Atividade(moeda.getIdItem(),4, idUserLogando, 2, "Excluiu o item "+moeda.getNomeM(),"(MOEDA)");
                    JOptionPane.showMessageDialog(this, "Camiseta"+moeda.getNomeM()+" excluída");
                    atividade.salvar();
                    atividade.bloquearAtividades(idUserLogando);
                    Dados.getMoedasBD().get(moeda.getIdItem()).setIdUsuario(0);

                }
            }
            break;
            case "Camiseta":
            for (Camiseta camiseta : Dados.getColecaoCamiseta(idUserLogando)) {
                if(opItem.equals(camiseta.getNome())){
                    Atividade atividade=new Atividade(camiseta.getIdItem(),1, idUserLogando, 2, "Excluiu o item "+camiseta.getNome(),"(CAMISETA)");
                    JOptionPane.showMessageDialog(this, "Camiseta "+camiseta.getNome()+" excluída");
                    atividade.salvar();
                    atividade.bloquearAtividades(idUserLogando);
                    Dados.getCamisetasBD().get(camiseta.getIdItem()).setIdUsuario(0);
                }
            }
            break;
            case "Cartão":
            for (Cartao cartao : Dados.getColecaoCartao(idUserLogando)) {
                if(opItem.equals(cartao.getNome())){
                    Atividade atividade=new Atividade(cartao.getIdItem(),2, idUserLogando, 2, "Excluiu o item "+cartao.getNome(),"(CARTÃO)");
                    JOptionPane.showMessageDialog(this, "Cartão "+cartao.getNome()+" excluída");
                    atividade.salvar();
                    atividade.bloquearAtividades(idUserLogando);
                    Dados.getCartoesBD().get(cartao.getIdItem()).setIdUsuario(0);
                    cartao.setIdUsuario(0);
                }
            }
            break;
            case "Jogo":
            for (Jogo jogo : Dados.getColecaoJogo(idUserLogando)) {
                if(opItem.equals(jogo.getNome())){
                    Atividade atividade=new Atividade(jogo.getIdItem(),3, idUserLogando, 2, "Excluiu o item "+jogo.getNome(),"(JOGO)");
                    JOptionPane.showMessageDialog(this, "Jogo "+jogo.getNome()+" excluída");
                    atividade.salvar();
                    atividade.bloquearAtividades(idUserLogando);
                    Dados.getCartoesBD().get(jogo.getIdItem()).setIdUsuario(0);
                    jogo.setIdUsuario(0);
                }
            }
            break;
            case "Quadrinho":
            for (Quadrinho quadrinho : Dados.getColecaoQuadrinho(idUserLogando)) {
                if(opItem.equals(quadrinho.getTitulo())){
                    Atividade atividade=new Atividade(quadrinho.getIdItem(),5, idUserLogando, 2, "Excluiu o item "+quadrinho.getTitulo(),"(QUADRINHO)");
                    JOptionPane.showMessageDialog(this, "Quadrinho "+quadrinho.getTitulo()+" excluída");
                    atividade.salvar();
                    atividade.bloquearAtividades(idUserLogando);
                    Dados.getQuadrinhosBD().get(quadrinho.getIdItem()).setIdUsuario(0);
                    quadrinho.setIdUsuario(0);
                }
            }
            break;
            case "HotWheels":
            for (hWheels hotWheels : Dados.getColecaohWheels(idUserLogando)) {
                if(opItem.equals(hotWheels.getNome())){
                    Atividade atividade=new Atividade(hotWheels.getIdItem(),6, idUserLogando, 2, "Excluiu o item "+hotWheels.getNome(),"(HOT WHEELS)");
                    JOptionPane.showMessageDialog(this, "Hot Wheels "+hotWheels+" excluída");
                    atividade.salvar();
                    atividade.bloquearAtividades(idUserLogando);
                    Dados.getHotWheelsBD().get(hotWheels.getIdItem()).setIdUsuario(0);
                    hotWheels.setIdUsuario(0);
                }
            }
            break;
            default:
            JOptionPane.showMessageDialog(this, "Escolha uma Coleção");
            break;
        }
    }//GEN-LAST:event_ExcluirMouseClicked

    private void ADDItemMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDItemMouseExited
        // TODO add your handling code here:
        if(Principal.getIdUserLogando()==idUsuario){
            Color padrao=new Color(0,102,0);
            ADDItem.setBackground(padrao);
        }
    }//GEN-LAST:event_ADDItemMouseExited

    private void ADDItemMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDItemMouseEntered
        // TODO add your handling code here:
        if(Principal.getIdUserLogando()==idUsuario){
            Color padrao=new Color(0,153,0);
            ADDItem.setBackground(padrao);
        }
    }//GEN-LAST:event_ADDItemMouseEntered

    private void ADDItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDItemMouseClicked
        if(Principal.getIdUserLogando()==idUsuario){
            String op;
            op = this.jComboBoxColecao.getSelectedItem().toString();
            System.out.println(""+op);
            if(null != op)switch (op) {
                case "Moeda":
                JIFrameMoeda moeda=new JIFrameMoeda();
                ExibeItemColecao O=new ExibeItemColecao(moeda);

                break;
                case "Cartão":
                JIFrameCartao jIFrameCartao = new JIFrameCartao();
                e=new ExibeItemColecao(jIFrameCartao);
                break;
                case "HotWheels":
                JIFramehWheels hwheels=new JIFramehWheels();
                e=new ExibeItemColecao(hwheels);
                break;
                case "Jogo":
                JIFrameJogo jogo=new JIFrameJogo();
                e=new ExibeItemColecao(jogo);
                break;
                case "Camiseta":
                JIFrameCamiseta jIFrameCamiseta = new JIFrameCamiseta();
                e=new ExibeItemColecao(jIFrameCamiseta);
                break;
                case "Quadrinho":
                JIFrameQuadrinho quadrinho=new JIFrameQuadrinho();
                e=new ExibeItemColecao(quadrinho);
                break;
                default:
                JOptionPane.showMessageDialog(this, "Escolha uma Coleção");
                break;
            }
        }
    }//GEN-LAST:event_ADDItemMouseClicked

    private void jComboBoxColecaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxColecaoActionPerformed
        String op;
        op = this.jComboBoxColecao.getSelectedItem().toString();
        System.out.println(""+op);

        if(null != op)switch (op) {
            case "Moeda":
            if(usuario.getColecaoMoeda().size()!=0){this.jComboBoxItem.setEnabled(true);}
            this.jComboBoxItem.removeAllItems();
            Iterator<Moeda> itMoeda = Dados.getColecaoMoeda(idUserLogando).iterator();
            while(itMoeda.hasNext()){
                Moeda e = itMoeda.next();
                String nomesitens = e.getNomeM();
                this.jComboBoxItem.addItem(nomesitens);
            }     break;

            case "Camiseta":
            if(usuario.getColecaoCamiseta().size()!=0){this.jComboBoxItem.setEnabled(true);}
            this.jComboBoxItem.removeAllItems();
            Iterator<Camiseta> itCamiseta = Dados.getColecaoCamiseta(idUserLogando).iterator();
            while(itCamiseta.hasNext()){
                Camiseta e = itCamiseta.next();
                String nomesitens = e.getNome();
                this.jComboBoxItem.addItem(nomesitens);
            }     break;

            case "Cartão":
            if(usuario.getColecaoCartao().size()!=0){this.jComboBoxItem.setEnabled(true);}
            this.jComboBoxItem.removeAllItems();
            Iterator<Cartao> itCartao = Dados.getColecaoCartao(idUserLogando).iterator();
            while(itCartao.hasNext()){
                Cartao e = itCartao.next();
                String nomesitens = e.getNome();
                this.jComboBoxItem.addItem(nomesitens);
            }     break;

            case "Jogo":
            if(usuario.getColecaoJogo().size()!=0){this.jComboBoxItem.setEnabled(true);}
            this.jComboBoxItem.removeAllItems();
            Iterator<Jogo> itJogo = Dados.getColecaoJogo(idUserLogando).iterator();
            while(itJogo.hasNext()){
                Jogo e = itJogo.next();
                String nomesitens = e.getNome();
                this.jComboBoxItem.addItem(nomesitens);
            }     break;
            case "Quadrinho":
            if(usuario.getColecaoQuadrinho().size()!=0){this.jComboBoxItem.setEnabled(true);}
            this.jComboBoxItem.removeAllItems();
            Iterator<Quadrinho> itQuadrinho = Dados.getColecaoQuadrinho(idUserLogando).iterator();
            while(itQuadrinho.hasNext()){
                Quadrinho e = itQuadrinho.next();
                String nomesitens = e.getTitulo();
                this.jComboBoxItem.addItem(nomesitens);
            }     break;

            case "HotWheels":
            if(usuario.getColecaohWheels().size()!=0){this.jComboBoxItem.setEnabled(true);}
            this.jComboBoxItem.removeAllItems();
            Iterator<hWheels> ithWheels = Dados.getColecaohWheels(idUserLogando).iterator();
            while(ithWheels.hasNext()){
                hWheels e = ithWheels.next();
                String nomesitens = e.getNome();
                this.jComboBoxItem.addItem(nomesitens);
            }     break;
            default:
            JOptionPane.showMessageDialog(this, "Escolha uma Coleção");
            break;
        }
    }//GEN-LAST:event_jComboBoxColecaoActionPerformed

    private void ADDAmigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDAmigoMouseClicked
       this.ADDAmigo.setText("Solicitação enviada");
        Dados.getUsuariosBD().get(Principal.getIdUserLogando()).addAmigo(idUsuario);
    }//GEN-LAST:event_ADDAmigoMouseClicked

    private void ADDAmigoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDAmigoMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDAmigoMouseEntered

    private void ADDAmigoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ADDAmigoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ADDAmigoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ADDAmigo;
    private javax.swing.JLabel ADDItem;
    private javax.swing.JLabel Excluir;
    private javax.swing.JPanel PainelExibicao;
    private javax.swing.JLabel colecoes;
    private javax.swing.JLabel exibeAmigos;
    private javax.swing.JLabel exibeComunidades;
    private javax.swing.JButton jButtonAdicionarAmigo;
    private javax.swing.JButton jButtonConvidarJogo;
    private javax.swing.JButton jButtonJogar;
    private javax.swing.JButton jButtonJogoTrunfo;
    private javax.swing.JButton jButtonNome;
    private javax.swing.JButton jButtonRecado;
    private javax.swing.JComboBox jComboBoxColecao;
    private javax.swing.JComboBox jComboBoxColecaoJogo;
    private javax.swing.JComboBox jComboBoxItem;
    private static javax.swing.JPanel jDesktopConteudoPerfil;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private static javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelInteresse1;
    private javax.swing.JLabel jLabelInteresse2;
    private javax.swing.JLabel jLabelInteresseC;
    private javax.swing.JLabel jLabelItens;
    private javax.swing.JLabel jLabelNumeroColecoes;
    private javax.swing.JLabel jLabelPublicidade;
    private javax.swing.JLabel jLabelRank;
    private static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private ProgramaColecionadores.JPanelAtividadeRede jPanelAtividadeRede2;
    private javax.swing.JPanel jPanelDetalhes;
    private javax.swing.JPanel jPanelJogo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jtbListarCliente;
    private javax.swing.JTable jtbListarJogos;
    private javax.swing.JLabel pais;
    // End of variables declaration//GEN-END:variables
     private void listarUsuarios() {

        DefaultTableModel dtm = (DefaultTableModel) jtbListarCliente.getModel();
        dtm.setNumRows(0);

        for(Jogador jogador:Jogador.jogadores.values()) {
            if(jogador.getIdJogador()!=idUserLogando){
            dtm.addRow(new Object[]{jogador.getIdJogador(),
                        Dados.getUsuariosBD().get(jogador.getIdJogador()).getNome(),
                        });
            System.out.println(jogador.getIdJogador());
        }}
    }
    private void listarJogos() {

        DefaultTableModel dtm = (DefaultTableModel) jtbListarJogos.getModel();
        dtm.setNumRows(0);

        for (Trunfo jogo : Trunfo.getJogos().values()) {//percorre a lista de usuarios
            if(jogo.getPlayer1().getIdJogador()==this.idUserLogando||jogo.getPlayer2().getIdJogador()==this.idUserLogando){
                dtm.addRow(new Object[]{jogo.getIdJogo(),
                        jogo.getPlayer1().getNome(),
                        jogo.getPontos1(),
                        jogo.getPlayer2().getNome(),
                        jogo.getPontos2(),
                        jogo.getIdTipoCarta()
                }); 
            }
        }
    }
    
    public static void botaoCamisetas(){
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameListarCamiseta jIFrameListarCamiseta = new JIFrameListarCamiseta(idUsuario);
        jIFrameListarCamiseta.idUserLogando=Principal.getIdUserLogando();
        jDesktopConteudoPerfil.add(jIFrameListarCamiseta);
        jIFrameListarCamiseta.setVisible(true);
        try {jIFrameListarCamiseta.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
//        jButtonCamiseta.setText("");
//        jButtonCamiseta.setText("Coleção de Camisetas "+"["+usuario.getColecaoCamiseta().size()+"]");
//        jLabelItens.setText(Integer.toString(usuario.getQuantidadeItensColecoes()));
    }
    public static void botaoCartoes(){
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameListarCartao jIFrameListarCartao = new JIFrameListarCartao(idUsuario);
        jIFrameListarCartao.idUserLogando=Principal.getIdUserLogando();
        jIFrameListarCartao.setVisible(true);
        jDesktopConteudoPerfil.add(jIFrameListarCartao);
        try {jIFrameListarCartao.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
    }
    public static void botaoMoedas(){
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameListarMoeda jIFrameListarMoeda = new JIFrameListarMoeda (idUsuario);
        jIFrameListarMoeda.idUserLogando=Principal.getIdUserLogando();
        jIFrameListarMoeda.setVisible(true);
        jDesktopConteudoPerfil.add(jIFrameListarMoeda);
        try {jIFrameListarMoeda.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
    }
    public static void botaoComics(){
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameListarQuadrinho jIFrameListarQuadrinho = new JIFrameListarQuadrinho (idUsuario);
        jIFrameListarQuadrinho.idUserLogando=Principal.getIdUserLogando();
        jIFrameListarQuadrinho.setVisible(true);
        jDesktopConteudoPerfil.add(jIFrameListarQuadrinho);
        try {jIFrameListarQuadrinho.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
    }
    public static void botaoJogos(){
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameListarJogo jIFrameListarJogo = new JIFrameListarJogo (idUsuario);
        jIFrameListarJogo.idUserLogando=Principal.getIdUserLogando();
        jIFrameListarJogo.setVisible(true);
        jDesktopConteudoPerfil.add(jIFrameListarJogo);
        try {jIFrameListarJogo.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
    }
    public static void botaohWheels(){
        jDesktopConteudoPerfil.removeAll();
        jDesktopConteudoPerfil.repaint();
        JIFrameListarhWheels jIFrameListarhWheels = new JIFrameListarhWheels (idUsuario);
        jIFrameListarhWheels.idUserLogando=Principal.getIdUserLogando();
        jIFrameListarhWheels.setVisible(true);
        jDesktopConteudoPerfil.add(jIFrameListarhWheels);
        try {jIFrameListarhWheels.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
    }
}