package ProgramaColecionadores;

import Jogo.Cartas;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tábata Gianelli
 */
public class JIFramehWheels extends javax.swing.JInternalFrame {
    hWheels hwheels;
    int idUserLogando=Principal.getIdUserLogando();
    Atividade atividade;
    private Atividade atividadeEditar;
    private boolean visitante;
    private Image img;
    /**
     * Creates new form JIFramehWheels
     */
    public JIFramehWheels() {
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas
        this.hwheels = new hWheels();
        this.Editar.setVisible(false);
        this.Salvar.setVisible(false);
        this.visitante = false;
        solicitarTroca.setEnabled(true);
        Trocar.setVisible(false);
        Iterator<String> cor = Dados.getCores().iterator();
            while(cor.hasNext()){
                String nomesitens = cor.next();
                
                this.jComboBoxCor.addItem(nomesitens);
        }
    }
    public JIFramehWheels(hWheels hwheels){
        this.idUserLogando=Principal.getIdUserLogando();
        this.visitante = Principal.getIdUserLogando()!=hwheels.getIdUsuario();
        this.hwheels=hwheels;
        initComponents();
        Iterator<String> cor = Dados.getCores().iterator();
            while(cor.hasNext()){
                String nomesitens = cor.next();
                
                this.jComboBoxCor.addItem(nomesitens);
        }
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas 
        
        this.CadastrarHW.setVisible(false);
        if(visitante){ this.Editar.setVisible(false);}
        if(Principal.getIdUserLogando()==hwheels.getIdUsuario()){
            this.Trocar.setVisible(false);
        }
        //dentro da classe hWheels
        this.jTextFieldNome.setText(hwheels.getNome());
        this.jComboBoxCor.setSelectedIndex(hwheels.o1.getIdCor());
        this.jTextFieldTamanho.setText(hwheels.o1.getTamanho());
        this.jTextFieldModelo.setText(hwheels.o1.getModelo());
        this.jTextFieldCensura.setText(hwheels.getCensura());
        this.jComboBoxMaterial.setSelectedItem(hwheels.getMaterial());
        //dentro da classe item
        if(hwheels.getFoto()!=null){ 
        jLabelFoto.setSize(221,199);
        jLabelFoto.setIcon(new ImageIcon(hwheels.getFoto().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT)));}
        this.jTextFieldEdicao.setText(hwheels.getEdicao());
        this.jComboBoxEstado.setSelectedItem(hwheels.getEstadoPreservacao());
        this.jTextFieldDescricao.setText(hwheels.getDescricao());
        this.jTextFieldFabricacao.setText(hwheels.getFabricacao());
        this.jTextFieldAquisicao.setText(hwheels.getAquisicao());
        this.jTextFieldVFabricacao1.setText(hwheels.getVFabricacao());        
        this.jTextFieldVAquisicao1.setText(hwheels.getVAquisicao());    
        this.jComboBoxPrivacidade.setSelectedIndex(hwheels.getPrivacidade());
        //desativa edicao
        //dentro da classe hWheels
        this.jComboBoxPrivacidade.setEnabled(false);
        this.jTextFieldNome.setEditable(false);
        this.jComboBoxCor.setEnabled(false);
        this.jTextFieldTamanho.setEditable(false);
        this.jTextFieldModelo.setEditable(false);
        this.jTextFieldCensura.setEditable(false);
        this.jComboBoxMaterial.setEnabled(false);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(false);
        this.jComboBoxEstado.setEnabled(false);
        this.jTextFieldDescricao.setEditable(false);
        this.jTextFieldFabricacao.setEditable(false);
        this.jTextFieldAquisicao.setEditable(false);
        this.jTextFieldVFabricacao1.setEditable(false);
        this.jTextFieldVAquisicao1.setEditable(false);
        this.Salvar.setVisible(false);//oculta o botão salvar
         if(idUserLogando==hwheels.getIdUsuario()){ this.Trocar.setVisible(false); }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTroca = new javax.swing.JPanel();
        solicitarTroca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbListarhWheels = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldTamanho = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldCensura = new javax.swing.JTextField();
        jComboBoxMaterial = new javax.swing.JComboBox();
        jTextFieldModelo = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextFieldEdicao = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldAquisicao = new javax.swing.JFormattedTextField();
        jTextFieldFabricacao = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldDescricao = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldVFabricacao1 = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldVAquisicao1 = new javax.swing.JFormattedTextField();
        jComboBoxPrivacidade = new javax.swing.JComboBox();
        jComboBoxCor = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Trocar = new javax.swing.JLabel();
        Salvar = new javax.swing.JLabel();
        CadastrarHW = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        solicitarTroca.setBackground(new java.awt.Color(21, 30, 51));
        solicitarTroca.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        solicitarTroca.setForeground(java.awt.SystemColor.control);
        solicitarTroca.setText("Solicitar Troca");
        solicitarTroca.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        solicitarTroca.setContentAreaFilled(false);
        solicitarTroca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitarTroca.setOpaque(true);
        solicitarTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseExited(evt);
            }
        });
        solicitarTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarTrocaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha um item seu para oferecer na troca");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 3));

        jtbListarhWheels.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtbListarhWheels.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Modelo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbListarhWheels.setMaximumSize(new java.awt.Dimension(225, 0));
        jScrollPane2.setViewportView(jtbListarhWheels);

        javax.swing.GroupLayout jPanelTrocaLayout = new javax.swing.GroupLayout(jPanelTroca);
        jPanelTroca.setLayout(jPanelTrocaLayout);
        jPanelTrocaLayout.setHorizontalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanelTrocaLayout.createSequentialGroup()
                .addGap(138, 138, 138)
                .addComponent(solicitarTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTrocaLayout.setVerticalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solicitarTroca)
                .addGap(16, 16, 16))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(null);
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 5));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nome");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 45, 219, 21));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Material");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 45, 226, 21));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Cor");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 328, 219, 21));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Faixa etária");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 215, 219, 21));

        jTextFieldNome.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 72, 219, 21));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Tamanho");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 104, 219, 21));

        jTextFieldTamanho.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldTamanho.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTamanhoActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldTamanho, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 129, 219, 21));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Foto do HotWheels");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 161, 221, 21));

        jTextFieldCensura.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldCensura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCensuraActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldCensura, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 242, 219, 21));

        jComboBoxMaterial.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxMaterial.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxMaterial.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Metal", "Plástico", "Outro" }));
        jComboBoxMaterial.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaterialActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxMaterial, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 72, 226, 21));

        jTextFieldModelo.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldModeloActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldModelo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 188, 219, 21));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Modelo");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 161, 219, 21));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Data de fabricação");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 45, 113, 21));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Data de aquisição");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 45, -1, 21));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Valor (Fabricação)");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 104, 113, 21));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Valor (Aquisição)");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 104, 102, 21));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Edição");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 274, 219, 21));

        jTextFieldEdicao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdicaoActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 301, 219, 21));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Estado de preservação");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 161, 226, 21));

        jComboBoxEstado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Usado", "Precário" }));
        jComboBoxEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 188, 226, 21));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Descrição");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 215, 226, 21));

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enari - imagem(item).png"))); // NOI18N
        jLabelFoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51)));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 188, 221, 188));

        try {
            jTextFieldAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldAquisicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAquisicao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPanel8.add(jTextFieldAquisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 72, 102, 21));

        try {
            jTextFieldFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFabricacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFabricacao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPanel8.add(jTextFieldFabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 72, 113, 21));

        jTextFieldDescricao.setColumns(20);
        jTextFieldDescricao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextFieldDescricao.setLineWrap(true);
        jTextFieldDescricao.setRows(4);
        jTextFieldDescricao.setWrapStyleWord(true);
        jTextFieldDescricao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jScrollPane1.setViewportView(jTextFieldDescricao);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 242, -1, 134));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("R$");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(492, 129, -1, 21));

        jTextFieldVFabricacao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVFabricacao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVFabricacao1.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPanel8.add(jTextFieldVFabricacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(511, 129, 94, 21));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("R$");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(611, 129, -1, 21));

        jTextFieldVAquisicao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVAquisicao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVAquisicao1.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPanel8.add(jTextFieldVAquisicao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 129, 83, 21));

        jComboBoxPrivacidade.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPrivacidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPrivacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Amigos", "Privado" }));
        jComboBoxPrivacidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jComboBoxPrivacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 129, 226, 21));

        jComboBoxCor.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxCor.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxCor.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxCorActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxCor, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 355, 219, 21));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Privacidade");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(248, 104, 226, 21));

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 30, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de HotWheels");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 698, -1));

        Voltar.setBackground(new java.awt.Color(21, 30, 51));
        Voltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voltar.setText("Cadastrados");
        Voltar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.setOpaque(true);
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });
        jPanel8.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 397, 93, 21));

        Editar.setBackground(new java.awt.Color(21, 30, 51));
        Editar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("Editar");
        Editar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.setOpaque(true);
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        jPanel8.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 397, 53, 21));

        Trocar.setBackground(new java.awt.Color(21, 30, 51));
        Trocar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Trocar.setForeground(new java.awt.Color(255, 255, 255));
        Trocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trocar.setText("Trocar");
        Trocar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Trocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trocar.setOpaque(true);
        Trocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrocarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrocarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrocarMouseExited(evt);
            }
        });
        jPanel8.add(Trocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 397, 54, 21));

        Salvar.setBackground(new java.awt.Color(21, 30, 51));
        Salvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salvar.setText("Salvar");
        Salvar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salvar.setOpaque(true);
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalvarMouseExited(evt);
            }
        });
        jPanel8.add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 397, 59, 21));

        CadastrarHW.setBackground(new java.awt.Color(21, 30, 51));
        CadastrarHW.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CadastrarHW.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarHW.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastrarHW.setText("Cadastrar HotWheels");
        CadastrarHW.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        CadastrarHW.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarHW.setOpaque(true);
        CadastrarHW.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarHWMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarHWMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarHWMouseExited(evt);
            }
        });
        jPanel8.add(CadastrarHW, new org.netbeans.lib.awtextra.AbsoluteConstraints(558, 397, 155, 21));

        jSeparator1.setBackground(new java.awt.Color(21, 30, 51));
        jSeparator1.setForeground(new java.awt.Color(21, 30, 51));
        jSeparator1.setOpaque(true);
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 387, 698, 4));

        jPanel7.add(jPanel8, "card2");

        getContentPane().add(jPanel7, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jTextFieldTamanhoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTamanhoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTamanhoActionPerformed

    private void jTextFieldCensuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCensuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCensuraActionPerformed

    private void jComboBoxMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaterialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMaterialActionPerformed

    private void jTextFieldModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldModeloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldModeloActionPerformed

    private void jTextFieldEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdicaoActionPerformed

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        String caminho;
        JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
        File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
        arquivo.setCurrentDirectory(diretorio);
        arquivo.showOpenDialog(null);
        caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
        img = new ImageIcon(caminho).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT);//NOVO COD PARA DEFINIR TAMANHO UNICO DE IMAGENS
        jLabelFoto.setIcon(new ImageIcon(img)); //LBIMAGEM RECEBERA A IMAGEM        // TODO add your handling code here:
        if(visitante==true){} else {
            this.hwheels.setFoto(img);
        }
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void jComboBoxCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxCorActionPerformed
             if(this.jComboBoxCor.getSelectedIndex()==1){
           String novaCor=JOptionPane.showInputDialog("Qual é a Cor?").toUpperCase();
           Dados.getCores().add(novaCor);
           jComboBoxCor.removeAllItems();
           Iterator<String> cor = Dados.getCores().iterator();
            while(cor.hasNext()){
                String nomesitens = cor.next();
                
                this.jComboBoxCor.addItem(nomesitens);
            }
       }
     
    }//GEN-LAST:event_jComboBoxCorActionPerformed

    private void solicitarTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarTrocaActionPerformed
        if (jtbListarhWheels.getSelectedRow() == -1) {
        JOptionPane.showMessageDialog(this, "Nenhuma Hot Wheels selecionada.");}
        Integer idCamiseta = (Integer) jtbListarhWheels.getValueAt(jtbListarhWheels.getSelectedRow(), 0);
        Troca troca=new Troca(idUserLogando,hwheels.getIdUsuario(),6,(Item)Dados.getHotWheelsBD().get(idCamiseta),(Item)hwheels);
        solicitarTroca.setText("Troca solicitada !");
        solicitarTroca.setEnabled(false);
        solicitarTroca.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_solicitarTrocaActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        JIFrameListarhWheels jIFrameListarhWheels = new JIFrameListarhWheels(idUserLogando);
        jIFrameListarhWheels.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarhWheels);
        jIFrameListarhWheels.setVisible(true);
        try {jIFrameListarhWheels.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_VoltarMouseClicked

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        atividadeEditar=new Atividade(hwheels.getIdItem(),6, idUserLogando, 3, "Editou","HOT WHEELS");
        atividadeEditar.add((Item) Dados.getHotWheelsBD().get(atividadeEditar.getIdItem()).clone());
        atividadeEditar.salvar(); //lista de atividades em dados recebendo a atividade de alteracao
        this.Salvar.setVisible(true);//oculta o botão salvar
        //habilita a edicao dos campos
        this.jTextFieldNome.setEditable(true);
        this.jComboBoxCor.setEnabled(true);
        this.jTextFieldTamanho.setEditable(true);
        this.jTextFieldModelo.setEditable(true);
        this.jTextFieldCensura.setEditable(true);
        this.jComboBoxMaterial.setEnabled(true);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(true);
        this.jComboBoxEstado.setEnabled(true);
        this.jTextFieldDescricao.setEditable(true);
        this.jTextFieldFabricacao.setEditable(true);
        this.jTextFieldAquisicao.setEditable(true);
        this.jTextFieldVFabricacao1.setEditable(true);
        this.jTextFieldVAquisicao1.setEditable(true);
        this.jComboBoxPrivacidade.setEnabled(true);
    }//GEN-LAST:event_EditarMouseClicked

    private void TrocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseClicked
       listarhWheels();
        JOptionPane.showMessageDialog(null,jPanelTroca);
    }//GEN-LAST:event_TrocarMouseClicked

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
       hWheels novohWheels=hwheels;
        //dentro da classe hWheels
        novohWheels.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        novohWheels.setNome(this.jTextFieldNome.getText());
        novohWheels.o1.setIdCor(this.jComboBoxCor.getSelectedIndex());
        novohWheels.o1.setTamanho(this.jTextFieldTamanho.getText());
        novohWheels.o1.setModelo(this.jTextFieldModelo.getText());
        novohWheels.setCensura(this.jTextFieldCensura.getText());
        novohWheels.setMaterial(this.jComboBoxMaterial.getSelectedItem().toString());
        //dentro da classe item
        novohWheels.setEdicao(this.jTextFieldEdicao.getText());
        novohWheels.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        novohWheels.setDescricao(this.jTextFieldDescricao.getText());
        novohWheels.setFabricacao(this.jTextFieldFabricacao.getText());
        novohWheels.setAquisicao(this.jTextFieldAquisicao.getText());
        novohWheels.setVFabricacao(jTextFieldVFabricacao1.getText());
        novohWheels.setVAquisicao(jTextFieldVAquisicao1.getText());
        novohWheels.setFoto(img);
        //armazena o ID do item
        Dados.getHotWheelsBD().get(atividadeEditar.getIdItem()).equals(novohWheels);
        atividadeEditar.lstItem.add(novohWheels);
        atividadeEditar.bloquearAtividades(idUserLogando);
        JIFrameListarhWheels jIFrameListarhWheels = new JIFrameListarhWheels(idUserLogando);
        jIFrameListarhWheels.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarhWheels);
        jIFrameListarhWheels.setVisible(true);
        try {jIFrameListarhWheels.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_SalvarMouseClicked

    private void CadastrarHWMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarHWMouseClicked
        addHWheels();
    }//GEN-LAST:event_CadastrarHWMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        Voltar.setOpaque(true);
        Voltar.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        Color padrao=new Color(21,30,51);
        Voltar.setBackground(padrao);
    }//GEN-LAST:event_VoltarMouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setOpaque(true);
        Editar.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Color padrao=new Color(21,30,51);
        Editar.setBackground(padrao);
    }//GEN-LAST:event_EditarMouseExited

    private void TrocarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseEntered
        Trocar.setOpaque(true);
        Trocar.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_TrocarMouseEntered

    private void TrocarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseExited
        Color padrao=new Color(21,30,51);
        Trocar.setBackground(padrao);
    }//GEN-LAST:event_TrocarMouseExited

    private void SalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseEntered
        Salvar.setOpaque(true);
        Salvar.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_SalvarMouseEntered

    private void SalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseExited
        Color padrao=new Color(21,30,51);
        Salvar.setBackground(padrao);
    }//GEN-LAST:event_SalvarMouseExited

    private void CadastrarHWMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarHWMouseEntered
        CadastrarHW.setOpaque(true);
        CadastrarHW.setBackground(Color.DARK_GRAY);   
    }//GEN-LAST:event_CadastrarHWMouseEntered

    private void CadastrarHWMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarHWMouseExited
        Color padrao=new Color(21,30,51);
        CadastrarHW.setBackground(padrao);
    }//GEN-LAST:event_CadastrarHWMouseExited

    private void solicitarTrocaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseEntered
        // TODO add your handling code here:
        if(solicitarTroca.isEnabled()==true){
        solicitarTroca.setOpaque(true);
        solicitarTroca.setBackground(Color.DARK_GRAY);   
        }
    }//GEN-LAST:event_solicitarTrocaMouseEntered

    private void solicitarTrocaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseExited
        Color padrao=new Color(21,30,51);
        solicitarTroca.setBackground(padrao);
    }//GEN-LAST:event_solicitarTrocaMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarHW;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Salvar;
    private javax.swing.JLabel Trocar;
    private javax.swing.JLabel Voltar;
    private javax.swing.JComboBox jComboBoxCor;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxMaterial;
    private javax.swing.JComboBox jComboBoxPrivacidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelTroca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jTextFieldAquisicao;
    private javax.swing.JTextField jTextFieldCensura;
    private javax.swing.JTextArea jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JFormattedTextField jTextFieldFabricacao;
    private javax.swing.JTextField jTextFieldModelo;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldTamanho;
    private javax.swing.JFormattedTextField jTextFieldVAquisicao1;
    private javax.swing.JFormattedTextField jTextFieldVFabricacao1;
    private javax.swing.JTable jtbListarhWheels;
    private javax.swing.JButton solicitarTroca;
    // End of variables declaration//GEN-END:variables
public void addHWheels(){
        String NOME = jTextFieldNome.getText();
        hWheels HWHEELS = new hWheels();
        boolean existehWheels=false;
        for (int i = 0; i < Dados.getHotWheelsBD().size(); i++) {//percorre a lista de usuarios "lst"
                HWHEELS = Dados.getHotWheelsBD().get(i);//paga o objeto da posição "i" e armazena no objeto "usuario" do tipo "Usuario"
            if (NOME.equals(HWHEELS.getNome())){jLabel8.setText("HotWheels já cadastrado");
            existehWheels=true;
            break;}
        }
            if(!existehWheels){
        //define o usuario dono da hWheels
        hwheels.setIdUsuario(idUserLogando);
        //dentro da classe hwheels
        hwheels.setNome(this.jTextFieldNome.getText());
        hwheels.o1.setModelo(this.jTextFieldModelo.getText());
        hwheels.setCensura(this.jTextFieldCensura.getText());
        hwheels.o1.setTamanho(this.jTextFieldTamanho.getText());
        hwheels.o1.setIdCor(this.jComboBoxCor.getSelectedIndex());
        hwheels.setMaterial(this.jComboBoxMaterial.getSelectedItem().toString());
        //dentro da classe item
        hwheels.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        hwheels.setFabricacao(this.jTextFieldFabricacao.getText());
        hwheels.setAquisicao(this.jTextFieldAquisicao.getText());
        hwheels.setEdicao(this.jTextFieldEdicao.getText());
        hwheels.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        hwheels.setDescricao(this.jTextFieldDescricao.getText());
        hwheels.setFoto(img);
        hwheels.salvar();
        
        int idCarta=(int) (Math.random() * Cartas.gethWheels().size()-1);
        if(idCarta<0){idCarta=0;}
        Dados.getUsuariosBD().get(idUserLogando).setCartaHotWheels(idCarta);
        
        
        //Atividade de adição do hWheels
        atividade=new Atividade(hwheels.getIdItem(),6, idUserLogando, 1, "Adicionou","HOT WHEELS");
        atividade.bloquearAtividades(idUserLogando);
        atividade.salvar();
        //cria a tela de colecoes
        JIFrameListarhWheels jIFrameListarhWheels = new JIFrameListarhWheels(idUserLogando);
        jIFrameListarhWheels.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarhWheels);
        jIFrameListarhWheels.setVisible(true);
        try {jIFrameListarhWheels.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
        this.doDefaultCloseAction();//fim atual
        Principal.atualizaInicial();
        }
        }

 private void listarhWheels(){
        DefaultTableModel dtm = (DefaultTableModel) jtbListarhWheels.getModel();
        dtm.setNumRows(0);

        for (hWheels hwheelsTable :  Dados.getUsuariosBD().get(idUserLogando).getColecaohWheels()) {
            dtm.addRow(new Object[]{hwheelsTable.getIdItem(),hwheelsTable.getNome(),
                hwheelsTable.o1.getModelo()}); 
        }
    }

}
