package ProgramaColecionadores;

import Jogo.Cartas;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tábata Gianelli
 */
public class JIFrameCartao extends javax.swing.JInternalFrame {
    Cartao cartao;
    int idUserLogando=Principal.getIdUserLogando();
    Atividade atividade;
    private Atividade atividadeEditar;
    private boolean visitante;
    private Image img;
    /**
     * Creates new form JIFrameCartao
     */
    public JIFrameCartao() {
        this.visitante=false;
        cartao = new Cartao();
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas 
        this.cartao = new Cartao();
        this.Editar.setVisible(false);
        this.Salvar.setVisible(false);
        this.visitante = false;
        solicitarTroca.setEnabled(true);
        Trocar.setVisible(false);
    }
    
    public JIFrameCartao(Cartao cartao) {
        this.idUserLogando=Principal.getIdUserLogando();
        this.visitante = idUserLogando!=cartao.getIdUsuario();
        this.cartao=cartao;
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas  
        this.CadastrarCar.setVisible(false);
        if(Principal.getIdUserLogando()!=cartao.getIdUsuario()){ this.Editar.setVisible(false);}else{
            this.Trocar.setVisible(false);
        }
        //dentro da classe cartao
        this.jTextFieldNomeC.setText(cartao.getNome());
        this.jTextFieldTemaC.setText(cartao.getTema());
        this.jTextFieldLoteC.setText(cartao.getLote());
        this.jTextFieldTiragemC.setText(cartao.getTiragem());
        this.jComboBoxOperadoraC.setSelectedItem(cartao.getOperadora());
        //dentro da classe item
        if(cartao.getFoto()!=null){ 
        jLabelFoto.setSize(220,188);
        jLabelFoto.setIcon(new ImageIcon(cartao.getFoto().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT)));}
        this.jTextFieldEdicao.setText(cartao.getEdicao());
        this.jComboBoxEstado.setSelectedItem(cartao.getEstadoPreservacao());
        this.jTextFieldDescricao.setText(cartao.getDescricao());
        this.jTextFieldFabricacao.setText(cartao.getFabricacao());
        this.jTextFieldAquisicao.setText(cartao.getAquisicao());
        this.jTextFieldVFabricacao1.setText(cartao.getVFabricacao());        
        this.jTextFieldVAquisicao1.setText(cartao.getVAquisicao());    
        this.jComboBoxPrivacidade.setSelectedIndex(cartao.getPrivacidade());
        //desativa edicao
        //dentro da classe cartao
        this.jComboBoxPrivacidade.setEnabled(false);
        this.jTextFieldNomeC.setEditable(false);
        this.jTextFieldTemaC.setEditable(false);
        this.jTextFieldLoteC.setEditable(false);
        this.jTextFieldTiragemC.setEditable(false);
        this.jComboBoxOperadoraC.setEnabled(false);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(false);
        this.jComboBoxEstado.setEnabled(false);
        this.jTextFieldDescricao.setEditable(false);
        this.jTextFieldFabricacao.setEditable(false);
        this.jTextFieldAquisicao.setEditable(false);
        this.jTextFieldVFabricacao1.setEditable(false);
        this.jTextFieldVAquisicao1.setEditable(false);
        
        this.Salvar.setVisible(false);//oculta o botão salvar
         if(idUserLogando==cartao.getIdUsuario()){ this.Trocar.setVisible(false); }
    }

    private void listarCartao() {
        DefaultTableModel dtm = (DefaultTableModel) jtbListarCartao.getModel();
        dtm.setNumRows(0);
        for (Cartao cartaoDaLista :Dados.getUsuariosBD().get(idUserLogando).getColecaoCartao()) {
            dtm.addRow(new Object[]{cartaoDaLista.getIdItem(),cartaoDaLista.getNome(),cartaoDaLista.getOperadora()});
            
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTroca = new javax.swing.JPanel();
        solicitarTroca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtbListarCartao = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldTemaC = new javax.swing.JTextField();
        jTextFieldNomeC = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldLoteC = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jComboBoxOperadoraC = new javax.swing.JComboBox();
        jTextFieldTiragemC = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextFieldEdicao = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldAquisicao = new javax.swing.JFormattedTextField();
        jTextFieldFabricacao = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldDescricao = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldVFabricacao1 = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldVAquisicao1 = new javax.swing.JFormattedTextField();
        jComboBoxPrivacidade = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Salvar = new javax.swing.JLabel();
        Trocar = new javax.swing.JLabel();
        CadastrarCar = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanelTroca.setBackground(new java.awt.Color(255, 255, 255));

        solicitarTroca.setBackground(new java.awt.Color(21, 30, 51));
        solicitarTroca.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        solicitarTroca.setForeground(java.awt.SystemColor.control);
        solicitarTroca.setText("Solicitar Troca");
        solicitarTroca.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        solicitarTroca.setContentAreaFilled(false);
        solicitarTroca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitarTroca.setOpaque(true);
        solicitarTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseExited(evt);
            }
        });
        solicitarTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarTrocaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha um item seu para oferecer na troca");

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 3));

        jtbListarCartao.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtbListarCartao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Operadora"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbListarCartao.setMaximumSize(new java.awt.Dimension(225, 0));
        jScrollPane3.setViewportView(jtbListarCartao);

        javax.swing.GroupLayout jPanelTrocaLayout = new javax.swing.GroupLayout(jPanelTroca);
        jPanelTroca.setLayout(jPanelTrocaLayout);
        jPanelTrocaLayout.setHorizontalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(solicitarTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );
        jPanelTrocaLayout.setVerticalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(solicitarTroca)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 5));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nome");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Operadora");

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Tema");

        jTextFieldTemaC.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldTemaC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTemaCActionPerformed(evt);
            }
        });

        jTextFieldNomeC.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNomeC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeCActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Lote");

        jTextFieldLoteC.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldLoteC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldLoteCActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Foto do Cartão");

        jComboBoxOperadoraC.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxOperadoraC.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxOperadoraC.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"Vivo", "Tim", "Oi", "Claro" }));
        jComboBoxOperadoraC.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxOperadoraC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxOperadoraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxOperadoraCActionPerformed(evt);
            }
        });

        jTextFieldTiragemC.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldTiragemC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTiragemCActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Tiragem");

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Data de fabricação");

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Data de aquisição");

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Valor (Aquisição)");

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Valor (Fabricação)");

        jTextFieldEdicao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdicaoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Edição");

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Estado de preservação");

        jComboBoxEstado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Usado", "Precário" }));
        jComboBoxEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxEstado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Descrição");

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enari - imagem(item).png"))); // NOI18N
        jLabelFoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 2));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
        });

        try {
            jTextFieldAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldAquisicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAquisicao.setSelectionColor(new java.awt.Color(21, 30, 51));

        try {
            jTextFieldFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFabricacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFabricacao.setSelectionColor(new java.awt.Color(21, 30, 51));

        jTextFieldDescricao.setColumns(20);
        jTextFieldDescricao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextFieldDescricao.setLineWrap(true);
        jTextFieldDescricao.setRows(5);
        jTextFieldDescricao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jScrollPane1.setViewportView(jTextFieldDescricao);

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("R$");

        jTextFieldVFabricacao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVFabricacao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVFabricacao1.setSelectionColor(new java.awt.Color(21, 30, 51));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("R$");

        jTextFieldVAquisicao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVAquisicao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVAquisicao1.setSelectionColor(new java.awt.Color(21, 30, 51));

        jComboBoxPrivacidade.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPrivacidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPrivacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Amigos", "Privado" }));
        jComboBoxPrivacidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxPrivacidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBoxPrivacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrivacidadeActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Privacidade");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 30, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Cartão");

        Voltar.setBackground(new java.awt.Color(21, 30, 51));
        Voltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voltar.setText("Cadastrados");
        Voltar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Voltar.setOpaque(true);
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });

        Editar.setBackground(new java.awt.Color(21, 30, 51));
        Editar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("Editar");
        Editar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Editar.setOpaque(true);
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });

        Salvar.setBackground(new java.awt.Color(21, 30, 51));
        Salvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salvar.setText("Salvar");
        Salvar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Salvar.setOpaque(true);
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalvarMouseExited(evt);
            }
        });

        Trocar.setBackground(new java.awt.Color(21, 30, 51));
        Trocar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Trocar.setForeground(new java.awt.Color(255, 255, 255));
        Trocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trocar.setText("Trocar");
        Trocar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Trocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trocar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Trocar.setOpaque(true);
        Trocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrocarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrocarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrocarMouseExited(evt);
            }
        });

        CadastrarCar.setBackground(new java.awt.Color(21, 30, 51));
        CadastrarCar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CadastrarCar.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarCar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastrarCar.setText("Cadastrar Cartão");
        CadastrarCar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        CadastrarCar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarCar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CadastrarCar.setOpaque(true);
        CadastrarCar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarCarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarCarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarCarMouseExited(evt);
            }
        });

        jSeparator1.setBackground(new java.awt.Color(21, 30, 51));
        jSeparator1.setForeground(new java.awt.Color(21, 30, 51));
        jSeparator1.setOpaque(true);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(Trocar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldNomeC, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jTextFieldTemaC, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jTextFieldLoteC, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jTextFieldTiragemC, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jTextFieldEdicao, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(jComboBoxOperadoraC, 0, 187, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBoxPrivacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(6, 6, 6)
                                .addComponent(jLabel19))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jTextFieldFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9)
                                .addComponent(jTextFieldAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addGap(9, 9, 9)
                                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(4, 4, 4)
                                .addComponent(jTextFieldVFabricacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldVAquisicao1))
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CadastrarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel8)
                    .addComponent(jLabel21)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19))
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jTextFieldNomeC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAquisicao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldFabricacao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel23))
                .addGap(8, 8, 8)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jComboBoxPrivacidade, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel26)
                    .addComponent(jTextFieldVFabricacao1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldVAquisicao1, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel25)
                    .addComponent(jTextFieldTemaC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel24)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jTextFieldLoteC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel17)
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldTiragemC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel22)
                                .addGap(6, 6, 6)
                                .addComponent(jTextFieldEdicao, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(6, 6, 6)
                                .addComponent(jComboBoxOperadoraC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(Trocar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Editar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Voltar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Salvar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CadastrarCar, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.add(jPanel8, "card2");

        getContentPane().add(jPanel7, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldTemaCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTemaCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTemaCActionPerformed

    private void jTextFieldNomeCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeCActionPerformed

    private void jTextFieldLoteCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldLoteCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldLoteCActionPerformed

    private void jComboBoxOperadoraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxOperadoraCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxOperadoraCActionPerformed

    private void jTextFieldTiragemCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTiragemCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTiragemCActionPerformed

    private void jTextFieldEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdicaoActionPerformed

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        String caminho;
        JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
        File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
        arquivo.setCurrentDirectory(diretorio);
        arquivo.showOpenDialog(null);
        jLabelFoto.setSize(220,188);
        caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
        img = new ImageIcon(caminho).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT);//NOVO COD PARA DEFINIR TAMANHO UNICO DE IMAGENS
        jLabelFoto.setIcon(new ImageIcon(img)); //LBIMAGEM RECEBERA A IMAGEM        // TODO add your handling code here:
        if(visitante==true){} else {
            cartao.setFoto(img.getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT));
        }
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void jComboBoxPrivacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrivacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPrivacidadeActionPerformed

    private void solicitarTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarTrocaActionPerformed
        if (jtbListarCartao.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma camiseta selecionada.");}
        Integer idCartao = (Integer) jtbListarCartao.getValueAt(jtbListarCartao.getSelectedRow(), 0);
        Troca troca=new Troca(idUserLogando,cartao.getIdUsuario(),2,(Item)Dados.getCartoesBD().get(idCartao),(Item)cartao);
        solicitarTroca.setText("Troca solicitada !");
     solicitarTroca.setEnabled(false);
     solicitarTroca.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_solicitarTrocaActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        JIFrameListarCartao jIFrameListarCartao = new JIFrameListarCartao(idUserLogando);
        jIFrameListarCartao.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarCartao);
        jIFrameListarCartao.setVisible(true);
        try {jIFrameListarCartao.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual       
    }//GEN-LAST:event_VoltarMouseClicked

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
        //dentro da classe cartao
        Cartao nCartao=cartao;
        nCartao.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        nCartao.setNome(this.jTextFieldNomeC.getText());
        nCartao.setTema(this.jTextFieldTemaC.getText());
        nCartao.setLote(this.jTextFieldLoteC.getText());
        nCartao.setTiragem(this.jTextFieldTiragemC.getText());
        nCartao.setOperadora(this.jComboBoxOperadoraC.getSelectedItem().toString());
        //dentro da classe item
        nCartao.setEdicao(this.jTextFieldEdicao.getText());
        nCartao.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        nCartao.setDescricao(this.jTextFieldDescricao.getText());
        nCartao.setFabricacao(this.jTextFieldFabricacao.getText());
        nCartao.setAquisicao(this.jTextFieldAquisicao.getText());
        nCartao.setVFabricacao(jTextFieldVFabricacao1.getText());
        nCartao.setVAquisicao(jTextFieldVAquisicao1.getText());
        nCartao.setFoto(img);
        //armazena o ID do item
        atividadeEditar.lstItem.add(nCartao);//adiciona nova versao de camiseta
        atividadeEditar.bloquearAtividades(idUserLogando);
        
        JIFrameListarCartao jIFrameListarCartao = new JIFrameListarCartao(idUserLogando);
        jIFrameListarCartao.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarCartao);
        jIFrameListarCartao.setVisible(true);
        try {jIFrameListarCartao.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual        
    }//GEN-LAST:event_SalvarMouseClicked

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        atividadeEditar=new Atividade(cartao.getIdItem(),2, idUserLogando, 3, "Editou","CARTÃO");
        atividadeEditar.add((Item) Dados.getCartoesBD().get(atividadeEditar.getIdItem()).clone());
        atividadeEditar.salvar();
        this.Salvar.setVisible(true);//oculta o botão salvar
        //habilita a edicao dos campos
        this.jTextFieldNomeC.setEditable(true);
        this.jTextFieldTemaC.setEditable(true);
        this.jTextFieldLoteC.setEditable(true);
        this.jTextFieldTiragemC.setEditable(true);
        this.jComboBoxOperadoraC.setEnabled(true);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(true);
        this.jComboBoxEstado.setEnabled(true);
        this.jTextFieldDescricao.setEditable(true);
        this.jTextFieldFabricacao.setEditable(true);
        this.jTextFieldAquisicao.setEditable(true);
        this.jTextFieldVFabricacao1.setEditable(true);
        this.jTextFieldVAquisicao1.setEditable(true);
        this.jComboBoxPrivacidade.setEnabled(true);        
    }//GEN-LAST:event_EditarMouseClicked

    private void TrocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseClicked
         listarCartao();
        JOptionPane.showMessageDialog(null,jPanelTroca);       
    }//GEN-LAST:event_TrocarMouseClicked

    private void CadastrarCarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarCarMouseClicked
        addCartao();       
    }//GEN-LAST:event_CadastrarCarMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        Voltar.setOpaque(true);
        Voltar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        Color padrao=new Color(21,30,51);
        Voltar.setBackground(padrao);
    }//GEN-LAST:event_VoltarMouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setOpaque(true);
        Editar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Color padrao=new Color(21,30,51);
        Editar.setBackground(padrao);
    }//GEN-LAST:event_EditarMouseExited

    private void TrocarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseEntered
        Trocar.setOpaque(true);
        Trocar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_TrocarMouseEntered

    private void TrocarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseExited
        Color padrao=new Color(21,30,51);
        Trocar.setBackground(padrao);
    }//GEN-LAST:event_TrocarMouseExited

    private void SalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseEntered
        Salvar.setOpaque(true);
        Salvar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_SalvarMouseEntered

    private void SalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseExited
        Color padrao=new Color(21,30,51);
        Salvar.setBackground(padrao);
    }//GEN-LAST:event_SalvarMouseExited

    private void CadastrarCarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarCarMouseEntered
        CadastrarCar.setOpaque(true);
        CadastrarCar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_CadastrarCarMouseEntered

    private void CadastrarCarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarCarMouseExited
        Color padrao=new Color(21,30,51);
        CadastrarCar.setBackground(padrao);
    }//GEN-LAST:event_CadastrarCarMouseExited

    private void solicitarTrocaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseEntered
        if(solicitarTroca.isEnabled()==true){
        solicitarTroca.setOpaque(true);
        solicitarTroca.setBackground(Color.DARK_GRAY); 
        }
    }//GEN-LAST:event_solicitarTrocaMouseEntered

    private void solicitarTrocaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseExited
        Color padrao=new Color(21,30,51);
        solicitarTroca.setBackground(padrao);
    }//GEN-LAST:event_solicitarTrocaMouseExited

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarCar;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Salvar;
    private javax.swing.JLabel Trocar;
    private javax.swing.JLabel Voltar;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxOperadoraC;
    private javax.swing.JComboBox jComboBoxPrivacidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelTroca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jTextFieldAquisicao;
    private javax.swing.JTextArea jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JFormattedTextField jTextFieldFabricacao;
    private javax.swing.JTextField jTextFieldLoteC;
    private javax.swing.JTextField jTextFieldNomeC;
    private javax.swing.JTextField jTextFieldTemaC;
    private javax.swing.JTextField jTextFieldTiragemC;
    private javax.swing.JFormattedTextField jTextFieldVAquisicao1;
    private javax.swing.JFormattedTextField jTextFieldVFabricacao1;
    private javax.swing.JTable jtbListarCartao;
    private javax.swing.JButton solicitarTroca;
    // End of variables declaration//GEN-END:variables
    public void addCartao(){
        String NOME = jTextFieldNomeC.getText();
        Cartao CARTAO = new Cartao();
        boolean existeCartao=false;
        for (int i = 0; i < Dados.getCartoesBD().size(); i++) {//percorre a lista de usuarios "lst"
                CARTAO = Dados.getCartoesBD().get(i);//paga o objeto da posição "i" e armazena no objeto "usuario" do tipo "Usuario"
            if (NOME.equals(CARTAO.getNome())){
                jLabel8.setText("Cartão já cadastrado");
                existeCartao=true;
                break;}
        }
            if(!existeCartao){
        cartao.setIdUsuario(idUserLogando);
        //dentro da classe cartao
        cartao.setNome(this.jTextFieldNomeC.getText());
        cartao.setLote(this.jTextFieldLoteC.getText());
        cartao.setTiragem(this.jTextFieldTiragemC.getText());
        cartao.setOperadora(this.jComboBoxOperadoraC.getSelectedItem().toString());
        cartao.setTema(this.jTextFieldTemaC.getText());      
        //dentro da classe item
        cartao.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        cartao.setFabricacao(this.jTextFieldFabricacao.getText());
        cartao.setAquisicao(this.jTextFieldAquisicao.getText());
        cartao.setEdicao(this.jTextFieldEdicao.getText());
        cartao.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        cartao.setDescricao(this.jTextFieldDescricao.getText());
        cartao.setVFabricacao(jTextFieldVFabricacao1.getText());        
        cartao.setVAquisicao(jTextFieldVAquisicao1.getText());   
        cartao.setFoto(img);
        //Armazenando o ID do item
        cartao.salvar();
        //Atividade de adição da camiseta
       Principal.atualizaInicial();
        
        int idCarta=(int) (Math.random() * Cartas.getCartoes().size()-1);
        if(idCarta<0){idCarta=0;}
        Dados.getUsuariosBD().get(idUserLogando).setCartaCartao(idCarta);
        
        
        atividade=new Atividade(cartao.getIdItem(),2, idUserLogando, 1, "Adicionou","CARTÃO");
        atividade.salvar(); 
        atividade.bloquearAtividades(idUserLogando);
        JIFrameListarCartao jIFrameListarCartao = new JIFrameListarCartao(idUserLogando);
        jIFrameListarCartao.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarCartao);
        jIFrameListarCartao.setVisible(true);
        try {jIFrameListarCartao.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
        this.doDefaultCloseAction();//fim atual
        }
        }
    }
