package ProgramaColecionadores;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.sql.Time;
import java.util.*;
import java.util.Timer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.plaf.basic.BasicInternalFrameUI;

/**
 *
 * @author Casa
 */
public class JIFrameCadastroUser extends javax.swing.JInternalFrame {

        Usuario usuario;
        int idUserLogando;
        private String senha,email;
        private Image img;
   
        public JIFrameCadastroUser() {
            initComponents();
             ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        //this.setBorder(null);//retirar bordas  
         
        jPasswordField04Senha01.addMouseListener(new MouseAdapter() {///apaga o texto da caixa de de senha 01  
        public void mouseClicked(MouseEvent arg0) {jPasswordField04Senha01.setText("");}
        });
       
        jPasswordField05Senha02.addMouseListener(new MouseAdapter() {///apaga o texto da caixa de de senha 01  
        public void mouseClicked(MouseEvent arg0) {jPasswordField05Senha02.setText("");}
        });  
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jTextField06Sobrenome = new javax.swing.JTextField();
        jLabelEmail = new javax.swing.JLabel();
        jTextField02Email = new javax.swing.JTextField();
        jLabelSenha1 = new javax.swing.JLabel();
        jPasswordField04Senha01 = new javax.swing.JPasswordField();
        jLabelSenha2 = new javax.swing.JLabel();
        jPasswordField05Senha02 = new javax.swing.JPasswordField();
        j07ComboBoxSexo = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextField01Nome = new javax.swing.JTextField();
        jLabelNomeUsuario = new javax.swing.JLabel();
        jTextField03NomeUsuario = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelSenha3 = new javax.swing.JLabel();
        cadastrar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UsuarioCadastrado = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(null);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(21, 30, 51));
        jLabel8.setText("Nome");

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(21, 30, 51));
        jLabel9.setText("Sobrenome");

        jTextField06Sobrenome.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTextField06Sobrenome.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextField06Sobrenome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField06SobrenomeMouseClicked(evt);
            }
        });
        jTextField06Sobrenome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField06SobrenomeActionPerformed(evt);
            }
        });

        jLabelEmail.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelEmail.setForeground(new java.awt.Color(21, 30, 51));
        jLabelEmail.setText("E-mail*");

        jTextField02Email.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTextField02Email.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextField02Email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField02EmailActionPerformed(evt);
            }
        });
        jTextField02Email.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField02EmailKeyPressed(evt);
            }
        });

        jLabelSenha1.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelSenha1.setForeground(new java.awt.Color(21, 30, 51));
        jLabelSenha1.setText("Senha*");

        jPasswordField04Senha01.setText("jPasswordField1");
        jPasswordField04Senha01.setSelectionColor(new java.awt.Color(21, 30, 51));

        jLabelSenha2.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelSenha2.setForeground(new java.awt.Color(21, 30, 51));
        jLabelSenha2.setText("Confirmar senha*");

        jPasswordField05Senha02.setText("jPasswordField1");
        jPasswordField05Senha02.setSelectionColor(new java.awt.Color(21, 30, 51));

        j07ComboBoxSexo.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        j07ComboBoxSexo.setForeground(new java.awt.Color(21, 30, 51));
        j07ComboBoxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));
        j07ComboBoxSexo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        j07ComboBoxSexo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(21, 30, 51));
        jLabel13.setText("Sexo");

        jTextField01Nome.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTextField01Nome.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextField01Nome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField01NomeMouseClicked(evt);
            }
        });
        jTextField01Nome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField01NomeActionPerformed(evt);
            }
        });

        jLabelNomeUsuario.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabelNomeUsuario.setForeground(new java.awt.Color(21, 30, 51));
        jLabelNomeUsuario.setText("Nome usuário*");

        jTextField03NomeUsuario.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jTextField03NomeUsuario.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextField03NomeUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField03NomeUsuarioMouseClicked(evt);
            }
        });
        jTextField03NomeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField03NomeUsuarioActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(21, 30, 51));
        jLabel15.setText("Foto de perfil");

        jLabelFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/default-user.png"))); // NOI18N
        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204), 2));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
        });

        jLabelSenha3.setFont(new java.awt.Font("Verdana", 0, 9)); // NOI18N
        jLabelSenha3.setForeground(new java.awt.Color(102, 102, 102));
        jLabelSenha3.setText("*Campos obrigatórios");

        cadastrar.setBackground(new java.awt.Color(21, 30, 51));
        cadastrar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        cadastrar.setForeground(new java.awt.Color(255, 255, 255));
        cadastrar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        cadastrar.setText("CADASTRAR");
        cadastrar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        cadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cadastrar.setOpaque(true);
        cadastrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cadastrarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cadastrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cadastrarMouseExited(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 30, 51));
        jLabel2.setText("Cadastro");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(21, 30, 51)));

        UsuarioCadastrado.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        UsuarioCadastrado.setForeground(new java.awt.Color(102, 102, 102));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(UsuarioCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField01Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField06Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jPasswordField04Senha01, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelSenha1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jPasswordField05Senha02, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(j07ComboBoxSexo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelSenha3)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField02Email, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelNomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextField03NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cadastrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabelFoto)))))
                .addGap(0, 0, 0))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField01Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField06Sobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabelNomeUsuario)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField03NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel8Layout.createSequentialGroup()
                                .addComponent(jLabelEmail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField02Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(16, 16, 16)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSenha2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSenha1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jPasswordField05Senha02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPasswordField04Senha01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(j07ComboBoxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelSenha3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jLabelFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                        .addComponent(UsuarioCadastrado, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField06SobrenomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField06SobrenomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField06SobrenomeActionPerformed

    private void jTextField02EmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField02EmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField02EmailActionPerformed

    private void jTextField01NomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField01NomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField01NomeActionPerformed

    private void jTextField03NomeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField03NomeUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField03NomeUsuarioActionPerformed

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        String caminho;
        JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
        File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
        arquivo.setCurrentDirectory(diretorio);
        arquivo.showOpenDialog(null);
        caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
        img=new ImageIcon(caminho).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_SMOOTH);                    
        jLabelFoto.setIcon(new ImageIcon(img)); //LBIMAGEM RECEBERA A IMAGEM        // TODO add your handling code here:
        img=new ImageIcon(caminho).getImage().getScaledInstance(240, 202, Image.SCALE_SMOOTH);     
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void cadastrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseClicked
        // TODO add your handling code here:
                //verifica email já existente
        String porcaria = jTextField02Email.getText();
        Usuario viadinho=new Usuario();
        int noia=0;
        for (int i = 0; i < Dados.getUsuariosBD().size(); i++) {//percorre a lista de usuarios "lst"
                viadinho= Dados.getUsuariosBD().get(i);//paga o objeto da posição "i" e armazena no objeto "usuario" do tipo "Usuario" 
            if (porcaria.equals(viadinho.getEmail())){noia++;}else{noia=0;}    
        }       
        if ("".equals(jTextField03NomeUsuario.getText())){              //verifica se o usuario não digitou o nome de usuario
            jLabelNomeUsuario.setText("Insira o Nome de Usuario");//exibe mensagem para inserir o nome
        }else if ("".equals(jTextField02Email.getText()) || noia>0){                //verifica se o usuario não digitou o email
            jLabelEmail.setText("Email inválido ou já cadastrado!");                         //exibe mensagem para inserir o email
        }else{
            senha = Arrays.toString(jPasswordField04Senha01.getPassword()); //captura senha na caixa1 e converte em string para armazenar em "senha"
            String  senha2 = Arrays.toString(jPasswordField05Senha02.getPassword()); //captura senha na caixa2 e converte em string para armazenar em "senha2"
            if (senha.equals(senha2)) //compara senha com senha2
            {//se igual cadastra
                
                System.out.println("Cadastrado!");
                senha = new String(jPasswordField04Senha01.getPassword());
                Usuario nUsuario = new Usuario();
                nUsuario.setNome(this.jTextField01Nome.getText());
                nUsuario.setSobrenome(this.jTextField06Sobrenome.getText());
                nUsuario.setSexo(this.j07ComboBoxSexo.getSelectedItem().toString());
                nUsuario.setEmail(this.jTextField02Email.getText());
                nUsuario.setNomeUsuario(this.jTextField03NomeUsuario.getText());
                nUsuario.setSenha(senha);
                nUsuario.setFoto(img);
                nUsuario.salvar();
                Atividade atividade=new Atividade();
                atividade.setIdUsuario(Dados.getNextIdUsuario()-1);
                jLabelNomeUsuario.setText("Nome usuário*");
                jLabelEmail.setText("E-mail*");
                jLabelSenha2.setText("Confirmar senha*");
                atividade.nomeObjeto="NA REDE.";
                atividade.tipoAcao="CADASTROU-SE ";
                atividade.salvar();
                Dados.idPrimeiroLog=nUsuario.getIdUsuario();
                this.jTextField01Nome.setText("");
                this.jTextField02Email.setText("");
                this.jTextField03NomeUsuario.setText("");
                this.jTextField06Sobrenome.setText("");
                this.jPasswordField04Senha01.setText("");
                this.jPasswordField05Senha02.setText("");
                                 
                img=null;
                System.out.println("\nLista de Cadastros\n");
                for (int i = 1; i < Dados.getUsuariosBD().size(); i++) {
                    usuario= Dados.getUsuariosBD().get(i);
                    System.out.println("Cadastro número: " + i);
                    System.out.println("\tNome: " + usuario.getNome());
                    System.out.println("\tSobrenome: " + usuario.getSobrenome());
                    System.out.println("\tUsuario: " + usuario.getNomeUsuario());
                    System.out.println("\tEmail: " + usuario.getEmail());
                }
                System.out.println("\nFim da lista\n");
                
                this.UsuarioCadastrado.setText("Usuário Cadastrado!");
                this.jLabelFoto.setIcon(new ImageIcon(getClass().getResource("/Images/default-user.png")));
            }else{
                jLabelSenha2.setText("Senhas não coincidem");
            }
        }
    }//GEN-LAST:event_cadastrarMouseClicked

    private void jTextField01NomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField01NomeMouseClicked
        // TODO add your handling code here:
        this.UsuarioCadastrado.setText("");
    }//GEN-LAST:event_jTextField01NomeMouseClicked

    private void jTextField06SobrenomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField06SobrenomeMouseClicked
        // TODO add your handling code here:
        this.UsuarioCadastrado.setText("");
    }//GEN-LAST:event_jTextField06SobrenomeMouseClicked

    private void jTextField02EmailKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField02EmailKeyPressed
        // TODO add your handling code here:
        this.UsuarioCadastrado.setText("");
    }//GEN-LAST:event_jTextField02EmailKeyPressed

    private void jTextField03NomeUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField03NomeUsuarioMouseClicked
        // TODO add your handling code here:
        this.UsuarioCadastrado.setText("");
    }//GEN-LAST:event_jTextField03NomeUsuarioMouseClicked

    private void cadastrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseEntered
        cadastrar.setOpaque(true);
        cadastrar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_cadastrarMouseEntered

    private void cadastrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cadastrarMouseExited
        Color padrao=new Color(21,30,51);
        cadastrar.setBackground(padrao);
    }//GEN-LAST:event_cadastrarMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsuarioCadastrado;
    private javax.swing.JLabel cadastrar;
    private javax.swing.JComboBox j07ComboBoxSexo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelEmail;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JLabel jLabelNomeUsuario;
    private javax.swing.JLabel jLabelSenha1;
    private javax.swing.JLabel jLabelSenha2;
    private javax.swing.JLabel jLabelSenha3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPasswordField jPasswordField04Senha01;
    private javax.swing.JPasswordField jPasswordField05Senha02;
    private javax.swing.JTextField jTextField01Nome;
    private javax.swing.JTextField jTextField02Email;
    private javax.swing.JTextField jTextField03NomeUsuario;
    private javax.swing.JTextField jTextField06Sobrenome;
    // End of variables declaration//GEN-END:variables
}