package ProgramaColecionadores;

import Jogo.Cartas;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tábata Gianelli
 */
public class JIFrameQuadrinho extends javax.swing.JInternalFrame {
    Quadrinho quadrinho;
    int idUserLogando=Principal.getIdUserLogando();
    Atividade atividade;
    private Atividade atividadeEditar;
    private boolean visitante;
    private Image img;
    /**
     * Creates new form JIFrameQuadrinho
     */
    public JIFrameQuadrinho() {
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas 
        this.quadrinho = new Quadrinho();
        this.Editar.setVisible(false);
        this.Salvar.setVisible(false);
        this.visitante = false;
        solicitarTroca.setEnabled(true);
        Trocar.setVisible(false);
    }
    public JIFrameQuadrinho(Quadrinho quadrinho){
        this.idUserLogando=Principal.getIdUserLogando();
        if(idUserLogando!=quadrinho.getIdUsuario()){
        this.visitante=true;}else{this.visitante=false;}
        this.quadrinho=quadrinho;
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas  
        this.CadastrarQu.setVisible(false);
        if(visitante){ this.Editar.setVisible(false);}
        if(Principal.getIdUserLogando()==quadrinho.getIdUsuario()){
            this.Trocar.setVisible(false);
        }
        //dentro da classe Quadrinho
        this.jTextFieldTitulo.setText(quadrinho.getTitulo());
        this.jTextFieldProdutora.setText(quadrinho.o1.getProdutora());
        this.jTextFieldCensura.setText(quadrinho.o1.getCensura());
        this.jTextFieldSinopse.setText(quadrinho.o1.getSinopse());
        this.jComboBoxIdioma.setSelectedItem(quadrinho.o1.getIdioma().toString());
        this.jComboBoxGenero.setSelectedItem(quadrinho.o1.getGenero().toString());
        //dentro da classe item
        if(quadrinho.getFoto()!=null){ 
        jLabelFoto.setSize(225,188);
        jLabelFoto.setIcon(new ImageIcon(quadrinho.getFoto().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT)));}
        this.jTextFieldEdicao.setText(quadrinho.getEdicao());
        this.jComboBoxEstado.setSelectedItem(quadrinho.getEstadoPreservacao());
        this.jTextFieldDescricao.setText(quadrinho.getDescricao());
        this.jTextFieldFabricacao.setText(quadrinho.getFabricacao());
        this.jTextFieldAquisicao.setText(quadrinho.getAquisicao());
        this.jTextFieldVFabricacao1.setText(quadrinho.getVFabricacao());        
        this.jTextFieldVAquisicao1.setText(quadrinho.getVAquisicao());    
        //desativa edicao
        //dentro da classe Quadrinho
        this.jTextFieldTitulo.setEditable(false);
        this.jTextFieldProdutora.setEditable(false);
        this.jTextFieldCensura.setEditable(false);
        this.jTextFieldSinopse.setEditable(false);
        this.jComboBoxIdioma.setEnabled(false);
        this.jComboBoxGenero.setEnabled(false);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(false);
        this.jComboBoxEstado.setEnabled(false);
        this.jTextFieldDescricao.setEditable(false);
        this.jTextFieldFabricacao.setEditable(false);
        this.jTextFieldAquisicao.setEditable(false);
        this.jTextFieldVFabricacao1.setEditable(false);
        this.jTextFieldVAquisicao1.setEditable(false);
        this.jComboBoxPrivacidade.setEnabled(false);
        this.Salvar.setVisible(false);//oculta o botão salvar
         if(idUserLogando==quadrinho.getIdUsuario()){ this.Trocar.setVisible(false); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTroca = new javax.swing.JPanel();
        solicitarTroca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtbListarQuadrinho = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldProdutora = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldCensura = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jComboBoxIdioma = new javax.swing.JComboBox();
        jComboBoxGenero = new javax.swing.JComboBox();
        jLabelFoto = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jTextFieldEdicao = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldAquisicao = new javax.swing.JFormattedTextField();
        jTextFieldFabricacao = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldDescricao = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextFieldSinopse = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldVFabricacao1 = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldVAquisicao1 = new javax.swing.JFormattedTextField();
        jComboBoxPrivacidade = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        Trocar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Salvar = new javax.swing.JLabel();
        CadastrarQu = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanelTroca.setBackground(new java.awt.Color(255, 255, 255));

        solicitarTroca.setBackground(new java.awt.Color(21, 30, 51));
        solicitarTroca.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        solicitarTroca.setForeground(java.awt.SystemColor.control);
        solicitarTroca.setText("Solicitar Troca");
        solicitarTroca.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        solicitarTroca.setContentAreaFilled(false);
        solicitarTroca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitarTroca.setOpaque(true);
        solicitarTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseExited(evt);
            }
        });
        solicitarTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarTrocaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha um item seu para oferecer na troca");

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 3));

        jtbListarQuadrinho.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtbListarQuadrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Título", "Edição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbListarQuadrinho.setMaximumSize(new java.awt.Dimension(225, 0));
        jScrollPane4.setViewportView(jtbListarQuadrinho);

        javax.swing.GroupLayout jPanelTrocaLayout = new javax.swing.GroupLayout(jPanelTroca);
        jPanelTroca.setLayout(jPanelTrocaLayout);
        jPanelTrocaLayout.setHorizontalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(solicitarTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(135, 135, 135))
            .addGroup(jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 458, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanelTrocaLayout.setVerticalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 372, Short.MAX_VALUE)
                .addComponent(solicitarTroca)
                .addContainerGap())
            .addGroup(jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelTrocaLayout.createSequentialGroup()
                    .addGap(46, 46, 46)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(48, Short.MAX_VALUE)))
        );

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 5));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Titulo");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 51, 206, 21));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Gênero");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 51, 203, 21));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Produtora");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 106, 206, 21));

        jTextFieldProdutora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldProdutoraActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldProdutora, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 134, 206, 21));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Sinopse");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 217, 205, 21));

        jTextFieldTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTituloActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 78, 206, 21));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Faixa etária");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 162, 72, 21));

        jTextFieldCensura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCensuraActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldCensura, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 190, 72, 21));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Foto do quadrinho");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 162, 107, 21));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Idioma");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 164, 112, 16));

        jComboBoxIdioma.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxIdioma.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxIdioma.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Inglês", "Chinês Mandarim", "Espanhol", "Português", "Russo", "Francês", "Alemão", "Japonês", "Italiano", "Tailandês", "Polonês" }));
        jComboBoxIdioma.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jComboBoxIdioma, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 190, 112, 21));

        jComboBoxGenero.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxGenero.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxGenero.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Ação", "Aventura", "Manga" }));
        jComboBoxGenero.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxGenero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxGeneroActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 78, 226, 21));

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enari - imagem(item).png"))); // NOI18N
        jLabelFoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51)));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.setPreferredSize(null);
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 189, 220, 188));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Data de aquisição");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 51, 106, 21));

        jTextFieldEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdicaoActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 244, 226, 21));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Valor (Aquisição)");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(617, 106, 100, 21));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Edição");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 217, 226, 21));

        jComboBoxEstado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Usado", "Precário" }));
        jComboBoxEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 190, 226, 21));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Descrição");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 271, -1, 21));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Data de fabricação");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 51, -1, 21));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Valor (Fabricação)");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 106, 110, 21));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Estado de preservação");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(255, 162, 141, 21));

        try {
            jTextFieldAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldAquisicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextFieldAquisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 78, 104, 21));

        try {
            jTextFieldFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFabricacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextFieldFabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 78, 100, 21));

        jTextFieldDescricao.setColumns(20);
        jTextFieldDescricao.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextFieldDescricao.setLineWrap(true);
        jTextFieldDescricao.setRows(3);
        jTextFieldDescricao.setWrapStyleWord(true);
        jScrollPane1.setViewportView(jTextFieldDescricao);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 298, -1, 79));

        jTextFieldSinopse.setColumns(20);
        jTextFieldSinopse.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        jTextFieldSinopse.setLineWrap(true);
        jTextFieldSinopse.setRows(3);
        jTextFieldSinopse.setWrapStyleWord(true);
        jScrollPane2.setViewportView(jTextFieldSinopse);

        jPanel8.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 244, 206, 133));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("R$");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 134, -1, 21));

        jTextFieldVFabricacao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVFabricacao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel8.add(jTextFieldVFabricacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 134, 86, 21));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("R$");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(616, 134, -1, 21));

        jTextFieldVAquisicao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVAquisicao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jPanel8.add(jTextFieldVAquisicao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(635, 134, 82, 21));

        jComboBoxPrivacidade.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPrivacidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPrivacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Amigos", "Privado" }));
        jComboBoxPrivacidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxPrivacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrivacidadeActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxPrivacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 134, 226, 21));

        jLabel2.setBackground(new java.awt.Color(21, 30, 51));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 30, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Quadrinho");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 16, 704, -1));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Privacidade");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(253, 106, -1, 21));

        Voltar.setBackground(new java.awt.Color(21, 30, 51));
        Voltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voltar.setText("Cadastrados");
        Voltar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.setOpaque(true);
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });
        jPanel8.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 403, 93, 20));

        Trocar.setBackground(new java.awt.Color(21, 30, 51));
        Trocar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Trocar.setForeground(new java.awt.Color(255, 255, 255));
        Trocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trocar.setText("Trocar");
        Trocar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Trocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trocar.setOpaque(true);
        Trocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrocarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrocarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrocarMouseExited(evt);
            }
        });
        jPanel8.add(Trocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 403, 56, 20));

        Editar.setBackground(new java.awt.Color(21, 30, 51));
        Editar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("Editar");
        Editar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.setOpaque(true);
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        jPanel8.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 403, 53, 20));

        Salvar.setBackground(new java.awt.Color(21, 30, 51));
        Salvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salvar.setText("Salvar");
        Salvar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salvar.setOpaque(true);
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalvarMouseExited(evt);
            }
        });
        jPanel8.add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 403, 60, 20));

        CadastrarQu.setBackground(new java.awt.Color(21, 30, 51));
        CadastrarQu.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CadastrarQu.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarQu.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastrarQu.setText("Cadastrar quadrinho");
        CadastrarQu.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        CadastrarQu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarQu.setOpaque(true);
        CadastrarQu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarQuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarQuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarQuMouseExited(evt);
            }
        });
        jPanel8.add(CadastrarQu, new org.netbeans.lib.awtextra.AbsoluteConstraints(569, 403, 150, 20));

        jSeparator1.setBackground(new java.awt.Color(21, 30, 51));
        jSeparator1.setForeground(new java.awt.Color(21, 30, 51));
        jSeparator1.setOpaque(true);
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 388, 704, 4));

        jPanel7.add(jPanel8, "card2");

        getContentPane().add(jPanel7, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldProdutoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldProdutoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldProdutoraActionPerformed

    private void jTextFieldTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTituloActionPerformed

    private void jTextFieldCensuraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCensuraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCensuraActionPerformed

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        String caminho;
        JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
        File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
        arquivo.setCurrentDirectory(diretorio);
        arquivo.showOpenDialog(null);
        caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
        jLabelFoto.setSize(225,188);
        img = new ImageIcon(caminho).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT);//NOVO COD PARA DEFINIR TAMANHO UNICO DE IMAGENS
        jLabelFoto.setIcon(new ImageIcon(img)); //LBIMAGEM RECEBERA A IMAGEM        // TODO add your handling code here:
        if(visitante==true){} else {
            quadrinho.setFoto(img.getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT));
        }
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void jTextFieldEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdicaoActionPerformed

    private void solicitarTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarTrocaActionPerformed
        if (jtbListarQuadrinho.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhum quadrinho selecionado.");}
        Integer idQuadrinho = (Integer) jtbListarQuadrinho.getValueAt(jtbListarQuadrinho.getSelectedRow(), 0);
        Troca troca=new Troca(idUserLogando,quadrinho.getIdUsuario(),5,(Item)Dados.getQuadrinhosBD().get(idQuadrinho),(Item)quadrinho);
        solicitarTroca.setText("Troca solicitada !");
        solicitarTroca.setEnabled(false);
        solicitarTroca.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_solicitarTrocaActionPerformed

    private void jComboBoxGeneroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxGeneroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxGeneroActionPerformed

    private void jComboBoxPrivacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrivacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPrivacidadeActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        JIFrameListarQuadrinho jIFrameListarQuadrinho = new JIFrameListarQuadrinho(idUserLogando);
        jIFrameListarQuadrinho.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarQuadrinho);
        jIFrameListarQuadrinho.setVisible(true);
        try {jIFrameListarQuadrinho.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_VoltarMouseClicked

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        atividadeEditar=new Atividade(quadrinho.getIdItem(),5, idUserLogando, 3, "Editou","QUADRINHO");
        atividadeEditar.add((Item) Dados.getQuadrinhosBD().get(atividadeEditar.getIdItem()).clone());
        atividadeEditar.salvar();
        this.Salvar.setVisible(true);//oculta o botão salvar
        //habilita a edicao dos campos
        this.jTextFieldTitulo.setEditable(true);
        this.jTextFieldProdutora.setEditable(true);
        this.jTextFieldCensura.setEditable(true);
        this.jTextFieldSinopse.setEditable(true);
        this.jComboBoxIdioma.setEnabled(true);
        this.jComboBoxGenero.setEnabled(true);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(true);
        this.jComboBoxEstado.setEnabled(true);
        this.jTextFieldDescricao.setEditable(true);
        this.jTextFieldFabricacao.setEditable(true);
        this.jTextFieldAquisicao.setEditable(true);
        this.jTextFieldVFabricacao1.setEditable(true);
        this.jTextFieldVAquisicao1.setEditable(true);
        this.jComboBoxPrivacidade.setEnabled(true);
    }//GEN-LAST:event_EditarMouseClicked

    private void TrocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseClicked
        listarQuadrinho();
        JOptionPane.showMessageDialog(null,jPanelTroca);
    }//GEN-LAST:event_TrocarMouseClicked

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
        Quadrinho novoQuadrinho=quadrinho;
        //dentro da classe quadrinho
        novoQuadrinho.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        novoQuadrinho.setTitulo(this.jTextFieldTitulo.getText());
        novoQuadrinho.o1.setProdutora(this.jTextFieldProdutora.getText());
        novoQuadrinho.o1.setCensura(this.jTextFieldCensura.getText());
        novoQuadrinho.o1.setSinopse(this.jTextFieldSinopse.getText());
        novoQuadrinho.o1.setGenero(this.jComboBoxGenero.getSelectedItem().toString());
        novoQuadrinho.o1.setIdioma(this.jComboBoxIdioma.getSelectedItem().toString());
        //dentro da classe item
        novoQuadrinho.setEdicao(this.jTextFieldEdicao.getText());
        novoQuadrinho.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        novoQuadrinho.setDescricao(this.jTextFieldDescricao.getText());
        novoQuadrinho.setFabricacao(this.jTextFieldFabricacao.getText());
        novoQuadrinho.setAquisicao(this.jTextFieldAquisicao.getText());
        novoQuadrinho.setVFabricacao(jTextFieldVFabricacao1.getText());
        novoQuadrinho.setVAquisicao(jTextFieldVAquisicao1.getText());
        novoQuadrinho.setFoto(img);
        atividadeEditar.add((Item) novoQuadrinho.clone());

        Dados.getQuadrinhosBD().get(atividadeEditar.getIdItem()).equals(novoQuadrinho);
        atividadeEditar.salvar();
        atividadeEditar.bloquearAtividades(idUserLogando);
        JIFrameListarQuadrinho jIFrameListarQuadrinho = new JIFrameListarQuadrinho(idUserLogando);
        jIFrameListarQuadrinho.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarQuadrinho);
        jIFrameListarQuadrinho.setVisible(true);
        try {jIFrameListarQuadrinho.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_SalvarMouseClicked

    private void CadastrarQuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarQuMouseClicked
       addQuadrinho();
    }//GEN-LAST:event_CadastrarQuMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        Voltar.setOpaque(true);
        Voltar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        Color padrao=new Color(21,30,51);
        Voltar.setBackground(padrao);
    }//GEN-LAST:event_VoltarMouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setOpaque(true);
        Editar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Color padrao=new Color(21,30,51);
        Editar.setBackground(padrao);
    }//GEN-LAST:event_EditarMouseExited

    private void TrocarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseEntered
        Trocar.setOpaque(true);
        Trocar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_TrocarMouseEntered

    private void TrocarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseExited
        Color padrao=new Color(21,30,51);
        Trocar.setBackground(padrao);
    }//GEN-LAST:event_TrocarMouseExited

    private void SalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseEntered
        Salvar.setOpaque(true);
        Salvar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_SalvarMouseEntered

    private void SalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseExited
        Color padrao=new Color(21,30,51);
        Salvar.setBackground(padrao);
    }//GEN-LAST:event_SalvarMouseExited

    private void CadastrarQuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarQuMouseEntered
        CadastrarQu.setOpaque(true);
        CadastrarQu.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_CadastrarQuMouseEntered

    private void CadastrarQuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarQuMouseExited
        Color padrao=new Color(21,30,51);
        CadastrarQu.setBackground(padrao);
    }//GEN-LAST:event_CadastrarQuMouseExited

    private void solicitarTrocaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseEntered
        if(solicitarTroca.isEnabled()==true){
        solicitarTroca.setOpaque(true);
        solicitarTroca.setBackground(Color.DARK_GRAY); 
        }
    }//GEN-LAST:event_solicitarTrocaMouseEntered

    private void solicitarTrocaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseExited
        Color padrao=new Color(21,30,51);
        solicitarTroca.setBackground(padrao);
    }//GEN-LAST:event_solicitarTrocaMouseExited

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarQu;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Salvar;
    private javax.swing.JLabel Trocar;
    private javax.swing.JLabel Voltar;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxGenero;
    private javax.swing.JComboBox jComboBoxIdioma;
    private javax.swing.JComboBox jComboBoxPrivacidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelTroca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jTextFieldAquisicao;
    private javax.swing.JTextField jTextFieldCensura;
    private javax.swing.JTextArea jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JFormattedTextField jTextFieldFabricacao;
    private javax.swing.JTextField jTextFieldProdutora;
    private javax.swing.JTextArea jTextFieldSinopse;
    private javax.swing.JTextField jTextFieldTitulo;
    private javax.swing.JFormattedTextField jTextFieldVAquisicao1;
    private javax.swing.JFormattedTextField jTextFieldVFabricacao1;
    private javax.swing.JTable jtbListarQuadrinho;
    private javax.swing.JButton solicitarTroca;
    // End of variables declaration//GEN-END:variables
public void addQuadrinho(){
        String NOME = jTextFieldTitulo.getText();
        Quadrinho QUADRINHO = new Quadrinho();
        boolean existeQuadrinho=false;
        for (int i = 0; i < Dados.getQuadrinhosBD().size(); i++) {//percorre a lista de usuarios "lst"
                QUADRINHO = Dados.getQuadrinhosBD().get(i);//paga o objeto da posição "i" e armazena no objeto "usuario" do tipo "Usuario"
            if (NOME.equals(QUADRINHO.getTitulo())){jLabel8.setText("Quadrinho já cadastrado");
            existeQuadrinho=true;
            break;}
        }
            if(!existeQuadrinho){

        //define o usuario dono da moeda
        quadrinho.setIdUsuario(idUserLogando);
        //dentro da classe quadrinho
        quadrinho.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        quadrinho.setTitulo(this.jTextFieldTitulo.getText());
        quadrinho.o1.setProdutora(this.jTextFieldProdutora.getText());
        quadrinho.o1.setCensura(this.jTextFieldCensura.getText());
        quadrinho.o1.setIdioma(this.jComboBoxIdioma.getSelectedItem().toString());
        quadrinho.o1.setSinopse(this.jTextFieldSinopse.getText());      
        quadrinho.o1.setGenero(this.jComboBoxGenero.getSelectedItem().toString());      
        //dentro da classe item
        
        quadrinho.setFabricacao(this.jTextFieldFabricacao.getText());
        quadrinho.setAquisicao(this.jTextFieldAquisicao.getText());
        quadrinho.setEdicao(this.jTextFieldEdicao.getText());
        quadrinho.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        quadrinho.setDescricao(this.jTextFieldDescricao.getText());
        quadrinho.setVFabricacao(jTextFieldVFabricacao1.getText());        
        quadrinho.setVAquisicao(jTextFieldVAquisicao1.getText());
        quadrinho.setFoto(img);
        //Armazenando o ID do item
        quadrinho.salvar();
        
        
        int idCarta=(int) (Math.random() * Cartas.getQuadrinhos().size()-1);
        if(idCarta<0){idCarta=0;}
        Dados.getUsuariosBD().get(idUserLogando).setCartaQuadrinho(idCarta);
        
        
        //Atividade de adição do quadrinho
        atividade=new Atividade(quadrinho.getIdItem(),5, idUserLogando, 1, "Adicionou","QUADRINHO");
        atividade.bloquearAtividades(idUserLogando);
        atividade.salvar();
        //cria a tela de colecoes
        JIFrameListarQuadrinho jIFrameListarQuadrinho = new JIFrameListarQuadrinho(idUserLogando);
        jIFrameListarQuadrinho.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarQuadrinho);
        jIFrameListarQuadrinho.setVisible(true);
        try {jIFrameListarQuadrinho.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
        this.doDefaultCloseAction();//fim atual
        Principal.atualizaInicial();
        }
        }
private void listarQuadrinho(){
        DefaultTableModel dtm = (DefaultTableModel) jtbListarQuadrinho.getModel();
        dtm.setNumRows(0);

        for (Quadrinho quadrinhoTable :Dados.getUsuariosBD().get(idUserLogando).getColecaoQuadrinho()) {
        dtm.addRow(new Object[]{quadrinhoTable.getIdItem(),
            quadrinhoTable.getTitulo(), quadrinhoTable.getEdicao()});
            
        }
    }
    }
