package ProgramaColecionadores;

import Jogo.Cartas;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import java.util.Iterator;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Tábata Gianelli
 */
public class JIFrameMoeda extends javax.swing.JInternalFrame {
    Moeda moeda;
    public int idUserLogando=Principal.getIdUserLogando();
    Atividade atividade;
    private Atividade atividadeEditar;
    private boolean visitante;
    private Image img;
    /**
     * Creates new form JIFrameMoeda
     */
    public JIFrameMoeda() {
        initComponents();
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas 
        this.moeda = new Moeda();
        this.Editar.setVisible(false);
        this.Salvar.setVisible(false);
        this.visitante = false;
        solicitarTroca.setEnabled(true);
        Trocar.setVisible(false);
        Iterator<String> material = Dados.getMaterial().iterator();
            while(material.hasNext()){
                String nomesitens = material.next();
                this.jComboBoxMaterialM.addItem(nomesitens);
            }
    }
    public JIFrameMoeda(Moeda moeda){
        this.idUserLogando=Principal.getIdUserLogando();
        this.visitante = idUserLogando!=moeda.getIdUsuario();
        this.moeda=moeda;
        initComponents();
        Iterator<String> material = Dados.getMaterial().iterator();
            while(material.hasNext()){
                String nomesitens = material.next();
                
                this.jComboBoxMaterialM.addItem(nomesitens);
        }
        ((BasicInternalFrameUI)this.getUI()).setNorthPane(null); //retirar o painel superior  
        this.setBorder(null);//retirar bordas  
        this.CadastrarMo.setVisible(false);
        if(visitante){ this.Editar.setVisible(false);}
        if(Principal.getIdUserLogando()==moeda.getIdUsuario()){
            this.Trocar.setVisible(false);
        }
        //dentro da classe moeda
        this.jTextFieldNomeM.setText(moeda.getNomeM());
        this.jTextFieldPesoM.setText(moeda.getPesoM());
        this.jTextFieldDiametroM.setText(moeda.getDiametroM());
        this.jTextFieldEspessuraM.setText(moeda.getEspessuraM());
        this.jTextFieldMetodoCunhagemM.setText(moeda.getMetodoCunhagemM());
        this.jComboBoxMaterialM.setSelectedIndex(moeda.getIdMaterial());
        this.jComboBoxCoresM.setSelectedItem(moeda.getCoresM().toString());
        this.jComboBoxBordasM.setSelectedItem(moeda.getBordaM().toString());
        //dentro da classe item
        if(moeda.getFoto()!=null){ 
        jLabelFoto.setSize(220,188);
        jLabelFoto.setIcon(new ImageIcon(moeda.getFoto().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT)));}
        this.jTextFieldEdicao.setText(moeda.getEdicao());
        this.jComboBoxEstado.setSelectedItem(moeda.getEstadoPreservacao());
        this.jTextFieldDescricao.setText(moeda.getDescricao());
        this.jTextFieldFabricacao.setText(moeda.getFabricacao());
        this.jTextFieldAquisicao.setText(moeda.getAquisicao());
        this.jTextFieldVFabricacao1.setText(moeda.getVFabricacao());        
        this.jTextFieldVAquisicao1.setText(moeda.getVAquisicao());    
        this.jComboBoxPrivacidade.setSelectedIndex(moeda.getPrivacidade());
        //desativa edicao
        //dentro da classe jogo
        this.jComboBoxPrivacidade.setEnabled(false);
        this.jTextFieldNomeM.setEditable(false);
        this.jTextFieldPesoM.setEditable(false);
        this.jTextFieldDiametroM.setEditable(false);
        this.jTextFieldEspessuraM.setEditable(false);
        this.jTextFieldMetodoCunhagemM.setEditable(false);
        this.jComboBoxMaterialM.setEnabled(false);
        this.jComboBoxCoresM.setEnabled(false);
        this.jComboBoxBordasM.setEnabled(false);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(false);
        this.jComboBoxEstado.setEnabled(false);
        this.jTextFieldDescricao.setEditable(false);
        this.jTextFieldFabricacao.setEditable(false);
        this.jTextFieldAquisicao.setEditable(false);
        this.jTextFieldVFabricacao1.setEditable(false);
        this.jTextFieldVAquisicao1.setEditable(false);
        this.Salvar.setVisible(false);//oculta o botão salvar
         if(idUserLogando==moeda.getIdUsuario()){ this.Trocar.setVisible(false); }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelTroca = new javax.swing.JPanel();
        solicitarTroca = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbListarMoeda = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldPesoM = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jComboBoxCoresM = new javax.swing.JComboBox();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldNomeM = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldDiametroM = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldEspessuraM = new javax.swing.JTextField();
        jComboBoxMaterialM = new javax.swing.JComboBox();
        jComboBoxBordasM = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldMetodoCunhagemM = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jComboBoxEstado = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jTextFieldEdicao = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabelFoto = new javax.swing.JLabel();
        jTextFieldAquisicao = new javax.swing.JFormattedTextField();
        jTextFieldFabricacao = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextFieldDescricao = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        jTextFieldVFabricacao1 = new javax.swing.JFormattedTextField();
        jLabel25 = new javax.swing.JLabel();
        jTextFieldVAquisicao1 = new javax.swing.JFormattedTextField();
        jComboBoxPrivacidade = new javax.swing.JComboBox();
        jLabel24 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Voltar = new javax.swing.JLabel();
        Editar = new javax.swing.JLabel();
        Trocar = new javax.swing.JLabel();
        Salvar = new javax.swing.JLabel();
        CadastrarMo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        jPanelTroca.setBackground(new java.awt.Color(255, 255, 255));

        solicitarTroca.setBackground(new java.awt.Color(21, 30, 51));
        solicitarTroca.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        solicitarTroca.setForeground(java.awt.SystemColor.control);
        solicitarTroca.setText("Solicitar Troca");
        solicitarTroca.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        solicitarTroca.setContentAreaFilled(false);
        solicitarTroca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        solicitarTroca.setOpaque(true);
        solicitarTroca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                solicitarTrocaMouseExited(evt);
            }
        });
        solicitarTroca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solicitarTrocaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Escolha um item seu para oferecer na troca");

        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 3));

        jtbListarMoeda.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jtbListarMoeda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Edição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbListarMoeda.setMaximumSize(new java.awt.Dimension(225, 0));
        jScrollPane2.setViewportView(jtbListarMoeda);

        javax.swing.GroupLayout jPanelTrocaLayout = new javax.swing.GroupLayout(jPanelTroca);
        jPanelTroca.setLayout(jPanelTrocaLayout);
        jPanelTrocaLayout.setHorizontalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(solicitarTroca, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(132, 132, 132))
        );
        jPanelTrocaLayout.setVerticalGroup(
            jPanelTrocaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTrocaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(solicitarTroca)
                .addContainerGap())
        );

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new java.awt.CardLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setLayout(new java.awt.CardLayout());

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51), 5));
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Nome");
        jPanel8.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 45, 199, 21));

        jLabel9.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(102, 102, 102));
        jLabel9.setText("Material");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 104, 244, 21));

        jLabel10.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 102, 102));
        jLabel10.setText("Peso (g)");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 104, 199, 21));

        jTextFieldPesoM.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldPesoM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesoMActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldPesoM, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 131, 199, 21));

        jLabel11.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(102, 102, 102));
        jLabel11.setText("Espessura (mm)");
        jPanel8.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 222, 199, 21));

        jLabel12.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(102, 102, 102));
        jLabel12.setText("Bordas");
        jPanel8.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 163, 244, 21));

        jComboBoxCoresM.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxCoresM.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxCoresM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Coroa prateada e núcleo dourado", "Coroa dourada e núcleo prateado", "Dourada", "Cobre", "Prata" }));
        jComboBoxCoresM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.add(jComboBoxCoresM, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 72, 244, 21));

        jLabel13.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Cores");
        jPanel8.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 45, 244, 21));

        jTextFieldNomeM.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldNomeM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeMActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldNomeM, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 72, 199, 21));

        jLabel14.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(102, 102, 102));
        jLabel14.setText("Diametro (mm)");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 163, 199, 21));

        jTextFieldDiametroM.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldDiametroM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDiametroMActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldDiametroM, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 190, 199, 21));

        jLabel15.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Foto da moeda");
        jPanel8.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 163, 220, 21));

        jTextFieldEspessuraM.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldEspessuraM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEspessuraMActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldEspessuraM, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 249, 199, 21));

        jComboBoxMaterialM.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxMaterialM.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxMaterialM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxMaterialM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMaterialMActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxMaterialM, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 131, 244, 21));

        jComboBoxBordasM.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxBordasM.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxBordasM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Serrilhado com inscrição", "Liso e serrilhado", "Ondulado", "Liso" }));
        jComboBoxBordasM.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxBordasM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBordasMActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxBordasM, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 190, 244, 21));

        jLabel16.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Método de cunhagem");
        jPanel8.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 281, 199, 21));

        jTextFieldMetodoCunhagemM.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldMetodoCunhagemM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldMetodoCunhagemMActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldMetodoCunhagemM, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 308, 199, 21));

        jLabel17.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setText("Data de fabricação");
        jPanel8.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 45, -1, 21));

        jLabel18.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Data de aquisição");
        jPanel8.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 45, 106, 21));

        jLabel19.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Valor (Fabricação)");
        jPanel8.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 104, -1, 21));

        jLabel20.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(102, 102, 102));
        jLabel20.setText("Estado de preservação");
        jPanel8.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 222, -1, 21));

        jComboBoxEstado.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxEstado.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Novo", "Usado", "Precário" }));
        jComboBoxEstado.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEstadoActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 249, 131, 21));

        jLabel21.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Descrição");
        jPanel8.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 281, 89, 21));

        jTextFieldEdicao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldEdicao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldEdicaoActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldEdicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 357, 199, 21));

        jLabel22.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Edição");
        jPanel8.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 335, 199, 16));

        jLabel23.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(102, 102, 102));
        jLabel23.setText("Valor (Aquisição)");
        jPanel8.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(614, 104, 105, 21));

        jLabelFoto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Enari - imagem(item).png"))); // NOI18N
        jLabelFoto.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabelFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(21, 30, 51)));
        jLabelFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabelFoto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelFotoMouseClicked(evt);
            }
        });
        jPanel8.add(jLabelFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 190, 220, 188));

        try {
            jTextFieldAquisicao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldAquisicao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldAquisicao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPanel8.add(jTextFieldAquisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(613, 72, 106, 21));

        try {
            jTextFieldFabricacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jTextFieldFabricacao.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldFabricacao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPanel8.add(jTextFieldFabricacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 72, 108, 21));

        jTextFieldDescricao.setColumns(20);
        jTextFieldDescricao.setLineWrap(true);
        jTextFieldDescricao.setRows(3);
        jTextFieldDescricao.setWrapStyleWord(true);
        jTextFieldDescricao.setSelectionColor(new java.awt.Color(21, 30, 51));
        jScrollPane1.setViewportView(jTextFieldDescricao);

        jPanel8.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 308, 245, 70));

        jLabel26.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(102, 102, 102));
        jLabel26.setText("R$");
        jPanel8.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 131, 18, 21));

        jTextFieldVFabricacao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVFabricacao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVFabricacao1.setSelectionColor(new java.awt.Color(21, 30, 51));
        jPanel8.add(jTextFieldVFabricacao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(521, 131, 84, 21));

        jLabel25.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(102, 102, 102));
        jLabel25.setText("R$");
        jPanel8.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(615, 131, -1, 21));

        jTextFieldVAquisicao1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#,###.00"))));
        jTextFieldVAquisicao1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldVAquisicao1.setSelectionColor(new java.awt.Color(21, 30, 51));
        jTextFieldVAquisicao1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldVAquisicao1ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextFieldVAquisicao1, new org.netbeans.lib.awtextra.AbsoluteConstraints(634, 131, 85, 21));

        jComboBoxPrivacidade.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jComboBoxPrivacidade.setForeground(new java.awt.Color(102, 102, 102));
        jComboBoxPrivacidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Público", "Amigos", "Privado" }));
        jComboBoxPrivacidade.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jComboBoxPrivacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxPrivacidadeActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBoxPrivacidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 249, 89, 21));

        jLabel24.setFont(new java.awt.Font("Verdana", 0, 11)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(102, 102, 102));
        jLabel24.setText("Privacidade");
        jPanel8.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(236, 222, 89, 21));

        jLabel2.setBackground(new java.awt.Color(21, 30, 51));
        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(21, 30, 51));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro de Moeda");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 11, 721, -1));

        Voltar.setBackground(new java.awt.Color(21, 30, 51));
        Voltar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Voltar.setForeground(new java.awt.Color(255, 255, 255));
        Voltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Voltar.setText("Cadastradas");
        Voltar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Voltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Voltar.setOpaque(true);
        Voltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VoltarMouseExited(evt);
            }
        });
        jPanel8.add(Voltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 399, 112, 21));

        Editar.setBackground(new java.awt.Color(21, 30, 51));
        Editar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Editar.setForeground(new java.awt.Color(255, 255, 255));
        Editar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Editar.setText("Editar");
        Editar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Editar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Editar.setOpaque(true);
        Editar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EditarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EditarMouseExited(evt);
            }
        });
        jPanel8.add(Editar, new org.netbeans.lib.awtextra.AbsoluteConstraints(137, 399, 53, 21));

        Trocar.setBackground(new java.awt.Color(21, 30, 51));
        Trocar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Trocar.setForeground(new java.awt.Color(255, 255, 255));
        Trocar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Trocar.setText("Trocar");
        Trocar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Trocar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Trocar.setOpaque(true);
        Trocar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrocarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TrocarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TrocarMouseExited(evt);
            }
        });
        jPanel8.add(Trocar, new org.netbeans.lib.awtextra.AbsoluteConstraints(196, 399, 61, 21));

        Salvar.setBackground(new java.awt.Color(21, 30, 51));
        Salvar.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        Salvar.setForeground(new java.awt.Color(255, 255, 255));
        Salvar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Salvar.setText("Salvar");
        Salvar.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        Salvar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Salvar.setOpaque(true);
        Salvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                SalvarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SalvarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SalvarMouseExited(evt);
            }
        });
        jPanel8.add(Salvar, new org.netbeans.lib.awtextra.AbsoluteConstraints(502, 399, 79, 21));

        CadastrarMo.setBackground(new java.awt.Color(21, 30, 51));
        CadastrarMo.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        CadastrarMo.setForeground(new java.awt.Color(255, 255, 255));
        CadastrarMo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CadastrarMo.setText("Cadastrar moeda");
        CadastrarMo.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED)));
        CadastrarMo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CadastrarMo.setOpaque(true);
        CadastrarMo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CadastrarMoMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                CadastrarMoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CadastrarMoMouseExited(evt);
            }
        });
        jPanel8.add(CadastrarMo, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 399, 132, 21));

        jSeparator1.setBackground(new java.awt.Color(21, 30, 51));
        jSeparator1.setForeground(new java.awt.Color(21, 30, 51));
        jSeparator1.setOpaque(true);
        jPanel8.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 389, 700, 4));

        jPanel7.add(jPanel8, "card2");

        getContentPane().add(jPanel7, "card2");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void solicitarTrocaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solicitarTrocaActionPerformed
        if (jtbListarMoeda.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Nenhuma moeda selecionada.");}
        Integer idCamiseta = (Integer) jtbListarMoeda.getValueAt(jtbListarMoeda.getSelectedRow(), 0);
        Troca troca=new Troca(idUserLogando,moeda.getIdUsuario(),4,(Item)Dados.getMoedasBD().get(idCamiseta),(Item)moeda);
        solicitarTroca.setText("Troca solicitada !");
        solicitarTroca.setEnabled(false);
        solicitarTroca.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_solicitarTrocaActionPerformed

    private void jComboBoxPrivacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxPrivacidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxPrivacidadeActionPerformed

    private void jTextFieldVAquisicao1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldVAquisicao1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldVAquisicao1ActionPerformed

    private void jLabelFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelFotoMouseClicked
        // TODO add your handling code here:
        String caminho;
        JFileChooser arquivo = new JFileChooser();//INSTANCIA O SELECIONADOR
        File diretorio = new File("C:\\Users\\aluno\\Pictures");//NOVO CODIGO PARA DEFINIR PASTA RAIZ DO FILE CHOOSER
        arquivo.setCurrentDirectory(diretorio);
        arquivo.showOpenDialog(null);
        caminho = arquivo.getSelectedFile().getAbsolutePath(); //VARIAVEL CAMINHO RECEBE O ENDEREÇO DA IMAGEM
        jLabelFoto.setSize(220,188);
        img = new ImageIcon(caminho).getImage().getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT);//NOVO COD PARA DEFINIR TAMANHO UNICO DE IMAGENS
        jLabelFoto.setIcon(new ImageIcon(img)); //LBIMAGEM RECEBERA A IMAGEM        // TODO add your handling code here:
        if(visitante==true){} else {
            moeda.setFoto(img.getScaledInstance(jLabelFoto.getWidth(), jLabelFoto.getHeight(), Image.SCALE_DEFAULT));
        }
    }//GEN-LAST:event_jLabelFotoMouseClicked

    private void jTextFieldEdicaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEdicaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEdicaoActionPerformed

    private void jComboBoxEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEstadoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEstadoActionPerformed

    private void jTextFieldMetodoCunhagemMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldMetodoCunhagemMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldMetodoCunhagemMActionPerformed

    private void jComboBoxMaterialMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMaterialMActionPerformed
        if(this.jComboBoxMaterialM.getSelectedIndex()==1){
            String novoMaterial=JOptionPane.showInputDialog("Qual é o Material?").toUpperCase();
            Dados.getMaterial().add(novoMaterial);
            jComboBoxMaterialM.removeAllItems();
            Iterator<String> material = Dados.getMaterial().iterator();
            while(material.hasNext()){
                String nomesitens = material.next();

                this.jComboBoxMaterialM.addItem(nomesitens);
            }
        }

    }//GEN-LAST:event_jComboBoxMaterialMActionPerformed

    private void jTextFieldEspessuraMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldEspessuraMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldEspessuraMActionPerformed

    private void jTextFieldDiametroMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDiametroMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDiametroMActionPerformed

    private void jTextFieldNomeMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeMActionPerformed

    private void jTextFieldPesoMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesoMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPesoMActionPerformed

    private void VoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseClicked
        JIFrameListarMoeda jIFrameListarMoeda = new JIFrameListarMoeda(idUserLogando);
        jIFrameListarMoeda.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarMoeda);
        jIFrameListarMoeda.setVisible(true);
        try {jIFrameListarMoeda.setMaximum(true);
        } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_VoltarMouseClicked

    private void EditarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseClicked
        atividadeEditar=new Atividade( moeda.getIdItem(),4, idUserLogando, 3, "Editou","MOEDA");
        atividadeEditar.add((Item) Dados.getMoedasBD().get(atividadeEditar.getIdItem()).clone());
        atividadeEditar.salvar();
        this.Salvar.setVisible(true);//oculta o botão salvar
        //habilita a edicao dos campos
        this.jTextFieldNomeM.setEditable(true);
        this.jTextFieldPesoM.setEditable(true);
        this.jTextFieldDiametroM.setEditable(true);
        this.jTextFieldEspessuraM.setEditable(true);
        this.jTextFieldMetodoCunhagemM.setEditable(true);
        this.jComboBoxMaterialM.setEnabled(true);
        this.jComboBoxCoresM.setEnabled(true);
        this.jComboBoxBordasM.setEnabled(true);
        //dentro da classe item
        this.jTextFieldEdicao.setEditable(true);
        this.jComboBoxEstado.setEnabled(true);
        this.jTextFieldDescricao.setEditable(true);
        this.jTextFieldFabricacao.setEditable(true);
        this.jTextFieldAquisicao.setEditable(true);
        this.jTextFieldVFabricacao1.setEditable(true);
        this.jTextFieldVAquisicao1.setEditable(true);
        this.jComboBoxPrivacidade.setEnabled(true);
    }//GEN-LAST:event_EditarMouseClicked

    private void TrocarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseClicked
        listarMoeda();
        JOptionPane.showMessageDialog(null,jPanelTroca);
    }//GEN-LAST:event_TrocarMouseClicked

    private void SalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseClicked
        Moeda novaMoeda=moeda;
        //dentro da classe moeda
        novaMoeda.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        novaMoeda.setNomeM(this.jTextFieldNomeM.getText());
        novaMoeda.setPesoM(this.jTextFieldPesoM.getText());
        novaMoeda.setDiametroM(this.jTextFieldDiametroM.getText());
        novaMoeda.setEspessuraM(this.jTextFieldEspessuraM.getText());
        novaMoeda.setMetodoCunhagemM(this.jTextFieldMetodoCunhagemM.getText());
        novaMoeda.setIdMaterial(this.jComboBoxMaterialM.getSelectedIndex());
        novaMoeda.setCoresM(this.jComboBoxCoresM.getSelectedItem().toString());
        novaMoeda.setBordaM(this.jComboBoxBordasM.getSelectedItem().toString());
        //dentro da classe item
        novaMoeda.setEdicao(this.jTextFieldEdicao.getText());
        novaMoeda.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        novaMoeda.setDescricao(this.jTextFieldDescricao.getText());
        novaMoeda.setFabricacao(this.jTextFieldFabricacao.getText());
        novaMoeda.setAquisicao(this.jTextFieldAquisicao.getText());
        novaMoeda.setVFabricacao(jTextFieldVFabricacao1.getText());
        novaMoeda.setVAquisicao(jTextFieldVAquisicao1.getText());
        novaMoeda.setFoto(img);
        //armazena o ID do item
        Dados.getMoedasBD().get(atividadeEditar.getIdItem()).equals(novaMoeda);
        atividadeEditar.add(novaMoeda);
        atividadeEditar.bloquearAtividades(idUserLogando);
        JIFrameListarMoeda jIFrameListarMoeda = new JIFrameListarMoeda(idUserLogando);
        jIFrameListarMoeda.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarMoeda);
        jIFrameListarMoeda.setVisible(true);
        try {jIFrameListarMoeda.setMaximum(true);
        } catch (PropertyVetoException ex) {  }
        this.doDefaultCloseAction();//fim atual
    }//GEN-LAST:event_SalvarMouseClicked

    private void CadastrarMoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMoMouseClicked
        addMoeda();
    }//GEN-LAST:event_CadastrarMoMouseClicked

    private void VoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseEntered
        Voltar.setOpaque(true);
        Voltar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_VoltarMouseEntered

    private void VoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VoltarMouseExited
        Color padrao=new Color(21,30,51);
        Voltar.setBackground(padrao);
    }//GEN-LAST:event_VoltarMouseExited

    private void EditarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseEntered
        Editar.setOpaque(true);
        Editar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_EditarMouseEntered

    private void EditarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditarMouseExited
        Color padrao=new Color(21,30,51);
        Editar.setBackground(padrao);
    }//GEN-LAST:event_EditarMouseExited

    private void TrocarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseEntered
        Trocar.setOpaque(true);
        Trocar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_TrocarMouseEntered

    private void TrocarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrocarMouseExited
        Color padrao=new Color(21,30,51);
        Trocar.setBackground(padrao);
    }//GEN-LAST:event_TrocarMouseExited

    private void SalvarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseEntered
        Salvar.setOpaque(true);
        Salvar.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_SalvarMouseEntered

    private void SalvarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SalvarMouseExited
        Color padrao=new Color(21,30,51);
        Salvar.setBackground(padrao);
    }//GEN-LAST:event_SalvarMouseExited

    private void CadastrarMoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMoMouseEntered
        CadastrarMo.setOpaque(true);
        CadastrarMo.setBackground(Color.DARK_GRAY); 
    }//GEN-LAST:event_CadastrarMoMouseEntered

    private void CadastrarMoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CadastrarMoMouseExited
        Color padrao=new Color(21,30,51);
        CadastrarMo.setBackground(padrao);
    }//GEN-LAST:event_CadastrarMoMouseExited

    private void solicitarTrocaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseEntered
        if(solicitarTroca.isEnabled()==true){
        solicitarTroca.setOpaque(true);
        solicitarTroca.setBackground(Color.DARK_GRAY); 
        }
    }//GEN-LAST:event_solicitarTrocaMouseEntered

    private void solicitarTrocaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_solicitarTrocaMouseExited
        Color padrao=new Color(21,30,51);
        solicitarTroca.setBackground(padrao);
    }//GEN-LAST:event_solicitarTrocaMouseExited

    private void jComboBoxBordasMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBordasMActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBordasMActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CadastrarMo;
    private javax.swing.JLabel Editar;
    private javax.swing.JLabel Salvar;
    private javax.swing.JLabel Trocar;
    private javax.swing.JLabel Voltar;
    private javax.swing.JComboBox jComboBoxBordasM;
    private javax.swing.JComboBox jComboBoxCoresM;
    private javax.swing.JComboBox jComboBoxEstado;
    private javax.swing.JComboBox jComboBoxMaterialM;
    private javax.swing.JComboBox jComboBoxPrivacidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelFoto;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanelTroca;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JFormattedTextField jTextFieldAquisicao;
    private javax.swing.JTextArea jTextFieldDescricao;
    private javax.swing.JTextField jTextFieldDiametroM;
    private javax.swing.JTextField jTextFieldEdicao;
    private javax.swing.JTextField jTextFieldEspessuraM;
    private javax.swing.JFormattedTextField jTextFieldFabricacao;
    private javax.swing.JTextField jTextFieldMetodoCunhagemM;
    private javax.swing.JTextField jTextFieldNomeM;
    private javax.swing.JTextField jTextFieldPesoM;
    private javax.swing.JFormattedTextField jTextFieldVAquisicao1;
    private javax.swing.JFormattedTextField jTextFieldVFabricacao1;
    private javax.swing.JTable jtbListarMoeda;
    private javax.swing.JButton solicitarTroca;
    // End of variables declaration//GEN-END:variables
public void addMoeda(){
        String NOME = jTextFieldNomeM.getText();
        Moeda MOEDA = new Moeda();
        boolean existeMoeda=false;
        for (int i = 0; i < Dados.getMoedasBD().size(); i++) {//percorre a lista de usuarios "lst"
                MOEDA = Dados.getMoedasBD().get(i);//paga o objeto da posição "i" e armazena no objeto "usuario" do tipo "Usuario"
            if (NOME.equals(MOEDA.getNomeM())){jLabel8.setText("Moeda já cadastrada");
            existeMoeda=true;
            break;}
        }
        
            if(!existeMoeda){
        //define o usuario dono da moeda
        moeda.setIdUsuario(idUserLogando);
        //dentro da classe moeda
        moeda.setNomeM(this.jTextFieldNomeM.getText());
        moeda.setIdMaterial(this.jComboBoxMaterialM.getSelectedIndex());
        moeda.setPesoM(this.jTextFieldPesoM.getText());
        moeda.setDiametroM(this.jTextFieldDiametroM.getText());
        moeda.setEspessuraM(this.jTextFieldEspessuraM.getText());
        moeda.setCoresM(this.jComboBoxCoresM.getSelectedItem().toString());
        moeda.setMetodoCunhagemM(this.jTextFieldMetodoCunhagemM.getText());
        moeda.setBordaM(this.jComboBoxBordasM.getSelectedItem().toString());
        //dentro da classe item
        moeda.setPrivacidade(this.jComboBoxPrivacidade.getSelectedIndex());
        moeda.setFabricacao(this.jTextFieldFabricacao.getText());
        moeda.setAquisicao(this.jTextFieldAquisicao.getText());
        moeda.setEdicao(this.jTextFieldEdicao.getText());
        moeda.setEstadoPreservacao(this.jComboBoxEstado.getSelectedItem().toString());
        moeda.setDescricao(this.jTextFieldDescricao.getText());        
        moeda.setVFabricacao(jTextFieldVFabricacao1.getText());        
        moeda.setVAquisicao(jTextFieldVAquisicao1.getText());  
        moeda.setFoto(img);
        moeda.salvar();
        //Atividade de adição do moeda
       
        int idCarta=(int) (Math.random() * Cartas.getMoedas().size()-1);
        if(idCarta<0){idCarta=0;}
        Dados.getUsuariosBD().get(idUserLogando).setCartaMoeda(idCarta);
        
        atividade=new Atividade( moeda.getIdItem(),4, idUserLogando, 1, "Adicionou","MOEDA");
        atividade.salvar();
        atividade.bloquearAtividades(idUserLogando);
        //cria a tela de colecoes
        JIFrameListarMoeda jIFrameListarMoeda = new JIFrameListarMoeda(idUserLogando);
        jIFrameListarMoeda.idUserLogando=Principal.getIdUserLogando();
        this.getDesktopPane().add(jIFrameListarMoeda);
        jIFrameListarMoeda.setVisible(true);
        try {jIFrameListarMoeda.setMaximum(true);
         } catch (PropertyVetoException ex) {  }
        
        this.doDefaultCloseAction();//fim atual
        
        }
}
 private void listarMoeda(){
        DefaultTableModel dtm = (DefaultTableModel) jtbListarMoeda.getModel();
        dtm.setNumRows(0);
        
        for (Moeda moedaTable :  Dados.getUsuariosBD().get(idUserLogando).getColecaoMoeda()) {
            dtm.addRow(new Object[]{moedaTable.getIdItem(),moedaTable.getNomeM(), moedaTable.getEdicao()});
            
        }
    }

}
